autobrr/autobrr

- internal/action/exec.go
- internal/action/macros.go
- internal/action/macros_test.go
- internal/action/qbittorrent.go
- internal/action/service.go
- internal/announce/parse.go
- internal/announce/service.go
- internal/release/process.go
Implement exec action.
Takes a program and arguments and tries to execute it.
Added support for a couple "macros" or variable replacements like [autodl-irssi](https://autodl-community.github.io/autodl-irssi/configuration/actions/#macros) does.
Currently supported:
- `{{.TorrentName}}` - Torrent name/release name
- `{{.TorrentPathName}}` - temp torrent file
- `{{.TorrentUrl}}` - torrent url which was used. (contains passkeys etc)
Which can then be added and used in the exec actions argument part like: `add {{.TorrentPathName}} --category test`.
With this in place autobrr can now be used like autodl-irssi to use external programs like `qbittorrent-cli`, `qbittools`, `qbit-race`, `deluge-automanage`, `deluge-console`, custom pvr commands, and so on!
> Feature: Exec action

- internal/action/run.go
Save file with `.torrent` extension to watch folder actions.
> Fix: Add extension to watch folder action

- web/src/forms/settings/IndexerForms.tsx
Name was empty on the indexer during setup, which made it not show in the Indexers dropdown on filters or listview.
> Fix: Empty indexer name on setup

- internal/announce/announce.go
- internal/irc/handler.go
Pass arg to `go func` and extract announce processor to it's own package.
> Fix: Announce parse queue

- internal/announce/announce_test.go
- internal/indexer/definitions/milkie.yaml
Add url encoding on the apikey for Milkie. And add some tests for `announce.processTorrentUrl` to verify expected behavior.
> Fix(indexers): Milkie url encode apikey and add tests

- internal/announce/announce.go
What: Using `break` in the announce processor outer loop caused it to exit. 
Fix: Use `continue` instead of `break` to not exit outer loop
> Fix: Unintetional exit from announce processor

- internal/action/service.go
- internal/database/action.go
- internal/database/filter.go
- internal/database/irc.go
- internal/domain/action.go
- internal/domain/filter.go
- internal/filter/service.go
- internal/http/action.go
- internal/http/filter.go
- web/src/screens/filters/details.tsx
What: Filter actions could not be deleted or updated properly.
Fix: Run store in transaction and delete connections before store, to allow for updates as well as delete.
Also:
- Improve the filter indexer connections handling
- Update query keys for web data fetcher on filters for better caching etc
> Fix: Store filter actions

- web/src/domain/interfaces.ts
- web/src/screens/filters/details.tsx
What: The filter page used the wrong property for tags and could therefore not save or load them correctly.
Fix: Change from `match_tags` to `tags`.
> Fix(filters): use correct property for tags

- internal/indexer/definitions/btn.yaml
- pkg/btn/btn.go
- pkg/jsonrpc/jsonrpc.go
What: 
* Api key and torrentId in wrong order
* Set hardcoded ID in `jsonrpc` request object
* Parse`torrentId` from url
Fixes #68
> Fix(indexers): BTN api client

- internal/irc/handler.go
- web/src/screens/settings/Irc.tsx
Inactive/disabled networks are now gray, and enabled but errored networks are red.
> Fix: IRC network distinguish inactive and error

- internal/database/download_client.go
With the change of database driver we now have to store json data as a regular string.
> Fix: Save download client json settings

- README.md
- internal/domain/release.go
- internal/indexer/definitions/animebytes.yaml
- web/src/domain/constants.ts
what the title says, but the regex need improvement so before merging, if you guys can help me improve the regex would be much appreciated I tested it with the current one it works great but sometimes AB doesn't provide the uploader or just missing some stuff for example;
```
Ore no Nounai Sentakushi ga, Gakuen Lovecome o Zenryoku de Jama Shiteiru - OVA  [2014] :: Blu-ray / MKV / h264 10-bit / 1080p / FLAC 2.0 / Softsubs (Drag) / Freeleech || https://animebytes.tv/torrents.php?id=18491&torrentid=97215968 || comedy, harem
BanG Dream! 3rd Season - TV Series  [2020] :: Blu-ray / MKV / h265 10-bit / 1080p / FLAC 5.0 / RAW (LoliHouse) / Freeleech || https://animebytes.tv/torrents.php?id=62837&torrentid=972135926 || music || Uploaded by: redacted
Koi Kaze - TV Series  [2004] :: DVD / MKV / h264 …
```
> Indexers: Add AnimeBytes

- internal/indexer/definitions/morethantv.yaml
MTV doesn't announce category separately, but it's in the tags. So this PR add support to parse their category from tags.
> Feature(indexers): MTV parse category from tags

- internal/indexer/definitions/morethantv.yaml
- internal/indexer/definitions/torrentday.yaml
- internal/indexer/definitions/torrentseeds.yaml
Some indexers were using the wrong var for size, and thus not matching correctly.
> fix(indexers): use torrentsize instead of size

- internal/database/action.go
- internal/database/filter.go
- internal/database/indexer.go
- internal/domain/action.go
- internal/domain/filter.go
- internal/domain/indexer.go
- internal/filter/service.go
- internal/http/filter.go
- internal/indexer/service.go
- web/src/screens/filters/details.tsx
Some more fixes to mitigate issues with a blank page when loading filters.
- Load indexers only on the general tab, and not the whole filter
- add loading state to the indexers dropdown
> Fix: blank page loading filters

- web/src/utils/Context.ts
Fix set theme. 
Call SettingsContext.set regardless of browsers media preference (fixes the need to double toggle to apply the dark theme).
Fixes #110
> fix: set theme

- internal/action/run.go
Related to #119
After some debugging I figured out that when `release.TorrentTmpFile` was not empty the `tmpFile` variable would not be set. 
Resulting in sending an empty variable to the download client's action function. That ultimately resulted in a file not found error when trying to send the torrent file to the download client.
Fixed by adding an else condition setting `tmpFile` to `release.TorrentTmpFile` (when it is not empty).
Even though this only happened to me on deluge, I added the else condition to all instances where this could possibly happen.
---
edit: I've tested it by building the container and deluge is now correctly getting the torrent added
> fix: empty tmpFile var passed to download client's action

- internal/indexer/definitions/orpheus.yaml
Looks like OPS has recently made changes and does not require the `authkey` anymore, and does not even provide it anywhere. This removes the setting for `authkey` and updates the download url to not need it.
> fix: indexers orpheus torrent url

- internal/domain/release.go
- internal/filter/service.go
This fixes a bug where error on downloading torrent would cause a panic because of missing data. The file downloader didn't set a new error when status was not 200, and thus returning a `nil` error which could not be handled by the caller.
> Fix: Handle download failure

- internal/action/lidarr.go
Special handling for RED and OPS because their torrent names contain to little info
`Artist - Album` is not enough for Lidarr to make a decision. It needs year like `Artist - Album 2022`
> fix: lidarr add more info to push

- web/package.json
- web/src/api/APIClient.ts
- web/src/forms/filters/FilterAddForm.tsx
- web/src/forms/settings/DownloadClientForms.tsx
- web/src/forms/settings/IndexerForms.tsx
- web/src/forms/settings/IrcForms.tsx
- web/src/screens/Dashboard.tsx
- web/src/screens/Logs.tsx
- web/src/screens/Releases.tsx
- web/src/screens/auth/login.tsx
- web/src/screens/auth/logout.tsx
- web/src/screens/filters/details.tsx
- web/src/screens/filters/list.tsx
- web/src/screens/settings/Application.tsx
- web/src/screens/settings/DownloadClient.tsx
- web/src/screens/settings/Indexer.tsx
- web/src/screens/settings/Irc.tsx
chore: prevent craco from opening a new tab every time you run "npm run start"
refactor: refactored APIClient.ts with a new fetch wrapper and changed it into an explicit-import.
chore: cleaned up code, deleted 2mo+ useless old comments. (~80% of PR is just from deleting comments in a single file and then reformatting that same file)
fix: fixed parameter collision in screens/filters/details.tsx
fix: override react-select's Select component style to make it consistent. addresses #116
I'd give the new HttpClient another testing from a different person. On my side, everything works as it should, since it's just a rewrite of old, messy,  code. But better be safe than sorry.
> Refactor APIClient, clean up code, fix #116

- internal/action/qbittorrent.go
- internal/action/run.go
- pkg/qbittorrent/methods.go
The download client rule check for `Max active downloads` did not exit properly if it was reached.
* Fixed the `max active downloads` check by exiting early
* Refactored the `re-announce` and changed initial delay to 4 seconds before recheck
* Added separate method in qbit client to only get active downloads
> Fix: Download clients rule checking

- web/package.json
Breaking changes in `react-ridge-state` `4.2.4` so lets pin `4.2.2` until it's fixed.
Related issue: https://github.com/web-ridge/react-ridge-state/issues/26
> fix: pin react-ridge-state

- internal/announce/announce.go
- internal/domain/indexer.go
- internal/domain/release.go
- internal/domain/release_test.go
- internal/indexer/definitions/alpharatio.yaml
This PR add support to force set what size unit to be used. 
AR does not specify a size unit in the announce, but it's always sent as megabytes (MB) so this adds support to set what unit should be used.
> feat(indexers): definitions set forcesizeunit

- internal/action/deluge.go
- internal/action/exec.go
- internal/action/macros.go
- internal/action/macros_test.go
- internal/action/qbittorrent.go
- internal/action/run.go
Add more variables to be used in fields for actions, and make them usable in more fields.
New variables:
* Indexer `{{.Indexer}}`
* TorrentHash `{{.TorrentHash}}`
* Resolution `{{.Resolution}}`
* Source `{{.Source}}`
* HDR `{{.HDR}}`
* Season `{{.Season}}`
* Episode `{{.Episode}}`
* Year `{{.Year}}`
* Month `{{.Month}}`
* Day `{{.Day}}`
* Hour `{{.Hour}}`
* Minute `{{.Minute}}`
* Second `{{.Second}}`
And usable in the action fields for:
* Watch folder
* Label
* Tags
* Category
* Save Path
Related issue #147
> feat(actions): add more macro variables

- internal/database/filter.go
- internal/database/migrate.go
- internal/domain/filter.go
- web/src/screens/filters/details.tsx
- web/src/types/Filter.d.ts
Add support for priority on filters.
When making the filter check it will fetch filters and order and run them by `priority`, highest to lowest.
Supports positive and negative numbers. Default `priority` is set to `0`.
> feat(filters): add priority

- .goreleaser.yml
Update goreleaser config to use new "group changelog" feature. https://carlosbecker.com/posts/goreleaser-changelog-groups/
> build: goreleaser group changelog

- Dockerfile
cURL is a very useful utility to have in the image - I'm using it with exec to notify other applications of the event.
> docker: Add curl to base image

- internal/action/qbittorrent.go
- internal/database/download_client.go
- internal/database/migrate.go
- internal/domain/client.go
- internal/download_client/connection.go
- internal/download_client/service.go
- internal/http/download_client.go
- pkg/qbittorrent/client.go
- web/src/forms/settings/DownloadClientForms.tsx
- web/src/types/Download.d.ts
Add option for download clients (qbittorrent, deluge) to skip TLS verification to allow for self signed certs.
* Rename SSL to TLS
* Add option/toggle to create and edit download client
Fixes #175
> feat: download clients skip tls verify option

- internal/action/run.go
Running actions in parallel might case a race condition if the torrent file isn't yet downloaded. If having more than one action per filter all of them will try and download the file which is not good.
Fixes #179
> fix(actions): dont run in parallel

- internal/indexer/definitions/torrentsyndikat.yaml
Tested it for a while. Should work now.
I used origin to mark the release source. (P2P, SCENE, O-SCENE)
Scene is for unpacked Scene Releases and O-Scene for untouched Scene Releases.
> Indexer: Adding Torrent-Syndikat

- internal/action/run.go
- internal/database/action.go
- internal/database/migrate.go
- internal/database/utils.go
- internal/domain/action.go
- web/src/components/inputs/input.tsx
- web/src/domain/constants.ts
- web/src/screens/filters/details.tsx
- web/src/types/Filter.d.ts
Add support for webhook action. This will allow for basic webhooks for now to integrate external programs easier like [mmgoodnow/cross-seed](https://github.com/mmgoodnow/cross-seed).
Currently only `POST` and json data.
Future improvements:
* set method (GET, POST, PUT, PATCH, DELETE)
* set data type (URL encoded, JSON)
* set headers
Resolves #171
> feat(actions): add webhook support

- internal/indexer/service.go
Background:
> 
> Currently autobrr loads all custom indexer definition files which contain the string .yaml from a given input directory. See https://github.com/autobrr/autobrr/commit/2d643af05dc3ecb07aa4f75594f803e4811b51f8#diff-9c51825dc11242e2fc4fbd0a973487828c090200ff21d88b605bf07c3144623eR373
> 
> The problem with this is that some people may end up experimenting and creating a backup file, say, test.yaml.bak which certainly shouldn't be loaded. Rather, just check if the file ends with .yaml (i.e. use HasSuffix or an equivalent function).
Fixes #187
> fix(indexers): only load definitions with .yaml ext

- internal/action/run.go
json.marshal escapes quotes unfortunately, which generates invalid json ironically.
> fix(actions): webhook double escaping with json.marshal

- internal/indexer/definitions/revolutiontt.yaml
Currently releases are saved as !new ReleaseName.720p.HDTV.x264-NoGroup.
Adding double quotes on pattern to avoid this.
> fix(indexers): update pattern RevTT

- internal/database/filter.go
Make sure to only grab filters from active indexers.
> fix(filters): load only active indexers

- internal/indexer/definitions/revolutiontt.yaml
Use single quotes for regex instead of double quotes.
> fix(indexers): revtt regex escape

- config.toml
- docker-compose.yml
- internal/config/config.go
- web/package.json
- web/src/utils/index.ts
Change default port from `8989` to `7474` to not collide with any existing apps in the Hotio or Linuxserver catalogue. 
Should only affect new installs.
> feat: change default port

- internal/indexer/definitions/animebytes.yaml
animebytes wouldn't match at all for me as the whitespace before the [year] seems to be double `A0` characters, the added test includes them
> fix(indexers): animebytes fix regex for invisible A0 whitespace characters

- cmd/autobrr/main.go
- internal/action/run.go
- internal/action/service.go
- internal/announce/announce.go
- internal/announce/service.go
- internal/database/action.go
- internal/domain/action.go
- internal/domain/event.go
- internal/domain/filter.go
- internal/domain/release.go
- internal/domain/release_test.go
- internal/filter/service.go
- internal/irc/handler.go
- internal/irc/service.go
- internal/notification/discord.go
- internal/release/service.go
- pkg/lidarr/lidarr.go
- pkg/qbittorrent/client.go
- pkg/radarr/radarr.go
- pkg/sonarr/sonarr.go
- pkg/whisparr/whisparr.go
Refactor of the filters and how actions are handled. Specifically how arr actions are handled with rejections.
A rejection from an arr app will now work similar as the other filter checks and simply run next filter. It keeps track of the arr instance by clientId to not try and send the same release again if another filter have the same action. If it finds it's already been run it will continue to next filter.
This now makes the filtering with arr actions work as part of the filtering decision which it did not do before.
This refactor will also help with adding pre-checks before filtering, like running a cross-seed match or ignore duplicate releases etc.
Fixes #163 
* Increase timeouts for arr clients to 30 seconds, up from 10.
> refactor: filter and action flow

- cmd/autobrr/main.go
- internal/database/database.go
- internal/http/health.go
- internal/http/server.go
Add healthcheck endpoints - liveness and readiness.
Useful for container deployments.
New endpoints. Both answers with appropiate status codes and body text as `text/plain`
- `/api/healtz/liveness` - 200 OK and OK in body
- `/api/healtz/readiness` - 200 OK and OK in body if databse ping is ok. If not, 500 and `Unhealthy. Database unreachable`
> feat(http): add healthcheck endpoints liveness and readiness

- internal/domain/release.go
- internal/domain/release_test.go
Ran into a case where resolution would be parsed into I instead of 2160p with the release `I Am Movie 2007 Theatrical UHD BluRay 2160p DTS-HD MA 5.1 DV HEVC HYBRID REMUX-GROUP1`.
> fix(release): edge case resolution parsing

- internal/indexer/definitions/hd-torrents.yaml
Use rss download link and tokens instead of cookies.
You'll have to set `rss key` and `rss token`.
> fix(indexers): use rss download url for hdt

- internal/database/feed.go
- internal/database/feed_cache.go
- internal/database/migrate.go
- internal/database/release.go
- internal/domain/feed.go
- internal/feed/torznab.go
Fix feedCache `ttl` from duration to timestamp with date + add time and rename "group" back to "release_group" due to compatibility.
> fix(feeds): ttl and correct field types

- internal/release/service.go
I haven't had a filter match yet to actually validate the delay, but I'll comment here when I do. It's the same logic as https://github.com/autobrr/autobrr/pull/255/commits/9a5b58beb3e295bd1d9f603aab50fe81a41d5f16 just in the new location.
> feat(actions): wait for the filter delay before performing actions

- internal/database/migrate.go
- web/src/forms/filters/FilterAddForm.tsx
Fix inconsistency in initial schema for sqlite where `filter.origins` was `NOT NULL` but the migrations was nullable.
- Fix initial schema (sqlite)
- Send empty origins array to fix current installs
> fix(db): initial schema filter origins nullable

- internal/domain/filter.go
- internal/domain/filter_test.go
In cases where users left a trailing comma on filters they would compare as empty strings as empty strings. `"" == ""` and give matches when they shouldn't.
> fix(filters): contains check empty

- internal/indexer/service.go
The form to add indexers was missing the `implementation` attribute and would not add irc indexers.
> fix(indexers): add

- internal/config/config.go
Accidentally removed the configpath for sqlite in previous PR when refactoring the config.
This adds it back.
> fix(config): load sqlite from configdir

- README.md
Not sure where I got that from in the first place. My bad.
> docs: removed deluge reannounce from feature list in readme

- go.mod
- go.sum
- internal/action/exec.go
- internal/action/exec_test.go
- internal/logger/mock.go
Properly parse exec args.
Fixes #171
> fix:(actions): exec shell expansion

- internal/action/qbittorrent.go
qBittorrent transparently moves this from B/s to KB/s in the UI and POST request. Presently if you specify 500 in the autobrr KB/s field for qBittorrent you get a staggering 500B/s.
> fix(download-clients): qBit transform speed limit from B to KB

- internal/database/release.go
- internal/domain/release.go
- internal/http/encoder.go
- internal/http/release.go
- internal/release/service.go
- web/src/api/APIClient.ts
- web/src/screens/dashboard/ActivityTable.tsx
- web/src/screens/releases/Filters.tsx
- web/src/screens/releases/ReleaseTable.tsx
Add ability to search releases in release list.
It's using basic `WHERE column LIKE '%something%'` to query data. Works for both `SQLite` and `postgres`.
- Use FST (Full text search) built into both sqlite and postgres
- refactor and optimize queries on dashboard
> feat(releases): search in ui

- web/src/screens/settings/Releases.tsx
possible todo: childless modals (i.e. those who do not have child components with a state) should all be using toggling internally, instead of doing it outside of the component?
> fix(web): modal double state update

- internal/domain/releasetags.go
- internal/domain/releasetags_test.go
Makes Autobrr match video containers from AB properly!
> fix(releases): ParseReleaseTags container matching

- internal/indexer/definitions/morethantv.yaml
Wrong tags used to map to category would cause it to fail early on.
> fix(indexers): mtv tags to category parsing

- internal/action/qbittorrent.go
- internal/action/run.go
- internal/action/service.go
- pkg/qbittorrent/client.go
- pkg/qbittorrent/methods.go
Due to no default logger being set for qbit it would panic.
* Set default logger
* Override logger if one is passed with settings
* Add panic recover on `RunAction`
> fix(download-clients): qbit panic on nil logger

- internal/action/exec.go
- internal/action/run.go
Only download torrent if needed for Exec and Webhook action.
Determined by if the `Exec Args` or `Webhook data` contains the macro variable `TorrentPathName`.
Fixes #194
> feat(actions): reduce metadata collection

- config.toml
- internal/config/config.go
Add `TRACE` in the list of log options. It's been a feature the whole time, just not explicit in the config.
> feat(config): loglevel default options add trace

- web/src/api/APIClient.ts
- web/src/components/alerts/index.tsx
- web/src/components/debug.tsx
- web/src/components/inputs/input_wide.tsx
- web/src/components/inputs/radio.tsx
- web/src/components/inputs/select.tsx
- web/src/components/modals/index.tsx
- web/src/components/panels/index.tsx
- web/src/domain/constants.ts
- web/src/forms/filters/FilterAddForm.tsx
- web/src/forms/settings/DownloadClientForms.tsx
- web/src/forms/settings/FeedForms.tsx
- web/src/forms/settings/IndexerForms.tsx
- web/src/forms/settings/IrcForms.tsx
- web/src/forms/settings/NotificationForms.tsx
- web/src/screens/Settings.tsx
- web/src/screens/filters/details.tsx
- web/src/screens/filters/list.tsx
- web/src/screens/settings/Action.tsx
- web/src/screens/settings/Application.tsx
- web/src/screens/settings/DownloadClient.tsx
- web/src/screens/settings/Feed.tsx
- web/src/screens/settings/Indexer.tsx
- web/src/screens/settings/Irc.tsx
- web/src/screens/settings/Notifications.tsx
- web/src/screens/settings/Releases.tsx
enhancement: simplified and improved radio switch group look
fix: fixed inconsistent spacing in input components (there's still some work left to be done)
fix: made slideover panel display on full width on mobile devices
enhancement: made forms more accessible to mobile users, adapter changes in accordance with the previous input components fix
fix: fixed misspelling in NotificationForms filename
chore: cleaned up code
fix: made filter table top edges less round and improved look
fix: fixed a bug where when a modal/slideover component was opened, a 1px white bar would be shown in one of the modal parent elements (for the fix see L89 in screens/settings/DownloadClient.tsx)
enhancement: improved responsiveness for irc network list
could probably use another round of testing both on …
> feat(web): mobile UI improvements

- internal/feed/torznab.go
The GUID is a download link but doesn't contain credentials.
Change `release.TorrentUrl` from `GUID` to `Link` from feed item.
> fix(feeds): torznab use link to download

- internal/indexer/definitions/torrentnetwork.yaml
Fixes category parsing of TN tracker.
Regex playground:
https://regex101.com/r/YfojxG/1
Fixes #368
> fix(indexers): tn fix category parsing

- internal/database/filter.go
- internal/domain/filter.go
- web/src/screens/filters/list.tsx
- web/src/types/Filter.d.ts
List number of actions on the filter list. As a visual marker if it's zero it will be red. Exposed in json as `actions_count`.
Return total and enabled count and make into a small badge like `[1/2]` or similar.
Fixes #366
> feat(filters): list actions count

- pkg/version/version.go
- pkg/version/version_test.go
On docker tags `develop` and `master` the version check would fail due to not being a valid semver tag and not getting properly checked.
For the future we might have to rework this to still be able to notify about updates on docker versions.
Probably by comparing latest commit to current commit.
> fix(server): exclude tags from version check

- internal/feed/service.go
- internal/scheduler/service.go
per https://github.com/autobrr/autobrr/issues/389 it seems to be a bit nutty right now where we're using cron fields to schedule work to be completed. This results not only in a thundering herd problem, but unexpected behaviour for people unfamiliar with the intricates of cron (and the specific flavour of implementation by the library owner).
This PR flips from fixed fields to use duration - it's completely untested and just from docs.
> fix(scheduler): use time as opposed to cron fields

- internal/indexer/definitions/immortalseed.yaml
Didn't support SSL/TLS, so set port to 6667 and no TLS.
> fix(indexers): immortalseed irc addr

- internal/indexer/definitions/ptm.yaml
`preGAP` is not always present in the feed for `pretome` so update the match regexp to make it optional.
> fix(indexers): fix ptm regexp to make preGAP optional

- pkg/ggn/ggn.go
Sometimes fields in the GamesInfo object was missing and since it's not used lets just remove it.
> fix(indexers): ggn fetch data from api

- pkg/lidarr/lidarr.go
Handle lidarr rejected as rejection instead of error.
Fixes #401
> fix(actions): lidarr properly handle rejected 

- internal/action/exec.go
- internal/action/run.go
- internal/domain/macros.go
- internal/domain/release.go
- internal/filter/service.go
shot in the dark implementation of TorrentDataRawBytes. The purpose behind this is to leave autobrr as the facilitator of providing valid data to actions. If the data isn't valid, the action shouldn't be run.
> feat(actions): implement TorrentDataRawBytes macro

- internal/notification/notifiarr.go
Check for non empty `API key` instead of `webhook`.
> fix(notifications): Notifiarr check for valid api key

- internal/action/rtorrent.go
Fix error with rtorrent when using save path. Change to `directory` instead of `base_path`.
Tested on `0.9.6`, `0.9.8` and working fine.
> fix(clients): rtorrent use `directory` instead of `base_path`

- web/src/screens/filters/list.tsx
- de-duplicate incompatible queries which led to a stale type-unsafe caching bug
> fix(web): indexer options stale caching

- internal/indexer/definitions/emp.yaml
Some releases wouldn't parse, and the culprit was the `lines` part where `pattern` was set as `- pattern` and that made the `lines` be split in two, even tho EMP is using single lines for announce and not multiple.
> fix(indexers): EMP parse line patterns

- .github/workflows/release.yml
- .goreleaser.yml
The docker builds with `goreleaser` lacked the possibility to only push images and not binaries at the same time. Ok for tags but not builds on PRs or `develop`.
> build: revert to old way of docker job

- internal/indexer/definitions/animebytes.yaml
Place the year inside square brackets before the release tags. This makes sure that the arrs don't think the release year is part of the title.
> feat(indexers): Improve arr compatability for animebytes

- internal/database/filter.go
- internal/database/release.go
This PR fixes the check for download per `HOUR` on SQLite.
The solution is quite obvious now, but wasn't at the time. `timestamp >= strftime('%Y-%m-%dT%H:00:00Z', datetime('now','localtime'))`.
That basically transforms the current time into a fixed format, and set's the current hour `%H` to the current hour from datetime, in local timezone, and then hardcodes minute and seconds to 00:00. So no more rolling hour, and there shouldn't be any bugs with it letting through more than set.
Day, week, month and total has been working fine all the time.
Fixes #467 #455
> fix(filters): max downloads per hour check

- web/src/components/data-table/Cells.tsx
- web/src/screens/filters/details.tsx
fix: fixed broken wrapping in tooltip child elements (missed last letter)
enhancement: increased line height for tooltip child cells in case of wrapping for clearer text
enhancement: renamed filter rejections from `Filter` to `Rejected` in tooltips
chore: changed remaining purple highlights to blue.
> fix(web): tooltips

- internal/indexer/definitions/immortalseed.yaml
fix(indexers): immortalseed regex
Fixed issue where the regex for matching the announce line from immortalseed only had 1 whitespace in front of "Link:"
but the announce line had 2 whitespaces in front of "Link:"
Added "\s+" (instead of " ") in front of "Link:" to match one or more whitespaces and simplified regex.
Other changes:
change IRC port to 7000
set TLS to true
replace "IRCKEY" in placeholder and help test with "PASSKEY" for invite_command field.
Tested with a sample size of 50 of which 50 matched. Before none of these announces matched.
Will report back again when i tested this regex with a bigger sample size.
> fix(indexers): immortalseed regex

- Dockerfile
- Dockerfile.ci
- cmd/autobrr/main.go
Presently we have code support for tz loading in golang, specifically for RSS feeds.
Golang has 3 lookup modes
* first using the ZONEINFO envvar
* second if golang is installed - loading $GOROOT/lib/time/zoneinfo.zip
* third using and embedded time/tzdata package
For full coverage across the three operating systems we support, embedding the zoneinfo into the application itself using the native package seems to be the "most portable" solution. Presently this works for binary installations of autobrr, because the system likely has zoneinfo already present. For containerized installations, there's no zoneinfo present, which results in the "max age" field in autobrr having unpredictable results.
> fix(cmd): add fallback tz information

- internal/indexer/definitions/gazellegames.yaml
[f96dd2d](https://github.com/autobrr/autobrr/pull/516/commits/f96dd2dffc9f4bb0788cdc27da34221f19674831)
Fixed regex to still match the announce if there are no flags in it.
Made the capture group 5 lazy/optional/ungreedy. 
[2aad404](https://github.com/autobrr/autobrr/pull/516/commits/2aad40415395dca3cad9e47464a6edc1b0b6b654)
Customized the regex to only match the word `FREELEECH` instead of `FREELEECH! ::`
[d832a4c](https://github.com/autobrr/autobrr/pull/516/commits/d832a4cdb95e21fb96b80d66bf991f7d6916c53b)
Fix match when there is no year given (instead of 0) for a release. 
Made capture group 4 lazy/optional/ungreedy.
Created a non-capturing group for the `:: NSFW! ::` section to exclude the seperators and the tag itself from the tags var.
I think we should exclude a possible `:: NSFW! …
> fix(indexers): GGn regex pattern

- web/src/components/data-table/Cells.tsx
- web/src/components/debug.tsx
- web/src/forms/settings/IrcForms.tsx
- web/src/screens/dashboard/ActivityTable.tsx
- web/src/screens/filters/details.tsx
- web/src/screens/settings/Application.tsx
- web/src/screens/settings/DownloadClient.tsx
- fixed table overflow in settings -> download client and also added truncation to the relevant text-based cell columns
- fixed uneven line height in the CellLine component (#520)
- in filter details renamed the "Cancel" button to "Reset form values"
- added log level and log path to application settings
- added additional alerts when one tries to use Match releases and Except releases (a very common issues)
> fix(web): download client table overflow, filter alerts, dubious wording

- web/src/App.tsx
- web/src/components/data-table/Cells.tsx
- infinitely retry web queries so we avoid the "failed to fetch" error when the web server is unavailable
- remove the "ago" suffix from age cells (closes #497)
> fix(web): infinitely retry queries, remove "ago" from age cells

- internal/database/feed.go
- internal/indexer/service.go
- web/src/forms/settings/IndexerForms.tsx
- web/src/types/Feed.d.ts
Presently to avoid duplicate identifiers, we don't store the implementation name in the database. However, as luck may have it, humans also use these names (and may for instance, want to name their feed `DistroWatch - RSS`). This adds a strange complexity to the issue, because if another feed was then named `DistroWatch - RSSRSS` you'd encounter a duplicate error. While the aforementioned isn't likely, it still results in a bad situation never the less. Torznab also does this, so this backs out the string replacement.
There's another issue present, where if the indexer ends with - the releases page doesn't have the trailing - which results in a query against a non-existent indexer, returning 0 rows. This was found working through bzwarts instance on 1.10.
> fix(feeds): indexer identifier issues

- .github/workflows/release.yml
The self-hosted runners are a bit buggy and sometimes hangs for hours and hours.
> build(ci): move back to hosted-runners

- web/src/components/modals/index.tsx
- web/src/screens/filters/details.tsx
Fixed an issue where the div containing the filter name in the delete modal would overflow if the filter name is too long.
Text inside the div is now contained and will word-break when too long.
Fixed an issue where the filter name headline would break into a second line if the filter name is too long.
In case the filter name is too long the filter name headline will now truncate and show it's full value at mouseover.
> fix(web/filters): truncate too long name

- web/src/screens/filters/action.tsx
When the first action is added to a filter, show it in edit mode for increased discoverability.
> feat(web): When adding the first action, display it in edit mode

- web/src/components/inputs/index.ts
- web/src/components/inputs/input_wide.tsx
- web/src/forms/settings/IrcForms.tsx
added red background to "Enabled" switch button when disabled for IRC update form
created const SwitchGroupWideRed in web/src/components/inputs/input_wide.tsx
added const SwitchGroupWideRed in web/src/components/inputs/index.ts
changed SwitchGroupWide to SwitchGroupWideRed in IrcNetworkUpdateForm in web/src/forms/settings/IrcForms.tsx
I only changed the switch of the IRC update form since this one seems to be the only on which gets overlooked sometimes.
Might also be because that is one of the switches that users need to click more regularly. Idk.
As always - if you don't like the change or this is not within our design policy feel free to close this PR. :)
> enhancement(web): red disabled switch button

- internal/database/release.go
This expands upon https://github.com/autobrr/autobrr/pull/302 by implementing keyword searching implementing a handful of what's immediately available. Multiple specifiers of the same type can be used, which does the right thing and implements an Or clause between them.
https://www.youtube.com/watch?v=MbXWrmQW-OE
- `title`
- `group`
- `category`
- `season`
- `episode`
- `year`
- `resolution`
- `source`
- `codec`
- `hdr`
- `filter`
In the search bar for releases do like `category:tv resolution:2160p`.
> feat(releases): implement keyword search

- internal/database/release.go
Presently we scan the entire DB on each line item returned by the database engine, in an effort to populate the single "total releases" counter on the bottom of the page. This results in a 47x slowdown on my system as the calculation is done for every line item returned. While it's more appropriate to break this out into another query entirely, changing the query to work on the static set of data in memory results in a massive speedup (47x on a classic SSD, much more on rotational systems).
EDIT: Removed one of the subqueries on stats, the speedup is only 40% (100ms savings), but I'm sure that's better than it was. Using Group By as opposed to renaming the fields like this is also faster, but would break the webui.
https://www.youtube.com/watch?v=yK0P1Bk8Cx4
> fix(releases): improve load time by 47x

- internal/indexer/definitions/torrentseeds.yaml
Adjusted our regex with capturing the ID after `/` instead of `id=`. 
Tested this the new expression with 1180 announces of which all resulted in a match.
EDIT:
Tested this PR with a snapshot build aswell. Successfully fetching files now again.
> fix(indexers): TS regex

- internal/indexer/definitions/alpharatio.yaml
- internal/indexer/definitions/torrentsyndikat.yaml
The indexer definition for AR resulted in `line not matching expected regex pattern` for all announces for unknown reason.
Recreated the regex to a similar but much more rudimentary fashion.
The indexer definition for TS (GER) resulted in `line not matching expected regex pattern` when there were no tags existing in the announce. 
AR is successfully tested in a live env and in regex101 with 1069 multi-line announces and
TS (GER) got successfully tested through mock with an announce previously resulting in an error.
> fix(indexers): fix AR and TS (GER) regex patterns

- web/src/screens/filters/action.tsx
- web/src/screens/filters/details.tsx
Added placeholders where there weren't any.
Some notable ones:
- Warn that label must exist in Deluge in order to work in `Deluge Label placeholder`.
- Higher number = higher prio in `Priority placeholder`.
- Emphasize that 0 is infinite in `Max downloads placeholder`.
- Emphasize the use of seconds in `Delay placeholder`.
> feat(web): added missing placeholders

- internal/indexer/definitions/ncore.yaml
Fixed the URL change initially made in the [baseurl override commit](https://github.com/autobrr/autobrr/commit/25a165b764ace7937ee8b0786ecd9bcd4b86a939#diff-8f417b2cd8914a5cdbdf14faaae4938e7f50de76992015ca2512204d3d0871a4)
An ncore user reported getting 404s after upgrading to v1.12.0
Untested, but should be good. The guy reporting it checked and confirmed that the URL is correct.
> fix(indexers): bad ncore torrent URL

- internal/database/action.go
- internal/database/api.go
- internal/database/database.go
- internal/database/download_client.go
- internal/database/feed.go
- internal/database/feed_cache.go
- internal/database/filter.go
- internal/database/indexer.go
- internal/database/irc.go
- internal/database/notification.go
- internal/database/release.go
- internal/database/user.go
SQLite defaults to sql.LevelSerializable, which takes a full atomic lock during the transaction. MSSQL defaults to sql.LevelReadCommitted, which seems like a reasonable compromise. Presently untested.
Documentation: https://www.sqlite.org/isolation.html
https://pkg.go.dev/database/sql#IsolationLevel
> refactor(database): clean-up queries

- internal/database/action.go
- internal/database/filter.go
- internal/database/release.go
So, as we're now painfully aware from https://github.com/autobrr/autobrr/pull/569 squirrel does not support subqueries as well as one would expect. There's some support, if you use an Alias on a column to provide a window, but this only supports params in either the window, another window, or a parent function, otherwise squirrel will misplace them. As squirrel is now in "maintenance" mode, I don't expect this situation to improve unfortunately.
So, lets revert this (hopefully) one regression.
> fix(database): fix filter regression from clean-up

- web/src/components/inputs/common.tsx
- web/src/components/inputs/input.tsx
- web/src/components/inputs/select.tsx
- web/src/screens/filters/details.tsx
Disable other fields visually when toggling **Perfect FLAC** for music. On the backend it does the same logic wise already.
* Set Log Score min 0 max 100
* Disable other music quality fields
* Also a fix for priority default to 0
The styling for the multi select fields could be improved with a gray bg, but that requires some css.
Fixes #576
> feat(filters): perfect flac disable fields

- web/src/components/inputs/input.tsx
Unable to adjust priority within filters with the following code present, so removed it for now.
```js
onChange={event => {
// safeguard and validation if user removes the number
// it will then set 0 by default. Formik can't handle this properly
if (event.target.value == "") {
form.setFieldValue(field.name, 0);
return;
}
form.setFieldValue(field.name, event.target.value);
}}
/>
{meta.touched && meta.error && (
<div className="error">{meta.error}</div>
)}
```
> fix(web) reversed onChange for priority numberfield

- web/src/components/inputs/common.tsx
Disabled checkboxes in dark mode are now the same color as disabled NumberFields in dark mode.
> enhancement(web): gray color for disabled checkboxes in dark mode

- README.md
ref: https://github.com/badges/shields/issues/8671
This PR fixes the build shield for the autobrr readme.md
In contrast to what is stated in the ref issue we do not need the subdirectory integrated in the URL,
even though our release.yml is in the workflows subdir.
> docs: build shield

- internal/indexer/definitions/subsplease.yaml
This PR fixes the 404 HTTP Error for SubsPlease, since the baseURL was wrong.
> fix(indexers): subsplease baseurl

- internal/indexer/definitions/subsplease.yaml
A user on discord found an issue with the SubsPlease regex not matching batches.
To fix the issue the releaseTags capture group is now optional.
Making the releaseTags group optional proposed another issue,
where the torrentName capture group would consume the content of the releaseTags group aswell.
This got fixed by setting the quantifier of the torrentName capture group lazy/ungreedy.
After setting this quantifier lazy/ungreedy the torrentName capture group got ended early by the torrentSize capture group.
That issue got fixed by creating a more specific regex for the torrentSize group.
Additionally I decided to move the releaseTags capture group out of the torrentName group in order to create more exact matches from the names of nyaa and the SubsPlease site itself.
Unfortunately i …
> fix(indexers): subsplease regex

- internal/indexer/definitions/skipthecommericals.yaml
Add STC.
Playground: https://regex101.com/r/wP53rX/2
Ref #1.
> feat(indexers): add SkipTheCommericals

- web/src/screens/Base.tsx
- web/src/screens/filters/details.tsx
- web/src/screens/settings/Api.tsx
- web/src/screens/settings/DownloadClient.tsx
- web/src/screens/settings/Feed.tsx
- web/src/screens/settings/Indexer.tsx
- web/src/screens/settings/Irc.tsx
- web/src/screens/settings/Notifications.tsx
- web/src/screens/settings/Releases.tsx
Minor visual changes and some UI bug fixes.
- Fixed Notifcations table under Settings/Notifcations to look good on narrow screens (See images)
- Changed icons for Docs and User
- Changed the Feeds paragraph to include regular RSS feeds
- Centered "Danger Zone" header on Settings/Releases
- Added paragraph below "Danger Zone" header on Settings/Releases 
- Added punctuations to subtitles and sublabels that were missing them in Filters
- Removed some subtitles over "Create new" buttons in Settings and improved button texts.
**Old:**
**New:**
**Old narrow:**
**New narrow**
**Old wide**
**New wide**
> feat(web): settings cosmetic improvements

- internal/action/lidarr.go
- internal/domain/filter.go
- internal/indexer/definitions/orpheus.yaml
- internal/indexer/definitions/red.yaml
This PR should improve the artist parsing for RED and OPS.
From `Artist - Album name` to now catch the whole `Artist - Albumname [2008] [Single] - FLAC / Lossless / Log / 100% / Cue / CD`. This should properly parse artist and album name. The other values were working good already.
And with this change we remove the workaround for Lidarr where we added year to the basic release name.
> feat(indexers): improve RED and OPS artist parsing

- internal/action/qbittorrent.go
- internal/domain/client.go
- web/src/forms/settings/DownloadClientForms.tsx
- web/src/types/Download.d.ts
Add new rule check for qBittorrent to check if the total transfer speed is below set threshold.
It works the same way as the Download Speed Threshold but upload instead.
Example: Upload speed threshhold set to 90000 (90MB/s)
If total transfer speed of client is less than 90000 it will add a new torrent if "ignore slow torrents" is enabled in the download client settings in autobrr.
If it's above 90000 then it will reject and skip adding.
Resolves #574
> feat(downloadclients): qBit add rule UploadSpeedThreshold

- internal/indexer/definitions/ant.yaml
Authkey is not required or used anymore so lets remove it.
> chore(indexers): remove authkey from ANT

- web/src/screens/Base.tsx
- web/src/screens/dashboard/Stats.tsx
Having the top left logo link to the front page is something you see on a lot of web pages. It's something you don't think about, because it's always like that. I've clicked that logo so many times expecting it to redirect me to the Dashboard that I've lost count.
The Stats header was a h3 tag. It is now an h1 tag with the same styling as the other h1 headers on other pages.
[Header change demonstration.](https://i.imgur.com/kwL0HoI.mp4)
> enhancement(web): autobrr logo link to dashboard

- web/src/screens/filters/details.tsx
Music type don't disable when perfect flac is selected.
> fix(filters): music type don't disable when perfect flac is selected

- internal/indexer/definitions/animebytes.yaml
Fixes #653 
Regex will now successfully capture the release group for translated printed media.
Additionally you can now filter for Sub type in the releaseTags!
Fixed an edge case where miscapturing occurred when the torrentName contained the string `TV`
Disclaimer: To achieve this the Release group is now part of the releaseTags var which might lead to misparsed tags.
I have not run tests against this.
There is also the possibility of unwanted behaviour when using the `MATCH RELEASE TAGS` field under `Advanced` in autobrr.
But since we have the warning banner for releaseTags filtering i feel like this is justified.
In case you have any other concerns about this change feel free to point them out! :)
https://regex101.com/r/zmgPQu/4
> fix(indexers): animebytes regex

- internal/indexer/definitions/fuzer.yaml
- internal/indexer/definitions/hebits.yaml
- internal/indexer/definitions/iplay.yaml
- internal/indexer/definitions/ncore.yaml
- internal/indexer/definitions/retroflix.yaml
- internal/indexer/definitions/speedapp.yaml
- internal/indexer/definitions/torrentbytes.yaml
New: https://regex101.com/r/YxtVT7/1
Old: https://regex101.com/r/pmyFOX/1
Removed `name1` var and capture group.
New: https://regex101.com/r/AuJPRg/1
Old: https://regex101.com/r/66kpcT/1
Removed `name1` var and capture group.
New: https://regex101.com/r/9Qpe6k/1
Old: https://regex101.com/r/kLzNrI/1
Case sensitive start made it fail everything(?)
New: https://regex101.com/r/hTkcT8/1
Old: https://regex101.com/r/Pj0y6X/1
Bad baseurl capture.
New: https://regex101.com/r/qIS6i5/1
Old: https://regex101.com/r/WY5qPu/1
Removed [REQUESTED] from torrentName capture.
New: https://regex101.com/r/Fzv6Cq/1
Old: https://regex101.com/r/1v0T3j/1
Removed unused capture group.
New: https://regex101.com/r/ozIu3F/1
Old: https://regex101.com/r/n5iJr6/1
Bad baseurl capture.
> fix(indexers): multiple definition regex pattern corrections

- web/src/screens/Base.tsx
- web/src/screens/filters/list.tsx
I know this isn't what you ultimately want[^1], but I think it's a massive improvement to the current version. Even if it's just temporary.
This does not change how it looks on a regular computer screen except for 1p of vertical padding on the rows.
Demo of how it changes from wide to narrow: https://i.imgur.com/c02tqNo.mp4
[^1]: I won't get hurt if this gets yeeted 😉
> enhancement(web): filters list mobile friendly

- web/src/screens/filters/list.tsx
changed the resolution response from sm (640px) to md (768px) for the indexer column
compacted the filter lines while maintaining the padding to the border when a filter name spans over multiple lines 
span the filter name over the full width until the next div 
fixed a duplicate display property
adjusted the width of the indexer and sort listbox for show the full values. (widths for both are uniform) 
adjusted padding of indexer listbox entries
> fix(web): filters list desktop and mobile friendly

- web/src/screens/filters/details.tsx
Make it abundantly clear that the advanced uploader filters are comma separated.
> docs(filters): update placeholders for advanced filters

- internal/domain/release.go
Presently Audio, Codec, and Other can contain duplicate information if it's present in the announced tags. This results in a not great situation where we're not only storing duplicate information, but filtering on it as well.
> fix(releases): check for duplicate tags

- web/src/screens/filters/details.tsx
https://github.com/autobrr/autobrr/pull/605/files#diff-3e21b97dc9b916aed60fb39277bef67216f3746fa5c541dbbcc3c8096360a367L349
breaks the priority field when users decided to use negative values for priorities.
This PR reverts the `min={0}` attribute for the priority NumberField.
> fix(filters): allow negative priority again

- web/src/screens/filters/details.tsx
This should hopefully help avoid confusion on the users part since toggling the switch locks freeleech percent to 100. Seen it happen a few times where they enter 50-100 and then toggles the switch.
> enhancement(web): disable freeleech percent field if freeleech is enabled

- internal/domain/release.go
- internal/feed/rss.go
When some RSS feeds have `Enclosure->Length` fixed size, autobrr fails to retrieve the size that's included in `Custom->Size`.
The previous logic used `custom->size` when `enclosure->length` was 0. But as stated in a previous issue, this `enclosure->length` can be a fixed length unrelated to the torrent. Therefore this value can be 0, fixed length, or the real one.
This modification will pick `custom->size` whenever is defined and it's bigger than `enclosures->length`.
https://github.com/autobrr/autobrr/issues/636
> fix(feeds): RSS improve torrent size parsing

- internal/indexer/definitions/skipthetrailers.yaml
Fix clashing identifier of stt to not use stc.
> fix(indexers): SkipTheTrailers identifier

- internal/indexer/definitions/torrentbytes.yaml
TorrentBytes tracker have broken SSL so until they fix it lets change to download of .torrent with just http trackers.
> fix(indexers): TorrentBytes broken tracker use non-SSL link

- internal/database/postgres.go
- internal/database/sqlite.go
Presently when a schema migration happens, nothing is printed until the migration completes (the application has no output until then). This is ok for a computer, however humans can get quite anxious seeing an application appear to hang for seconds, to minutes, to tens of minutes on startup. These printouts are in an effort to help reduce that anxious moment, and let the end-user know that the application is doing good work for them.
> enhancement(database): improve log messages

- web/src/screens/auth/login.tsx
- web/src/screens/auth/onboarding.tsx
- web/src/screens/filters/action.tsx
**Improvements**:
- Added a "forgot password?" tooltip and a autobrr header on the login page.
- Added autobrr logo and header on the onboarding page.
**Bug fix**:
The link in this tooltip is broken when running autobrr in a subfolder:
https://github.com/autobrr/autobrr/blob/d52b28d05f2a4ae147a9c2f51811e6df45bb327d/web/src/screens/filters/action.tsx#L239
This PR fixes that by replacing the `<a>` tag with a React link.
Just cleaning up my own mess here, sorry.
> enhancement(web): login and onboarding work

- web/src/components/tooltips/CustomTooltip.tsx
- web/src/domain/routes.tsx
- web/src/screens/Base.tsx
- web/src/screens/auth/login.tsx
- web/src/screens/filters/details.tsx
Ref proposals in #707 
- Reduced contrast on the tooltip icon. It should now be identical to description and subtitle texts in both dark mode and light mode.
- Reverted the Docs icon to the old one
- Fixed Freeleech tooltip text
Proposed change:
> enhancement(web): reduce tooltip icon contrast

- web/src/screens/Logs.tsx
Right now you can't download logs if you're on a subfolder reverse proxy setup. It only works on `/`.
Reason: the Link component does not require `${baseUrl()}`.
> fix(web): fixed baseurl for log downloads

- web/src/screens/Logs.tsx
It now stays within the Logs window when scrolling. Tested on Firefox only.
https://i.imgur.com/VKVW6GW.mp4
Removed unused var (baseUrl)
> fix(web): Logs page scroll to bottom

- web/src/screens/filters/details.tsx
Reverted locking mechanism for the Freeleech toggle as it doesn't set `freeleechPercent` to 100 when doing so.
> fix(web): reverted freeleech lock mechanism

- internal/domain/macros.go
- internal/domain/macros_test.go
Adds [sprig functions](http://masterminds.github.io/sprig/) to Macros.
Fixes #732
> feat(macros): add sprig functions to macros

- .dockerignore
- .github/workflows/release.yml
- Dockerfile
- ci.Dockerfile
- go.mod
https://go.dev/blog/go1.20
`
The new function [errors.Join](https://go.dev/pkg/errors#Join) returns an error wrapping a list of errors which may be obtained again if the error type implements the Unwrap() []error method.
`
`When [building a Go release from source](https://go.dev/doc/install/source), Go 1.20 requires a Go 1.17.13 or newer release. In the future, we plan to move the bootstrap toolchain forward approximately once a year. Also, starting with Go 1.21, some older operating systems will no longer be supported: this includes Windows 7, 8, Server 2008 and Server 2012, macOS 10.13 High Sierra, and 10.14 Mojave. On the other hand, Go 1.20 adds experimental support for FreeBSD on RISC-V.`
> chore(deps): update Go to 1.20

- internal/indexer/definitions/ncore.yaml
nCore IRC has moved to `irc.p2p-network.net`, and their announce channel no longer requires an invitation. This was reported by qmayer in #dev-general yesterday, and I have confirmed it through TheLounge.
I left the invite part commented out instead of removing it, as it is uncertain whether they will re-implement it at some point.
> fix(indexers): ncore irc server change

- internal/domain/filter.go
- internal/domain/filter_test.go
An update in the `rls` parsing library broke the previous implementation.
The matching for HDR now checks if there's a space in the filter, like `dv hdr` and then does extra checks to make sure all parts exists in the release.
> fix(filters): match `dv hdr`

- internal/domain/release_test.go
- internal/domain/releasetags.go
- internal/domain/releasetags_test.go
Added negation to the Lossless regex to prevent it from matching 24bit Lossless. This should fix #703
> fix(tags): `24bit Lossless` being tagged as `Lossless`

- web/src/forms/settings/DownloadClientForms.tsx
Connection fails for ip:port
Updated help text with these examples:`http://ip:port` and `https://url.com/sabnzbd`
> enhancement(web): emphasize the need for HTTP in SABnzbd host URL

- cmd/autobrrctl/main.go
`autobrrctl version` is contacting Github directly right now. Using brr-api makes more sense.
Added some error handling after recommendations from Kyle.
> fix(autobrrctl): use brr-api instead of github directly for version check

- web/src/api/APIClient.ts
- web/src/forms/filters/FilterAddForm.tsx
i'm not certain if there is an explict reason for the current behavior, but personally I always want to edit a filter immediately after creation.
i can adjust the commit message if needed, i wasn't sure if this was a fix or a feature /shrug
> feat(filters): navigate to edit page on filter creation

- web/src/screens/filters/action.tsx
Switched to the TextArea component for the webhook data input field as it makes more sense than using TextField in this case.
> feat(filters): use TextArea for webhook data field

- internal/config/config.go
Windows uses backslashes `\` which doesn't work instead they should use forwardslashes `/` for the logPath .
To help clarify this issue and assist users in understanding how to properly set the logPath I have added example and warning.
> enhancement(config): clarify logPath usage

- internal/action/rtorrent.go
- web/src/screens/filters/action.tsx
Someone in the discord asked for it* so here it is
*they said paused, but you can't do that on rtorrent from my understanding so i went with stopped
this matches the option in rutorrent's add dialog
> feat(actions): add "don't start" option for rtorrent

- web/src/screens/filters/list.tsx
- web/src/utils/Context.ts
Store the user's chosen sortOrder in the browser's localStorage to maintain their sorting preference even when the page is refreshed. Previously, the sortOrder would reset upon refreshing the Filters page.
> feat(web): preserve sort order on Filters list

- web/src/screens/filters/list.tsx
The Clipboard API requires HTTPS, so we need to add a fallback for HTTP. Using the old execCommand('copy') method.
EDIT: Tested and confirmed by user who reported it.
> fix(filters): add fallback for clipboard api on http

- internal/http/logs.go
- internal/http/logs_sanitize_test.go
Closes #799 
This PR sanitizes the data from the `host`, `user` and `password` fields for `"level":"info","module":"action"` log entries when downloading the logs via the webinterface.
Additionally it also sanitizes the `ExternalWebhookHost` field.
Huge thank you to @s0up4200 for helping me get my troubles out of the way! 😄
> feat(logs): webhook sanitization

- web/src/components/inputs/input.tsx
- web/src/components/tooltips/CustomTooltip.tsx
This PR addresses the issue where the fields in the RegexField component were only validated when they were touched.
Also made sure the red border disappears if `useRegex` is false without being touched.
Demonstration: https://cln.sh/C8rqH56D
Improved regex validation. Returning false for known cases that is unsupported by Go. Playground test: https://go.dev/play/p/F0aFh2fPGYz
Thanks to @martylukyy and @nuxencs for assisting with the regex improvements.
Also corrected nasty z-index on tooltips. Its needed in the RegexField, but not the others.
> feat(filters): improve RegexField validation

- web/src/components/inputs/input.tsx
- web/src/components/inputs/input_wide.tsx
This PR addresses the issue where number input fields were changing their values when using the scroll wheel. The desired behavior is to prevent the scroll wheel from changing the input values while still allowing the page to scroll if field is selected.
~~Currently only tested in Firefox.~~
> fix(web): numberfield changing while scrolling

- web/src/components/inputs/input.tsx
Added a conditional pr-10 if useRegex=true to make the right side of the field remain visible when the icons are present.
> fix(web): RegexField add padding

- internal/database/filter.go
- internal/database/postgres_migrate.go
- internal/database/sqlite_migrate.go
- internal/domain/filter.go
- internal/domain/filter_test.go
- web/src/components/inputs/select.tsx
- web/src/domain/constants.ts
- web/src/screens/filters/details.tsx
- web/src/types/Filter.d.ts
Added logic to support any/all matching logic for tags and except tags.
I found some unused fields in the `Filter` struct (`TagsAny`, `ExceptTagsAny`) that seemed like a way to start implementing this, but are not used anywhere. I kept them there for now.
Until now tag evaluation was always evaluated using `any` from what I could tell. Created new fields to store the logic to be used. In the DB migrations I updated the values of these to "any", not sure if that's the correct way to go about it
> feat(filters): add match logic for tags and except tags

- web/src/components/inputs/input_wide.tsx
- web/src/forms/settings/IndexerForms.tsx
An attempt to disable autocomplete in text fields for Add Indexer.
1Password does not seem to respect this and decides itself what to do, but it's something.
Closes #750
> fix(settings): indexer forms disable autocomplete in TexField

- web/src/screens/filters/details.tsx
Should have been done here probably: #719
Removed the description text completely and updated the tooltips with a description as well as linking to the appropriate page in the docs.
> fix(web): explanation of freeleech options

- internal/indexer/definitions/tokyotoshokan.yaml
Add support for Tokyo Toshokan indexer.
Closes https://github.com/autobrr/autobrr/issues/501
The only caveat is that this definition uses their main `#tokyotosho` channel on IRC instead of the `#tokyotosho-api` channel as specified in the issue (https://github.com/autobrr/autobrr/issues/501). This is because of the way they delimit their messages and is therefore not possible to use at the moment, as described in this related issue: https://github.com/autobrr/autobrr/issues/817.
> feat(indexers): add Tokyo Toshokan

- web/src/screens/Logs.tsx
Closes #835 
Log download button now shows on screen with less than 640px width.
Switched places of `Last modified` and `Size` column.
Decided to hide the file name when browsing the log download section to fit one entry in a single line. (responsive only)
The reason why I decided on this element to be hidden is the fact that the file name starting with `autobrr-`
takes up a lot of valuable space for narrower screens.
We could also make each log file a double line and keep the file name.
Comment in case the latter would be preferred.
> fix(web): make log files section responsive

- internal/notification/service.go
If the agent variable is nil (This can happen if the `notification.Type` doesn't match any of the cases in the switch statement.) the server will crash.
On the frontend  when user test the notification without providing the type it will crash. Maybe we need to change the frontend as well, to make sure that the test button is disabled unless all the required field is filled, but this change at least will prevent the server from crashing.
> fix(notifications): test handle unsupported type

- web/src/components/alerts/NotFound.tsx
- web/src/domain/routes.tsx
This PR implements a not found page when the user is logged in.
When the user is not logged in we already have a * directive which redirects to the login page.
> feat(web): add not found page

- web/src/components/Icons.tsx
- web/src/screens/Logs.tsx
replace loading dots with spinner icon and move text to title for it display at mouseover.
EDIT: This PR is tested in a dev environment and on my dedi with a reverse proxy. 
(Client: Chrome  112.0.5615.87 on Windows 11 Pro 22H2 Build 22621.1555)
In contrary to the solution with CSS, this one is CORS save since it is a animated SVG using SMIL.
https://user-images.githubusercontent.com/35452459/232457839-6fa32ee4-e2ef-45b8-ae68-8224794939a3.mp4
> enhancement(web): log download spinner icon

- internal/indexer/definitions/torrentnetwork.yaml
Fixes #878 
There was a misspelling in the TorrentNetwork definition which caused an error due for not finding the field required.
Will pull this on prod and report back if the fix has been successful.
> fix(indexers): TorrentNetwork settings crash

- internal/database/action.go
- internal/database/download_client.go
- internal/domain/action.go
Properly remove from filter actions on delete.
The best solution would have been to use SQL foreign key constraints, but that might have unintended consequences for users who have been running autobrr for a long time.
Fixes #856
> fix(downloadclients): remove from filter actions on delete

- internal/config/config.go
The current method to detect lxc and start the config file with host 0.0.0.0 does not work because linux kernel have moved to namespaces and also only root have permissions to access some proc files.
I have checked within all my containers and also with a friend that runs lxc on a different plataform, both of us have this file with same permissions 444.
I also have checked against [lxc source code](https://github.com/lxc/lxc/blob/master/src/lxc/conf.c#L4024).
I would assume its safe to assume this file should exists on every boot.
> fix(config): lxc container detection

- internal/database/filter.go
Include release actions in status `pending` in check for max downloads with Postgres.
SQLite already does this, only Postgres affected.
> fix(filters): max downloads include pending with postgres

- internal/action/run.go
- internal/domain/release.go
Fixes and error where non download client based actions would fail because of a recent change from a non nil value to action.Client now being nillable.
> fix(actions): handle non download client actions

- internal/indexer/definitions/xspeeds.yaml
https://regex101.com/r/29qG0d/1
It fails to match `Category: ( TOTW (x2 upload)` in its current state.
> fix(indexers): xspeeds regex pattern for categories

- README.md
https://saltbox.dev/ gives 404, even https://github.com/saltyorg/Saltbox about section links to https://docs.saltbox.dev/
> docs: update Saltbox link

- web/src/screens/filters/list.tsx
Exclude `tags_match_logic` and `except_tags_match_logic` on filter export if default values.
```ts
if (["tags_match_logic", "except_tags_match_logic"].includes(key) && value === "ANY") {
delete completeFilter[key as keyof CompleteFilterType];
}
```
**EDIT:** Further testing indicates that its only added to the export if the user has interacted with that field.
Like setting it to `all`, save, then setting it back to `any` again. 
I still think we should remove it if set to `any` as its the default anyway. There is no need to export default values.
But that explains why some exports has it while others don't.
> enhancement(filters): exclude `tags_match_logic` on export if default value

- web/src/screens/filters/list.tsx
The messages were reversed – it would say "enabled" when the filter was actually disabled, and vice versa.
Let me know if there is a better solution!
> fix(filters): correct toasts for enabling and disabling filters

- web/src/api/APIClient.ts
- web/src/screens/releases/ReleaseTable.tsx
Add torrent download link to Release Table. A good interim solution until a more proper function is implemented.
By using an extension like [Torrent Control](https://addons.mozilla.org/en-GB/firefox/addon/torrent-control/), users can easily add torrents to their client if they were rejected or for any other reason. This can be done by simply right-clicking the torrent link and selecting the option to add it to their client.
> feat(release): add torrent download link to release table

- internal/feed/rss.go
Do not cache items on initial run for RSS feeds.
Neither Torznab or Newznab does this and allows items to be processed from the start.
This supersede #885
> fix(feeds): process RSS on initial run

- web/src/components/inputs/input.tsx
This PR limits the maximum height of the new automagically resizing textareas to 10 rows,
while still giving the user the option to drag them bigger manually.
I "hardcoded" all the fields to have a maximum height of 10 rows.
We could also choose the maximum height for each field but it feels like a nuisance to me..
> fix(filters): limit textarea height

- web/src/screens/Logs.tsx
Search is now case insensitive and way more flexible thanks to regex.
Searches like `this show`, `ThIs ShOw`, `s[0-9]{2}e[0-9]{2}.*(1080p|720p)` or `The.Company.*(1080p|720p).*-GRP` now works.
Show a red icon if pattern is invalid:
> feat(logs): improve log search with regex

- config.toml
- internal/config/config.go
Fixes an issue where the config would try merge with env vars in k8s environments.
> fix(config): env var prefix clashing in k8s

- internal/filter/service.go
This fixes the issue with actions missing from duplicated filters.
With the recent change introduced in https://github.com/autobrr/autobrr/pull/932 we do not longer remove all the actions before saving them again. Instead we check if `id > 0` to update existing actions, and if `id == 0` then we store a new action.
By resetting each `action.ID` to 0 in the **duplicate** method it will now treat that as a new action on the new filter, and thus store it and give it an ID.
Fixes #938
> fix(filters): duplicate missing actions

- cmd/autobrr/main.go
- go.mod
- go.sum
- internal/database/irc.go
- internal/domain/irc.go
- internal/http/irc.go
- internal/http/server.go
- internal/irc/handler.go
- internal/irc/service.go
- test/mockindexer/irc/handlers.go
- web/src/api/APIClient.ts
- web/src/screens/settings/Irc.tsx
- web/src/types/Irc.d.ts
- web/src/utils/Context.ts
View messages/announces per channel of IRC networks.
With the improved functionality in the Server Sent Events library we can now store events from channels and replay those easily. The current number is set to replay 1000 messages when opening the channel log. This might be too many messages but they are streamed and not a giant blob. We can always reduce this in the future.
Expanded
Fixes #826
> feat(irc): view announces per channel

- internal/http/server.go
Protect against Slowloris attacks.
> Configuring ReadHeaderTimeout would protect directly against this attack by closing the connection once the deadline is reached. By default, Go does not define any value — meaning there is no timeout.
> fix(http): set ReadHeaderTimeout to mitigate Slowloris

- .github/workflows/release.yml
- Dockerfile
- Makefile
- web/package.json
[Corepack](https://nodejs.org/api/corepack.html) is enable since node v14, it has the package manager built-in and we can just use it.
When using corepack it will respect the version at package.json but it needs to be locked version.
I also think its nice to lock node-version on the github actions to the same as the docker image is using.
I have not tested the github actions changes, just Google and it seems to work, but we need to run to test it.
For Dockerfile I have tested and it works fine:
> build(web): use pnpm from corepack

- Dockerfile
- ci.Dockerfile
Something on my editor have removed the `\`...
Tried to build it today and it broken
> fix(build): missing concat EOL on Dockerfile

- .github/workflows/release.yml
- .goreleaser.yml
So... goreleaser does not allow opensource users to use GGOOS (which lets you filter the goreleaser file) so matrix builds are possible but it's constructing the file each time (not a problem, just work).
The linux nodes on GHA only have a single CPU which is fine, but takes a lot of time with cross-compilation. MacOS and Windows still run on (or close to) metal. Windows with setup-go from years ago still suffers from zstd compression times (taking 4 minutes), with a pretty beefy node. MacOS runs in a similar fashion, but uses gzip which decompresses faster (3 minutes) to be exact.
As these are both faster than linux... lets change nodes until such a time that this no longer makes sense, or there's an easier way.
> build: goreleaser parallel builds

- internal/indexer/definitions/torrentseeds.yaml
This PR adds freeleech to the regex and the vars for new TS announce format.
Since there is no seperator between the username and freeleech,
i had to get a bit creative and need to change the group for the uploader var to `\w` which is the character class `[a-zA-Z0-9_]`.
Hope this doesn't come back to get us, but i didn't see usernames with any other characters upon a quick look.
https://regex101.com/r/Y3n2Vu/1
> feat(indexers): add freeleech support for TS

- internal/action/porla.go
- pkg/porla/client.go
- pkg/porla/domain.go
- web/src/screens/filters/action.tsx
Some improvements to the Porla integration,
- Omit download and upload limits completely if they're set to 0.
- Prefix JWT with `Bearer ` if not already specified.
- Allow setting a preset.
Re: the preset changes - I'm reusing the label field from other clients since we don't have that concept in Porla and it seemed easier than introducing a whole new field. Lemme know if this was bad 😃
Also, I'm not sure of the idiomatic Golang way of handling pointers when I want nil, specifically the download and upload limits. If there's a better way, I'm all for it.
> feat(downloadclients): Porla support preset

- internal/database/irc.go
- internal/database/postgres_migrate.go
- internal/database/sqlite_migrate.go
- internal/domain/irc.go
- internal/irc/handler.go
- internal/irc/service.go
- web/src/forms/settings/IrcForms.tsx
- web/src/types/Irc.d.ts
Add initial bouncer support for IRC. Only tested with ZNC so far, which is the most popular IRC bouncer.
In the IRC settings for the network there's now a toggle **Bouncer (BNC)**. Toggle that and you'll get a new field below, **Bouncer address** which takes the addr to your bouncer.
Then set the password to your users password for the bouncer and Account to your `user/network` configured by the bouncer. Leave channels as is.
Fixes #488
> feat(irc): add bouncer/znc support

- internal/irc/handler.go
- internal/irc/service.go
- web/src/screens/settings/Irc.tsx
Fixes an issue with some IRC channels not showing any messages.
Not sure exactly why this was, but making the SSE stream key a base64 encoded string fixed it.
Fixes #985
> fix(irc): view channel history

- internal/irc/service.go
- web/src/screens/settings/Irc.tsx
Apply RFC4648 to base64 sseKey to fix urlEncoding of SSE stream key.
> fix(irc): urlencode SSEKey for SSE streams

- internal/domain/filter.go
If user sets a min or max size without specifying a unit, the rejection returns blank
> feat(filter): add rejection on invalid size set

- web/.eslintrc.js
- web/src/screens/settings/Application.tsx
- web/src/screens/settings/Feed.tsx
- web/src/screens/settings/Irc.tsx
I know we dont need to be crazy about linting rules... but...
The idea is to allow the use of `_` or `_myVariable` when you **really** need an unused variable (like for skip a paramether) this way eslint wont complaing to you
There are more files to be updated but those files is being touched in another MR so I prefer to leave out for now avoiding possible conflict.
> chore(web): add ignore pattern to eslint for the unused-vars rule

- web/src/screens/settings/Irc.tsx
This PR fixes the View button on the IRC settings page sticking out to the right if the viewport is too narrow.
Old:
New:
> fix(web): view button alignment in irc settings

- web/index.html
- web/src/utils/Context.ts
It have been report on #1016 that firefox is flashing on dark theme.
This happens because the whole js is needed to set the user theme and Firefox likes to play as faster guy so the css renders first with default styles.
My idea was to quickly read the user theme and apply, setting the dark class ready there for the styles.
We know that is dangerous to use `JSON.parse` without try catch because it throws exception and stop execution, but I also notice theres not many places doing try/catch for the localStorage values as well.
> fix(web): set theme before app loads

- internal/database/download_client.go
Fixes an issue where deleting clients not connected to actions would give an error.
Fixes #1007
> fix(downloadclient): could not delete

- internal/database/postgres_migrate.go
Fixes an issue where filters (with downloads) could not be deleted because of foreign key constraints.
Fixes #973
> fix(filters): could not delete with postgres

- internal/database/postgres_migrate.go
Different naming of foreign key constraints led to failing migrations.
This adds `IF EXISTS` check and the other naming variant which should fix the issue.
Reporters @jpalenz77 and @BaukeZwart
> fix(releases): bad postgres fk migration

- internal/indexer/definitions/sharewood.yaml
Sharewood URL has been changed recently. This updates the IRC URL for newly created connections
> fix(indexers): IRC URL for Sharewood

- internal/database/action.go
- internal/database/release.go
This pr fixes issues from action/release replay with missing data for qBit `ContentLayout` and missing release `torrentId`.
Fixes #1048 , fixes #1037
> fix(actions): missing data on retry

- internal/filter/service.go
Replace newline of `shows` with comma.
Fixes #1019
> fix(filters): replace newline with comma

- internal/indexer/definitions/morethantv.yaml
They changed something in their announce regarding tags. This fixes that thanks to @martylukyy 
New: https://regex101.com/r/F565KE/1
Old: https://regex101.com/r/dll2hL/1
> fix(indexers): MTV announce regex pattern

- internal/indexer/definitions/alpharatio.yaml
AR got rid of NickServ completely on their IRC, but we still have NickServ as a requirement for them.
I would propose to get rid of the NickServ fields completely to avoid complications.
> fix(indexers): remove nickserv options for AlphaRatio

- Dockerfile
- web/package.json
- web/pnpm-lock.yaml
- web/postcss.config.js
The idea is that we improve the Docker cache layers on the web-builder.
If theres no changes on package.json or pnpm-lock, we dont need to run the install command.
This is the similar that we already have implemented on the app-builder stage.
> build(docker): improve cache on web-builder stage

- web/src/screens/Logs.tsx
This PR fixes the autoscrolling issues we had on the Logs page.
I noticed when settings.scrollOnNewLog gets changed it loads the entire map again..
To circumvent duplicate entries it will now clear the div once, resulting in resetting the position to the top of the div or respectively the bottom of the div depending on the value of settings.scrollOnNewLog .
If someone has a better way of handling this please ping me on discord or comment here.
> fix(web): autoscrolling for Logs page

- web/src/components/Checkbox.tsx
- web/src/screens/settings/Irc.tsx
This PR now implements auto scrolling for IRC logs.
Sorting is now newest at the bottom again and you start out scrolled all the way down when the setting is activated.
Additionally I added the timestamp to the logs because in one case I wanted to see the timestamps at a glance instead of moving the mouse over the different entries.
I am not too worried about it there being to much information in for a single entry since we have the fullscreen view too.
Also, I added some margin to the show/hide button because it looked crowded.
I noticed when `settings.scrollOnNewLog` gets changed it loads the entire map again..
To circumvent duplicate entries it will now clear the div once, resulting in resetting the position to the top of the div or respectively the bottom of the div depending on the …
> enhancement(web): IRC logs view

- internal/database/feed_cache.go
- internal/database/postgres_migrate.go
- internal/database/sqlite_migrate.go
- internal/domain/feed.go
- internal/feed/cleanup.go
- internal/feed/newznab.go
- internal/feed/rss.go
- internal/feed/service.go
- internal/feed/torznab.go
- internal/indexer/service.go
- internal/scheduler/service.go
Add daily scheduled cleanup job for feed cache. Cleans cache older than 30 days.
This PR also changes:
* The feed cache from a generic "bucket" style KV store to using foreign keys connected to `feed.id`
* Refactor of feed jobs and their identifiers for better control
Fixes #1055
> feat(feeds): add scheduled cleanup

- .github/dependabot.yml
Way too much churn in golang and npm unfortunately. Turning this down for the health of the project until such a time that dependabot is ready.
https://github.com/dependabot/dependabot-core/issues/2264
> ci: back-off Dependabot to monthly due to spam

- go.mod
- go.sum
Bump go-deluge to v1.1.0 to fix issues.
> build(deps): bump go-deluge to v1.1.0

- pkg/lidarr/lidarr.go
- pkg/radarr/radarr.go
- pkg/readarr/readarr.go
- pkg/sonarr/sonarr.go
- pkg/whisparr/whisparr.go
For reasons unbeknownst to me, pushes can take lots of time before autobrr gets a return back. The pushes eventually succeed, but not before autobrr logs an error on the action as the connection has since "timed out". As these actions are run in a goroutine, we're not at risk of blocking main application activity, so just crank it.
> feat(downloadclients): arrs increase timeout for release/push

- .github/workflows/release.yml
During testing and frustrations with the performance of a Linux node, it was found that Mac and Windows are significantly more powerful. This reverts a change from 99 to a more realistic number, as Windows nodes appear more stable, but have less memory available than Apple.
> ci: goreleaser lower parallelism to mitigate OOM issues

- .github/workflows/release.yml
According to the docs [[1]](https://github.com/docker/metadata-action/tree/master?tab=readme-ov-file#tags-input), the default entry for tags is:
```
tags: |
type=schedule
type=ref,event=branch
type=ref,event=tag
type=ref,event=pr
```
But this **will not** parse the semver [[2]](https://github.com/docker/metadata-action/blob/master/src/meta.ts#L62) to match the pre-releases.
By set tags to `semver`, **it will** parses pre-releases [[3]](https://github.com/docker/metadata-action/blob/master/src/meta.ts#L66) and it **will not** set latest tag on them [[4]](https://github.com/docker/metadata-action/blob/master/src/meta.ts#L159-L168).
This MR also removes the ref event=tag because it is the one that will apply latest by default [[5]](https://github.com/docker/metadata-action/blob/master/src/met …
> ci: fix docker metadata to parse semver tags

- internal/database/release.go
Now that there's full documentation for this on the page in-product, it's going to see more usage. This makes the keys case-insensitive (Season:9 is accepted, as opposed to just season:9) to help prevent reports of it "not working".
> fix(releases): improve search keyword specifiers

- .github/workflows/release.yml
Ref https://github.com/docker/metadata-action?tab=readme-ov-file#typesemver
`{{version}}` was missing the v prefix for the tag that we have used since the start.
> ci(docker): change docker metadata tag to `{{raw}}` from `{{version}}`

- pkg/porla/domain.go
The `flags` property in the Porla `torrents.list` response has changed from an int to a string. Instead of breaking things, just remove the property in the serialization since it is unused.
> fix(downloadclient): Porla remove flags property

- web/src/components/modals/index.tsx
- web/src/components/tooltips/CustomTooltip.tsx
- web/src/screens/filters/Importer.tsx
- web/src/screens/filters/List.tsx
- web/src/screens/filters/_configParser.ts
- web/src/screens/filters/_const.ts
feat: added autodl-irssi filter importer/parser
enhancement: improved filter importing code
enhancement: redesigned filter list page
fix(DeleteModal): don't center text on mobile
fix(Tooltip): don't set opacity (avoid console.log spam), update prop names
The autodl-irssi parser can also parse networks/channels but they're unused at the moment. Left as dead-code for future reference, in case somebody decides to add those on the backend-side.
properly closes #454
In case of incompatibilities, warnings are displayed while importing. This version also properly handles various edge cases and also multiple values for some fields, e.g. formats, quality, etc, which are not handled by the parser available at `convert.autobrr.com`.
> feat(web): add autodl-irssi filter import

- internal/indexer/definitions/subsplease.yaml
Some releases wouldn't parse, and the culprit was the `lines` part where `pattern` was set as `- pattern` and that made the `lines` be split in two, even though SubsPlease is using single lines for announce and not multiple.
ref #494
> fix(indexers): SubsPlease parse line pattern

- internal/notification/telegram.go
This adds file size information to notifications sent via Telegram.
See also: https://github.com/autobrr/autobrr/pull/1143
> feat(notifications): Telegram display file size

- internal/indexer/api.go
Add additional check for empty body from indexer API check for GetTorrentByID.
Depending on the response from the indexer it would only trigger rejection errors for certain errors. Found out that some responses answer with 200 OK but bad status body and those were not caught.
> fix(indexers): API get torrent check for nil body

- internal/indexer/definitions/pbay.yaml
This PR fixes the pbay regex pattern which would previously cause misparsing of the category in following case:
`[Category] [Some] Release`
In this case the category did include `] [Some`, which we do not want.
> fix(indexers): pbay regex pattern

- internal/indexer/definitions/pbay.yaml
pbay changed their announce bot name (again)
added the new bot to the definition.
ref #790
> fix(indexers): pbay announce bot name

- internal/indexer/definitions/ptp.yaml
PTP has started to announce freeleech recently so this PR adds support to parse it properly instead of having to use `Match release tags` like `*freeleech*`.
https://regex101.com/r/QapE4W/1
> feat(indexers): PTP support freeleech

- web/src/components/inputs/input_wide.tsx
Doesn’t currently work on the `auth.password` and `nickserv password` fields for some reason. I believe they share the `name=auth.password`.
> feat(web): disable 1password prompts

- internal/database/feed_cache.go
- internal/database/sqlite.go
- internal/domain/feed.go
- internal/feed/newznab.go
- internal/feed/rss.go
- internal/feed/torznab.go
When one or more feeds run at the same time it leads to locking errors with SQLite.
This is an attempt to fix that by batching inserts of feed cache items instead of one per item.
> feat(feeds): improve caching

- internal/indexer/definitions/torrentseeds.yaml
There is no way of issuing an `IDENTIFY` or `GROUP` a bot nick with NickServ on the TorrentSeeds network.
It only supports the `HELP` and `SET GREET` command for users.
So I would suggest to remove those fields for the indexer setup with TorrentSeeds to not cause any confusion.
> fix(indexers): TorrentSeeds remove nickserv fields

- internal/indexer/definitions/myanonamouse.yaml
Autobrr's Discord had a user indicate that the format needs to be "mam_id=$id;"
The $id being the one created in the Preferences > Security in MAM website for the relevant IP.
> docs(definitions): MAM clarify cookie usage

- internal/domain/release.go
- internal/indexer/definitions/beyondhd.yaml
This PR adapts the BHD regex to match the new announces which now announce their various freeleech options.
I am unsure of what to do with the freeleech var so i improvised and used `freeleech` for a start..
Do we want to use `freeleech` or `freeleechPercent` here?
There might me some changes needed at other files to overcome that problem?
(pun intended)
Regex101 Link: https://regex101.com/r/KQeS0G/1
> feat(indexers): BHD freeleech announces

- pkg/btn/btn.go
Fix for BTN api to return any errors that occurred, instead of crashing the web ui :see_no_evil:
> fix(indexers): BTN api handle errors

- web/src/forms/settings/IrcForms.tsx
The fields of an IRC channel entry will now be disabled for editing when `channels[index].name === "#ptp-announce-dev"`
> feat(web): disable IRC fields

- internal/database/postgres_migrate.go
- internal/database/sqlite_migrate.go
Fix bad database migration for `filter_external`.
Tested with both Pg and SQLite.
> fix(database): migrations filter_external

- cmd/autobrr/main.go
- go.mod
- go.sum
This sync's up GOMAXPROCS with the implemented quota assigned by cgroup. The outcome is (hopefully) lower latency to complete tasks.
More information available at: https://github.com/uber-go/automaxprocs
> feat(go): implement cpu quota detection

- cmd/autobrr/main.go
Refactored the server shutdown code to handle all signals in a unified way and removed the unnecessary `SIGKILL` case. `SIGKILL` cannot be caught, so its inclusion is unnecessary. On database closure error, we exit with status code `1` to signal a fault, otherwise, we exit with `0` for a clean shutdown.
Ref #1247
> refactor: streamline shutdown signal handling

- internal/config/config.go
- internal/config/config_test.go
Refactor mutex handling, optimize byte slice creation, and clean up code in accordance with go.staticcheck and copylocks guidelines.
- Changed `AppConfig`'s mutex to `*sync.Mutex`, preventing mutex copying and enhancing thread safety.
- Simplified byte slice initialization in `writeConfig` for efficiency.
- Removed redundant return in `DynamicReload` for better code clarity.
> refactor(config): copylocks and staticcheck findings

- web/src/screens/filters/Details.tsx
- web/src/screens/filters/sections/Advanced.tsx
We now collapse any section that doesn't contain data, instead of having only some sections open by default.
This should improve UX by focusing attention on sections that are actively filled out.
> feat(filters): auto-expand used sections

- internal/database/action.go
- internal/database/action_test.go
This fixes the no sql row set, no idea why it does that but removing the row check I added fixes it, Not sure if it affects others rowsAffected in the delete function.  I haven't come across it and it happened on postgresdb, probably gives same error in sqlite but I could be wrong, someone can just test the dev version and confirm it, if needed.
> fix(filters): could not delete filter without actions

- internal/database/filter.go
this is a hot path, the scan can be improved by ignoring values which would help with icache, but would ultimately likely be slower for the common case (single / no external filters).
> refactor(filters): optimize assignment to allocation

- internal/http/server.go
Linux capabilities can limit the usage of dual stack configurations through namespaces. It's rather silly, but there's been sporadic reports over the years about this - so try for the best, downgrade to v4, then v6.
> fix(http): specify ip stack when listen fails

- go.mod
- go.sum
- internal/domain/filter.go
- internal/domain/filter_test.go
This fixes regex patterns that contain commas to not split inside valid regex delimiters.
Fixes #1241
> fix(filters): do not split commas inside valid Regexp

- web/src/screens/filters/List.tsx
Made sure a tooltip isn't rendered if at least one action is active.
New:
Old:
> fix(filters): hide tooltip when actions are active

- go.mod
- go.sum
- internal/action/qbittorrent.go
- internal/database/action.go
- internal/database/postgres_migrate.go
- internal/database/sqlite_migrate.go
- internal/domain/action.go
- web/src/domain/constants.ts
- web/src/screens/filters/sections/Actions.tsx
- web/src/screens/filters/sections/action_components/ActionQBittorrent.tsx
- web/src/types/Filter.d.ts
~~It *almost* works as you'd expect, but if user sets either `Top of queue` or `Bottom of queue` when `Torrent Queueing` is disabled, the release is flagged as an `Action error` in the release history. It gets added to the client regardless. This results in it breaking the `MAX_DOWNLOADS` rule if set. This should be an easy fix I think.~~
~~When `Torrent Queueing` is enabled, it works just fine from my testing.~~
Tested on 4.3.9.
closes #1012
> feat(actions): qBittorrent add priority handling

- web/src/components/modals/index.tsx
This PR enables the Force Run modal to be confirmed with the ENTER key instead of clicking the Force Run button
> enhancement(web): force run feed with enter key

- internal/database/filter.go
- internal/database/filter_test.go
- pkg/cmp/cmp.go
With the recent refactor of `FilterRepo.FindByIndexerIdentifier` we use a map to hold the results and then make a slice of it. The map does not keep order by priority.
This PR fixes that by sorting the `filters slice` by `filter.Priority`.
> fix(filters): ensure sort by priority

- .github/workflows/release.yml
Windows performance on GitHub is wildly unpredictable. I/O patterns are non-deterministic, and even though the compute is substantially faster, prepping the filesystem still takes upwards of 5 minutes before kicking off any real work.
> build(ci): change goreleaser back to ubuntu runner

- .github/workflows/release.yml
Fix for mistakenly tagging pre-releases as `latest`.
> build(docker): do not tag pre-release as latest

- web/src/screens/settings/Irc.tsx
Fixes the colors of the IRC settings page for light mode.
Tested both modes now. Mea culpa.
Before:
After:
> fix(web): irc settings light theme colors

- web/package.json
- web/pnpm-lock.yaml
Theres an issue when building the web on armv7 (maybe other platforms too):
```sh
> tsc && vite build
/builds/fabricionaweb/aports/testing/autobrr/src/autobrr-1.35.0/web/node_modules/.pnpm/rollup@4.9.0/node_modules/rollup/dist/native.js:38
throw new Error(
^
Error: Your current platform "linux" and architecture "arm" combination is not yet supported by the native Rollup build. Please use the WASM build "@rollup/wasm-node" instead.
The following platform-architecture combinations are supported:
android-arm
android-arm64
darwin-arm64
darwin-x64
linux-arm
linux-arm64
linux-arm64 (musl)
linux-riscv64
linux-x64
linux-x64 (musl)
win32-arm64
win32-ia32
win32-x64
If this is important to you, please consider supporting Rollup to make a native build for your platform and architecture available.
``` …
> build(web): override rollup with wasm-node version

- internal/notification/gotify.go
- internal/notification/lunasea.go
- internal/notification/message_builder.go
- internal/notification/message_builder_test.go
- internal/notification/ntfy.go
- internal/notification/pushover.go
- internal/notification/shoutrrr.go
- internal/notification/telegram.go
Fixes a regression that removed the html attributes for Pushover and Telegram notifications.
> fix(notifications): Pushover and Telegram formatting

- internal/indexer/definitions/torrentseeds-music.yaml
This PR adds support for the torrentseeds music announce channel.
There is some barely visible / invisible whitespace in the announce lines that i couldn't be bothered looking for,
hence the `\s+` to account for that even though it makes it less readable.
> feat(indexers): add TorrentSeeds Music

- internal/domain/macros.go
- internal/domain/macros_test.go
Exposes the Type field to macros.  This is beneficial for external scripts and webhooks that may want to alter their behavior based on the type of the Release.
> feat(macros): add Type

- internal/indexer/definitions/digitalcore.yaml
Append a trailing slash to infourl to avoid site redirecting to home page.
> fix(indexers): DigitalCore InfoURL

- internal/indexer/definitions/nebulance.yaml
A user asked us to change the IRC address in our definition for NBL too since they share the same network as ANT.
Related #1403
> fix(indexers): NBL new irc address

- web/src/components/inputs/common.tsx
@stacksmash76 noticed a color difference in the indexer forms.
Old:
New:
> fix(web): unify border colors in indexer form

- internal/domain/macros.go
- internal/domain/macros_test.go
Exposes the FilterID field to macros. This is beneficial as another way to allow external tools to know which filter generated an event.  This should be more stable than the Filter Name which is already present because the Filter ID is immutable.
> feat(macros): add FilterID

- web/src/screens/filters/sections/Advanced.tsx
This makes the collapsible sections open by default again when:
- Values in the fields are present
- Values in the multiselect fields are present
- Regex switches are enabled.
> fix(filters): open used collapsible sections by default

- web/src/screens/filters/sections/MoviesAndTV.tsx
Small fix to correctly link to a proper anchor on the page.
The correct anchor was found using the actual documentation page.
> fix(filters): point to the correct docs page anchor for `skipping seasons packs`

- internal/indexer/definitions/locadora.yaml
We just added the fields internal and tvdb/tmdb ids to the announce and these are the new regular expressions to match those changes. Looking forward to having access to Tags as a variable to be used on scripts.
Thank you
> feat(indexers): Locadora add internal and tags var

- web/src/components/tooltips/Tooltip.tsx
This PR fixes/refactors the tooltips in order to make them clickable when a touchscreen is present.
I could only test this on a Android tablet so i would appreciate someone testing this with an iPad with Safari e.g.
potentially fixes #1389
> fix(web): make tooltips clickable if touchscreen is present

- internal/irc/handler.go
With Go v1.22 they deprecated a lot of old TLS cipher suites that was deemed insecure. https://go.dev/doc/go1.22#crypto/tls
In the world of IRC there is a lot of networks running on ancient ircd versions, so we unfortunately have to comply with that. 
This only fixes IRC for now, not sure yet if we need to change anything for HTTP calls.
Fixes #1443
> fix(irc): allow insecure TLS cipher suites

- internal/database/postgres.go
- internal/database/sqlite.go
This PR fixes the wrong number being printed in the logs during database schema upgrades for SQLite and PostgreSQL.
Old:
```
INF Beginning database schema upgrade from version 54 to version: 55 module=database type=sqlite
INF Upgrading Database schema to version: 54 module=database type=sqlite
INF Database schema upgraded to version: 55 module=database type=sqlite
```
New:
```
INF Beginning database schema upgrade from version 54 to version: 55 module=database type=sqlite
INF Upgrading Database schema to version: 55 module=database type=sqlite
INF Database schema upgraded to version: 55 module=database type=sqlite
```
Fixes #1440
> fix(database): migrations log correct upgrade var version

- .github/workflows/release.yml
This should fix the missing commit hash when using the docker image.
> fix(ci): missing commit hash in docker builds

- internal/indexer/definitions/fearnopeer.yaml
-  Do they have irc announce? Yes
-  Link to existing `autodl-irssi .tracker` file: N/a
- Indexer name: FearNoPeer
- Short name: FnP
- URL: https://fearnopeer.com/
- Download link: UNIT3D format, https://fearnopeer.com/torrents/77448.rsskey
Multi-line announce:
Sample movie
```
[FnP] New Upload - Category: [Movies] Type: [Remux] Name: [Terror Out of the Sky 1978 1080p BluRay REMUX AVC DTS-HD MA 2.0-HDT] Size: [17.11 GiB] Uploader: [MartyMcFly] Url: [https://fearnopeer.com/torrents/78627]
```
Sample TV
```
[FnP] New Upload - Category: [TV] Type: [WEB-DL] Name: [江河之上 2024 S01E12 1080p WEB-DL AAC 2.0 H.264-HHWEB] Size: [703.09 MiB] Uploader: [oppie] Url: [https://fearnopeer.com/torrents/78626]
```
- Network name: LibraIRC
- Network address: irc.librairc.net
- Port: 6697
- IRC Channels: …
> feat(indexers): add FearNoPeer

- cmd/autobrr/main.go
- internal/domain/irc.go
- internal/domain/release.go
- internal/http/irc.go
- internal/http/release.go
- internal/http/server.go
- internal/indexer/service.go
- internal/irc/handler.go
- internal/irc/service.go
- internal/logger/logger.go
- internal/release/service.go
- web/src/api/APIClient.ts
- web/src/screens/Logs.tsx
- web/src/screens/settings/Irc.tsx
- web/src/types/Irc.d.ts
Implement re-process from network channel logs.
> [!IMPORTANT]
> Only supports single line announces to start with.
> feat(irc): manually re-process announces

- cmd/autobrr/main.go
Do not exit with log fatal on error from setting `GOMAXPROCS`.
> fix(backend): do not exit on `GOMAXPROCS` error

- web/src/domain/constants.ts
The parsing library doesn't differentiate between 1080i and 1080p but we have both options in the resolution dropdown which causes missed releases because autobrr will say that a 1080i is 1080p which will not result in a match..
This PR removes the interlaced option in the resolution dropdown because of that.
~~As a miniscule further change the AHDTV source has been added and an according test with it.~~
> fix(filters): remove unusable resolution constants

- web/src/api/QueryClient.tsx
Speculative fix for broken redirect to /login when using baseurl.
> fix(auth): correct redirect on bad session cookie

- internal/indexer/definitions/animeworld.yaml
- web/src/forms/settings/IndexerForms.tsx
-  Do they have irc announce? Yes
- Indexer name: AnimeWorld
- Short name: AW
- URL: https://animeworld.cx
- Download link example: https://animeworld.cx/torrent/download/00000.{rss_key}
(Release names slightly modified to not use any real but very similar releasenames)
- `Neuer Upload: Magic.S02E10.Ger.Eng.Sub.AAC.1080p.WEB.h264-ABC [Kategorie: Anime Serien][Typ: WebDL][Auflösung: 1080p][Größe: 1.35 GB][FL: 100%] | https://animeworld.cx/torrents/00000 | Uploader: NotAnonymous`
- `Neuer Upload: The.Zero.S04.German.DL.DTS.1080p.BluRay.10bit.x265.Repack-ABC [Kategorie: Anime Serien][Typ: Encode][Auflösung: 1080p][Größe: 17.28 GiB][FL: 100%][Vorgestellt] | https://animeworld.cx/torrents/00000 | Uploader: Anonym`
- `Neuer Upload: How.to.Train.2010.German.DL.AC3.1080p.BluRay.x264-ABC …
> feat(indexers): add AnimeWorld

- web/src/forms/settings/IndexerForms.tsx
Fix for creating indexers that does not have the `channels.password` setting, which is all but 2.
Fixes #1478
> fix(indexers): could not create

- internal/indexer/definitions/nyaa.yaml
The NekoNeko announcer for Nyaa now appends trusted/remake/batch to the end of the announcement line, this PR catches these as tags for use in filters.
While the batch tag is not used on Nyaa, it's mentioned in the FAQ so the addition is there.
**Tags added**:
- trusted
- remake
- batch
> feat(indexers): Nyaa add trusted, remake and batch tags

- internal/domain/filter.go
- internal/filter/service.go
- pkg/sanitize/sanitize.go
Add check for External Filter and Actions Exec program if it exists on save.
And improve cleaning of filter data.
> feat(filters): validate existence of external exec cmd

- internal/logger/logger.go
> fix(logger): properly SetGlobalLevel on all levels

- internal/notification/telegram.go
- web/src/forms/settings/NotificationForms.tsx
Telegram API is blocked in some places. Therefore, I added the feature to allow customizing Telegram API domain name. Very few changes were made. If not specified, it directly uses "https://api.telegram.org/" itself.
> feat(notifications): add support for custom Telegram api url

- internal/database/database_test.go
This function is unused; setupPostgresForTest and setupSqliteForTest are used instead.
> chore(database): remove unused test func

- web/src/screens/auth/Login.tsx
`onError` now accepts an error object as its argument.
This will help in cases the backend is unreachable. The current version displays a "bad credentials" regardless of error.
Thanks for the help Ghost!
> feat(auth): improved error handling during login

- cmd/autobrr/main.go
- internal/database/indexer.go
- internal/database/release.go
- internal/domain/release.go
- internal/indexer/service.go
Update the indexer baseURL (for `info_url` and `download_url`) of releases when changed in indexer settings.
> feat(indexers): update release baseurl on update

- web/package.json
- web/pnpm-lock.yaml
- web/src/routes.tsx
- web/src/screens/Settings.tsx
- web/src/screens/filters/Details.tsx
- web/src/screens/releases/ReleaseTable.tsx
This PR branches off the branch of #1527 
Due to fixes in `"@tanstack/router-devtools": "^1.31.1"`  
the routes in the arrays for the settings and the filter pages had to be adapted.
During fixing the routes i saw that we had a `ReleasesIndexRoute` that couldn't be accessed  
and that isn't in use for some other part from what i can tell.  
So took the freedom and removed it and moved the component into the parent route `ReleasesRoute`
> fix(web): use absolute paths for router links

- internal/domain/indexer.go
Fixes an issue where using an alternative URL for the indexer links would not actually update new links for IRC indexers.
> fix(indexers): irc baseurl override for links

- web/src/App.tsx
- web/src/components/header/RightNav.tsx
- web/src/utils/Context.ts
Added a dynamic theme switcher to the navbar for light/dark mode toggling.
Additionally, it now listens for system-level theme changes, and defaults to system-preferred theme when localstorage is empty.
> feat(web): add theme toggle to navbar

- internal/indexer/definitions/iptorrents.yaml
In case this won't be a permanent change on their side, just close this PR.
> fix(indexers): new IPT announce bot name

- web/src/components/inputs/select.tsx
- web/src/screens/filters/sections/action_components/ActionQBittorrent.tsx
This PR fixes the spacing between the input field of the qbittorrent action rules in 1.42.0-rc1
Left is old - right is new.
> fix(web): qbittorrent action rules spacing

- web/src/routes.tsx
This PR sets the root pending component for desktop to 30% height and centers it for mobile.
Before the root pending component was stuck at the top of the screen.
Other pending components are not affected by this change.
Old:
New:
> fix(web): root pending component placement

- web/src/screens/settings/Account.tsx
Due to PR #1527, when changing credentials in the account settings,
there is now an incorrect error when providing no or an incorrect current password.
Correct me if i am wrong, but the since the only thing that can go wrong here,   
is that either no or an invalid password has been provided we can just catch the error on the `updateUserMutation`
and return the correct error message in a toast.
Mea culpa, should've caught that beforehand.
> fix(auth): show correct error when providing wrong current password at credential change

- internal/feed/service.go
Testing RSS feeds when providing a cookie is currently broken. The custom client should be used because it supports setting a cookie.
> fix(rss): use custom client for rss tests

- web/src/forms/settings/NotificationForms.tsx
During the headlessUI v2 refactor the notification settings form slideover slipped through my fingers,
resulting in it not being clickable. Instead it will just close again.
This PR fixes this unwanted behaviour.
Mea culpa for this oversight on my part!
> fix(web): add notification panel

- web/src/domain/constants.ts
This PR adds `SLOVAK` as an language option in the advanced filters which has previously been missing.
> feat(filters): add SLOVAK language option

- internal/config/config.go
The namespace checks are becoming more inconsistent with cgroup sleuthing and similar. There's a good chance if the application is running as pid 1, we're either in a micro kernel or a namespace for this purpose.
> feat(config): check pid for container startup

- internal/domain/irc.go
- internal/indexer/indexer_test.go
The message from OPS Announce does not contain a % sign and that seemed to break it. This is probably not the best fix but it is something.
> CD/FLAC/Lossless/Cue/Log/100
#1535 Attemping to fix this issue.
> fix(indexers): OPS log score parsing

- web/src/screens/filters/List.tsx
This PR fixes the filter dropdowns being cutoff when there is not enough space towards the bottom edge of the viewport.
There is still *some* weird behaviour when there isn't enough space towards the bottom and the top.
In this case a scrollbar will appear for the dropdown but
you still won't be able to scroll to all the entries on viewports with very low height.
However, the case that there isn't enough space towards the bottom and the top feels very unprobable.
fixes #1597
> fix(web): filter dropdown cut off

- internal/action/lidarr.go
- internal/action/radarr.go
- internal/action/readarr.go
- internal/action/sonarr.go
- internal/action/whisparr.go
- internal/database/indexer.go
- internal/domain/indexer.go
- internal/indexer/service.go
- internal/release/service.go
Fixes an issue with retrying release actions. The external identifier would be missing and lead to unexpected results when pushing to the arrs.
> fix(releases): retry action missing external indexer identifier

- Dockerfile
- ci.Dockerfile
- goreleaser.Dockerfile
Fix for https://docs.docker.com/reference/build-checks/legacy-key-value-format/
> fix(docker): update deprecated LABEL format

- internal/feed/service.go
Implement staggered start of feeds to mitigate SQLite Busy errors.
> fix(feeds): implement staggered start

- internal/indexer/definitions/theoldschool.yaml
This PR adapts the TheOldSchool regex to account for the new EXCLUSiVE tag.
> fix(indexers): adapt TheOldSchool regex

- internal/indexer/definitions/hdonly.yaml
This PR fixes the HD-Only `torrenturl` in order for users to be able to download again.
> fix(indexers): HD-Only `torrenturl`

- cmd/autobrr/main.go
- internal/action/deluge.go
- internal/action/lidarr.go
- internal/action/porla.go
- internal/action/qbittorrent.go
- internal/action/radarr.go
- internal/action/readarr.go
- internal/action/rtorrent.go
- internal/action/run.go
- internal/action/sabnzbd.go
- internal/action/service.go
- internal/action/sonarr.go
- internal/action/transmission.go
- internal/action/whisparr.go
- internal/database/action.go
- internal/database/action_test.go
- internal/database/download_client.go
- internal/database/download_client_test.go
- internal/database/filter.go
- internal/database/filter_test.go
- internal/database/release_test.go
- internal/domain/action.go
- internal/domain/client.go
- internal/domain/client_test.go
- internal/download_client/cache.go
- internal/download_client/service.go
- internal/filter/service.go
- internal/http/download_client.go
- internal/release/service.go
- pkg/transmission/transmission.go
Return early if the client of an action is disabled.
* Refactor how DownloadClient is fetched and cached
* Update tests
* Update various methods for DownloadClient
* Unify client handling in action run
Fixes #1623
> fix(actions): reject if client is disabled

- internal/config/config.go
- internal/diagnostics/profiling.go
- internal/domain/config.go
Fix for reading enabled flag for profiling in config file.
> fix(diagnostics): profiling config flags

- web/src/utils/Context.ts
This PR remove the `checkForUpdates` JSON object from the `autobrr_settings` key
which seems not to be used.
https://github.com/autobrr/autobrr/blob/34d6e0cf609e225fa22261177d4b43c258f03566/web/src/screens/settings/Application.tsx#L141
The checkbox for it just writes to the config file upon triggering but doesn't change the JSON object.
So i feel list this can be removed?
> fix(web): remove unused `checkForUpdates` JSON object

- internal/action/run.go
- internal/domain/action.go
- internal/domain/filter.go
- internal/domain/release.go
- internal/filter/service.go
Fix for `TorrentHash` in Macros being empty if torrent has not already been downloaded for parsing.
Fixes #1122
> fix(macros): `TorrentHash` empty

- web/src/components/modals/index.tsx
- web/src/forms/filters/FilterAddForm.tsx
This PR sets the initial focus on the input field for the force run modal and the filter add form,
so that you don't have to click into the fields and you can just begin to type and hit ENTER.
The initial focus handling needed two different approaches since using `data-autofocus` in the filter add form
breaks the CSS transition of it by it just popping up and not sliding in.
In case the individuals reviewing this PR can think of other elements where this would be beneficial,
please feel free to add a suggestion by commenting here.
> feat(web): manage initial focus for force run modal and filter add form

- web/src/api/queries.ts
- web/src/screens/releases/ReleaseFilters.tsx
While reviewing #1706 i missed that the indexer filter on the releases page was still showing the identifier
instead of the name now.
This PR adds the required changes to make the options and the current filter value show the name.
> feat(releases): show indexer name in indexer filter

- internal/domain/notification.go
- internal/notification/message_builder.go
- internal/notification/telegram.go
This PR adds a conditional sender payload for telegram for the message to say which app the notification is coming from.
Fixes #1722
> feat(notifications): Telegram set sender

- web/src/components/data-table/Cells.tsx
With the recent changes from #1706 the table now overflows in rare cases due to the indexer names being longer.
This PR shortens the max widths of the **release name cells** in order for the table rows not to overflow the body.
I tested this PR with quite a few of my gathered examples but i would appreciate if someone can verify my changes 
with their examples so that we can make sure that the table won't overflow in other cases aswell.
Old behaviour at 2560x1600:
New behaviour at 2560x1600:
Comparison between old and new behaviour at 1280x1600
> fix(web): activity/release table cell widths

- README.md
This PR fixes 2 links in the readme.md and rephrases the feature requests section to account for the usage of the new discusssions usage.
> fix(docs): update feature requests link and swizzin install link

- web/src/forms/filters/FilterAddForm.tsx
- web/src/forms/settings/APIKeyAddForm.tsx
- web/src/forms/settings/DownloadClientForms.tsx
- web/src/forms/settings/IndexerForms.tsx
- web/src/forms/settings/NotificationForms.tsx
- web/src/forms/settings/ProxyForms.tsx
During the headlessUI refactors i did, i messed up a couple of mobile sildeover forms.
This PR fixes the slideovers to take full widths for the mobile forms while mostly retaining the widths for the desktop view.
Why mostly? I cleaned up the paddings on the slideovers since the do not add any real value and are just clutter imo.
I tested to following forms for correct desktops and mobile views and uniformity:
> fix(web): form slideovers for mobile views

- internal/database/postgres_migrate.go
- internal/database/sqlite_migrate.go
- internal/indexer/definitions/fuzer.yaml
Old URL just displays a white page while new URL shows login form.
**WARNING:**
This PR contains database migrations. You **cannot** go back to 1.46.x once you run a version with this fix
> fix(indexers): new baseURL for Fuzer

- .github/workflows/release.yml
After merge the #1721 we notice it that some steps doesnt run on merge event and pipeline failed because was missing "dist" folder (created by those skipped steps).
This is to fix it but also ensure to run on tags creation only.
> fix(build): run web-dist tarball step for tags only

- internal/database/notification.go
- internal/notification/telegram.go
- web/src/forms/settings/NotificationForms.tsx
- web/src/types/Notification.d.ts
**WARNING:**
This PR contains database migrations. You cannot go back to 1.46.x or earlier once you run a version with these changes.
Since there were complaints about the hardcoded autobrr sender in the Telegram notifications
it's now an optional field in the Telegram form fields.
If that field is left empty, there will not be an additional line with a sender.
If you enter something in this field, there will be an additional line with the string you entered.
ref https://github.com/autobrr/autobrr/pull/1723
> feat(notifications): optional Telegram sender

- .github/workflows/release.yml
Upload `web-dist.tar.gz` to release assets after goreleaser build and push.
This uses the action [softprops/action-gh-release](https://github.com/softprops/action-gh-release?tab=readme-ov-file#%EF%B8%8F-uploading-release-assets) which has this function:
> If a tag already has a GitHub release, the existing release will be updated with the release assets.
Running this on tag events after GoReleaser _should_ work.
> build: upload web-dist to release assets on tag

- internal/action/deluge.go
Potential fix for deluge issues. Deluge uses RPC to the daemon and opens a connection. The cached client likely interferes with this so lets revert this to the previous way.
Fixes #1736 
Fixes #1737
> fix(downloadclients): do not load Deluge from cache

- internal/action/lidarr.go
- internal/action/radarr.go
- internal/action/readarr.go
- internal/action/sonarr.go
- internal/action/whisparr.go
- pkg/lidarr/client.go
- pkg/lidarr/lidarr.go
- pkg/radarr/client.go
- pkg/radarr/radarr.go
- pkg/readarr/client.go
- pkg/readarr/readarr.go
- pkg/sonarr/client.go
- pkg/sonarr/sonarr.go
- pkg/whisparr/client.go
- pkg/whisparr/whisparr.go
Change size types to uint64 for arr clients, and also add error handling to url.Parse methods.
This should fix CodeQL reports and lint errors.
> fix(downloadclients): arrs change size type to uint64

- internal/http/filter.go
- web/src/screens/filters/List.tsx
This PR will implement sorting filters by date.
The 4 options will be:
- Recently created first
- Recently created last
- Recently updated first
- Recently updated last
The react query devtools show that the field param is getting submitted,
but checking with the debugger in GoLand in database/filter.go:75 shows that the param is missing...
Not sure what is going on here 🤔
> feat(filters): sort by created and updated

- internal/releasedownload/download_service.go
Handle rate-limit retry for downloads. Been observed so far only with RSS on UNIT3D based indexers.
> feat(downloads): handle http status 429 rate-limit retry

- internal/database/filter.go
- internal/database/filter_test.go
When counting the number of recent downloads to enforce the `Max Downloads` rule on a filter, multiple actions attached to the same filter will be counted as multiple downloads.
This PR changes the logic to count multiple actions as a single download.
> fix(filters): release download counts

- pkg/wildcard/match.go
- pkg/wildcard/match_test.go
In some cases names would be out of bounds and lead to a panic.
> fix(wildcard): check name length

- .github/workflows/release.yml
Turns out that the flat tarball isnt working as I expected it would 🙈 sorry
It will actually be better to have it inside folder because the apkbuilder doest put them inside any folder when extracting and it end being a messy src folder
> fix(build): do not create flat tarball for web-dist

- internal/database/postgres_migrate.go
- internal/database/sqlite_migrate.go
- internal/indexer/definitions/fuzer.yaml
This PR contains database migrations. 
You cannot go back to an older or current stable version once you have used this PR.
maybe push a new patch version for this?
fixes #1763
> fix(indexers): update Fuzer IRC addr

- pkg/ops/ops.go
Fix for OPS API returning required ratio as float if not 0.
> fix(indexers): OPS API test function

- pkg/ptp/ptp.go
- pkg/ptp/ptp_test.go
- pkg/ptp/testdata/ptp_get_torrent_by_id.json
Fix for PTP api returning ID as int on browse.php endpoint and string on Get by ID.
> fix(indexers): PTP API test function

- .github/workflows/codeql.yml
- .github/workflows/golang-linter.yml
- .github/workflows/release.yml
- go.mod
Our prebuilt binaries are built with`v1.23.0`, instead of building with the latest patch release. The docker images are "unaffected", since they are built with the latest patch release through alpine.
Can be checked with `go version /path/to/autobrr`
```console
/autobrr_1.47.1_darwin_arm64 ❯ go version autobrr                                                                                                                                            11:49:35 AM
autobrr: go1.23.0
```
> chore(build): update workflows and `go.mod` to use latest patch version of Go

- web/src/screens/settings/Logs.tsx
The link linked to the page you're already viewing, which seemed unnecessary.
Old:
New:
> fix(web): remove unnecessary link to Logs

- internal/config/config.go
The `config file reloaded!`-message is being logged twice when the configuration is reloaded.
Changes made to address the issue:
- Moved `viper.WatchConfig()` before setting up the `OnConfigChange` callback in `internal/config/config.go`
- Used `defer` for unlocking the mutex to ensure it's always unlocked
> fix(config): log reload message once

- internal/action/deluge.go
This feature was previously in a TODO state. I set out to complete it, but considering that labels generally only need to be added once, checking every time would consume extra time. Therefore, the processing logic I used is to set the label directly unless an exception with rpcErr.ExceptionMessage == 'Unknown Label' is returned. I don't have a Deluge 1.x client, but since there's no difference in the interface in go-libdeluge, I believe it should also work on Deluge 1.x. I would be really grateful if someone could help me test it.
> feat(download-client): add label to Deluge if it does not exist

- pkg/wildcard/match.go
- pkg/wildcard/match_test.go
Fix for multi-line matching with wildcard on for example long RSS descriptions.
Fixes #1766
> fix(wildcard): match on multi-line data

- internal/domain/filter.go
Fix lint warnings about using `min` and `max` as variable names.
> fix(filters): lint warning variable naming

- internal/domain/release.go
- internal/indexer/definitions/btfiles.yaml
BTFiles announces size with comma delimiter. The humanize package strips the comma so `3,76GB` becomes `376GB` which is not ideal.
This fix adds a replace comma to dot.
Fixes #1804
> fix(indexers): BTFiles size parsing

- internal/database/release.go
- internal/domain/release.go
- internal/release/service.go
Update release size after actions run, in case they download and parse .torrent files.
This used to work but was changed/forgotten in one of the many big refactors.
Fixes #1803
> fix(releases): update size after actions run

- internal/proxy/service.go
- pkg/sharedhttp/http.go
Add new shared transport used only for Proxies to not interfere with non-proxied requests.
When using the shared transports and once setting a proxy it would persist on the client/transport, even if it was disabled by the application.
This PR adds a new `sharedhttp.ProxyTransport` which proxies will use.
Fixes #1793
> fix(proxy): add shared transport for proxies

- cmd/autobrr/main.go
- internal/action/run.go
- internal/database/feed.go
- internal/database/feed_test.go
- internal/domain/event.go
- internal/domain/feed.go
- internal/domain/indexer.go
- internal/events/subscribers.go
- internal/feed/service.go
- internal/indexer/service.go
Delete feed when deleting indexers.
This uses the eventbus to pass messages because importing feedService into indexerService is not possible with the current setup.
Fixes #1800
> fix(indexers): delete feed with indexer

- internal/database/postgres_migrate.go
- internal/database/sqlite_migrate.go
- internal/indexer/definitions/fearnopeer.yaml
Update FNP irc server and add migrations for SceneHD and BitHUmen changes all in one.
The update for FNP from LibraIRC to P2P-Network will set the nick to nick_0 to not cause any UNIQUE constraint issues. Users will have to update or merge with existing P2P-Network config.
> feat(indexers): FearNoPeer update IRC server

- internal/http/encoder.go
- internal/http/server.go
Adds proper error logging with stack traces for API error responses.
**Before:** API errors (like 500 responses) were not logged
**After:** All API errors are logged with stack traces and context
Testing:
Verified by attempting to create a second user when onboarding is unavailable:
```curl
curl -i -X POST http://localhost:7474/api/auth/onboard -H "Content-Type: application/json" \
-d '{"username": "testuser2", "password": "test123"}'
```
This produced the expected error log with stack trace:
```shell
2024-11-16T12:38:27+01:00 ERR server error error="onboarding unavailable" stack=[...] status=503
```
> feat(http): add error logging for API responses

- .github/workflows/release.yml
- .goreleaser.yml
- ci.Dockerfile
- ciwindows.Dockerfile
- cmd/autobrr/main.go
default.pgo needs to be along side the unit being compiled at the time of this writing, which isn't great for general profiles being created. The file is intentionally named cpu.pprof, to denote that it needs to be statically added on the command as defualt.pgo isn't read from the current (present working) directory.
Committing binary profiling data to a git repository is just crazy (which is the present recommendation from the go team), hence the run-time generation as part of the pipeline. Tests are used as a kludge now to try and get more inlining, but this is the wrong approach in the future once more e2e comes into the tree.
> build(ci): implement PGO

- .github/workflows/trigger_docs_update.yml
Adds workflow to trigger docs update in autobrr.com when a new release is published.
We need to:
- Create PAT in autobrr/autobrr.com with `workflow` scope
- Add PAT as `DOCS_TOKEN` secret in this repo
> feat(ci): add workflow to trigger docs update on release

- internal/domain/client.go
- internal/domain/client_test.go
- internal/download_client/connection.go
- internal/download_client/service.go
Fix lint warning for url parse err handling.
> fix(downloadclient): qBittorrent url parse err handling

- internal/database/sqlite.go
Colons in filenames are not valid on Windows, which breaks the migration backups.
Fixes #1842
> fix(database): backup on windows bad filename

- go.mod
- go.sum
Update indirect dep `github.com/cilium/ebpf` to `v0.16.0` due to breaking Alpine builds.
> build(deps): bump indirect cilium/ebpf to v0.16.0

- .github/workflows/trigger_docs_update.yml
This commit adds the `workflow_dispatch` trigger to the Trigger Docs Update workflow, allowing manual triggering of the workflow in addition to the existing release trigger.
> build: add docs update workflow trigger

- internal/indexer/definitions/uploadcx.yaml
**We currently only support indexers with IRC announces.**
-  Do they have irc announce? Yes
-  Link to existing `autodl-irssi .tracker` file: NA
- Indexer name: Upload.cx
- Short name: ULCX
- URL: https://upload.cx
- Download link: https://upload.cx/torrents/24921.rsskey
Please provide 1-5 different announces. And change release titles for good measure. If they have tags like freeleech and internals etc make sure to get examples of those.
- TV: [upload.cx] - [Redacted] has uploaded [The Man in the High Castle S02 2160p AMZN WEB-DL DD+ 5.1 H.265-FLUX]. Grab it now! Category: [TV] Type: [WEB-DL] Resolution: [2160p] Size: [59 GiB] Freeleech: [100] Link: [https://upload.cx/torrents/25694]
- Movie: [upload.cx] - [Redacted] has uploaded [Sahara 2005 Open Matte 1080p BluRay REMUX AVC TrueHD …
> feat(indexers): add UploadCX

- internal/http/auth.go
- internal/http/encoder.go
This PR downgrades onboarding availability check responses from error to warning level. 
- Added StatusWarning method to encoder for non-critical responses
This is an improvement to the changes made in https://github.com/autobrr/autobrr/pull/1819
> fix(http): downgrade canOnboard check to warning log level

- internal/domain/macros.go
Some trackers add information about the release in the description. This change would allow the description to be available for Exec action and take decisions based on that.
> feat(macros): add Description

- internal/database/sqlite.go
Try to re-index when encountering errors from integrity check.
Related #1842
> fix(database): SQLite try reindexing on integrity check error

- internal/indexer/definitions/privatesilverscreen.yaml
Use `freeleechPercent` variable to capture freeleech percent.
> fix(indexers): PrivateSilverScreen freeleech parsing

- web/src/screens/settings/Feed.tsx
- web/src/screens/settings/Irc.tsx
fixes #1886 
This PR fixes the headless UI menus running out of bounce for the feed and IRC settings.
This has already been fixed for the filter menus and i haven't found any other menus with this bug on a quick look.
Old:
New:
> fix(web): feed and IRC menu out of bounce

- internal/domain/macros.go
- internal/domain/release.go
Add new macro `MetaIMDB` which contains IMDB id, only supported by PTP at this time.
> feat(macros): add `MetaIMDB`

- internal/indexer/definitions/animeworld.yaml
This PR implements the announce type feature for AnimeWorld.
There are 2 possibilities:
- `Neuer Upload` which are new releases and are mapped to NEW
- `Torrent vorgestellt` which are already uploaded releases getting applied a bonus and are mapped to PROMO
> feat(indexers): implement AnimeWorld announce types

- internal/database/list.go
Fixes an issue saving non-arr lists with Postgres.
Fixes #1903
> fix(lists): handle NULL clientID for non-arr lists on Postgres

- internal/indexer/definitions/fuzer.yaml
Parse the full category string.
Fixes #1919
> fix(indexers): Fuzer parse full category

- web/src/screens/settings/Releases.tsx
This PR fixes two typos in the titles for the duplicate release settings.
> fix(web): typos in duplicate release profile settings

- go.mod
- go.sum
update rtorrent pkg to support old xmlrpc-c and new tinyxml2 implementation of rtorrent v0.15.0.
Fixes #1921
> build(deps): bump autobrr/go-rtorrent to v1.12.0

- internal/indexer/definitions/myanonamouse.yaml
This PR changes the parsing of `VIP` on `MAM` to be captured by `releaseTags` which makes it easy to filter for or ignore with `Match Release Tags` and `Except Release Tags`.
This is backwards compatible thanks to the variable mapping which still sets freeleech if it's flagged as VIP.
Ref discussion https://github.com/autobrr/autobrr/discussions/1666
> feat(indexers): MAM filter VIP with release tags

- web/src/screens/settings/Irc.tsx
This PR fixes a cosmetic bug introduced by the tailwind v4 PR in the IRC network settings.
Old and ugly:
New and beautiful:
> fix(web): IRC network status gaps

- internal/list/process_list_anilist.go
- internal/list/title.go
- internal/list/title_test.go
This PR moves the AniList specific procressing to title.go to apply it to all lists.
All titles will now be filtered for symbols and the "Latin-1 Supplement" and "Latin Extended-A" unicode block.
Code comments have been added to get a better understanding of what is getting filtered.
All 30 tests pass with this change.
The test that has been altered is due to the test not honoring the processing done in process_list_anilist.go
@fabricionaweb if you have more tests that you wanna add, now is the time to do so.
Please leave this PR open until the release of the next minor version so enough tests can be added.
> refactor(lists): title character filtering

- internal/indexer/definitions/hdb.yaml
This PR adds support for the "Exclusive" tag in HDB's announces.
The string will get mapped to the `tags` var.
From what i can tell, there won't be a release that is Internal and Exclusive so that has not been considered in this solution.
https://regex101.com/r/7cJA1S/2
> feat(indexers): add HDB parse Exclusive as tag

- internal/indexer/definitions/myanonamouse.yaml
Updated the help text to include how to generate the session properly tied to the IP address that Autobrr is running from.
> docs(indexers): update MAM cookie help text

- internal/list/title.go
- internal/list/title_test.go
Refactored the title processing for lists to get rid of a lot of code duplication.
Also fixed an issue with `Add` logic to make sure we don't end up with multiple wildcards at the end of processed titles when `matchRelease` is set to `true`. Added a new test case for that as well.
> refactor(lists): title variation processing

- web/src/screens/filters/sections/Advanced.tsx
Normalize "Remember to tick" tooltips removing "below" because the switch is actually above.
> docs(filters): fix tooltips

- internal/list/process_list_plaintext.go
- web/src/forms/settings/ListForms.tsx
Add support to read plaintext lists from file on disk with URL as `file:///home/user/list.txt`.
> feat(lists): read Plaintext from file on disk

- internal/auth/oidc.go
Adds call to OIDC Userinfo endpoint to retrieve user claims. Merges these with ID Token claims, prioritizing Userinfo for attributes like `preferred_username`.
This ensures user details are correctly obtained even when the provider does not include them directly in the ID Token, resolving issues where the username defaulted to the 'sub' claim.
Tested with Pocket ID by commenting out claims from ID Token, and it correctly fetched from Userinfo endpoint.
Fixes #2013
> fix(oidc): fetch claims from Userinfo endpoint

- web/src/screens/filters/List.tsx
Shows a red warning on `/filters` if a filter is using an indexer in disabled state.
On hover it will list all indexers in disabled state.
> feat(filters): show disabled indexer warning

- internal/metrics/collector/irc.go
Plz see https://github.com/autobrr/autobrr/discussions/2035
Currently a channel is only considered enabled if it's enabled in the db.
However when you disable an IRC server, its channel remains enabled in the db but should be considered disabled in the metrics.
> fix(metrics): irc channel enabled gauge

- internal/domain/macros.go
- internal/domain/macros_test.go
Implements a template cache for macro parsing. Using ttlcache.
> feat(macros): implement template cache

- internal/http/auth.go
- internal/http/encoder.go
This PR changes the log level for the `onboarding unavailable` log message,
since we experienced an upsurge in support workload due to people asking about this warning.
> fix(http): change onboarding unavailable log level

- internal/domain/indexer.go
- internal/domain/indexer_test.go
- internal/domain/irc.go
- internal/domain/release.go
- internal/indexer/definitions/t66y.yaml
This adds supports for t66y.com (Caoliu Community) which is a forum aggregating mostly Chinese/Japanese adult content.
* Adds a new `T66y` indexer using IRC (Rizon.net on #t66y).
* Adds the ability for IRC indexer definitions to templatize `torrenthash` and `magneturi`.
* Adds tests.
The categories on the forum don't map to anything common/generic on the releases so they are kept to their original numeric form.
> feat(indexers): add T66y

- internal/domain/releasetags.go
- internal/domain/releasetags_test.go
- internal/indexer/indexer_test.go
Fix for #2045. Sets `HasLog` to true when `Log` is present in the announced release tags.
Added tests for the release in question.
> fix(macros): set HasLog when Log Score is missing in announce

- Dockerfile
- README.md
- config.toml
- docker-compose.yml
- internal/config/config.go
- internal/database/database.go
- internal/database/postgres.go
- internal/database/postgres_test.go
- internal/domain/config.go
Allow Postgres to connect over socket via a new config/env var or the a new env var `DATABASE_DSN` or `databaseDSN` config var.
If `DSN` is set it uses that, otherwise it builds a `DSN` with individual variables like before.
This PR also introduces the ability to read from for example docker secrets via env vars like `AUTOBRR__POSTGRES_PASSWORD_FILE` which points to a file. It will try to read the file and if it does not exist it will crash.
All existing ENV vars have support for a _FILE variant, and it's fully optional to use or not.
Reference #2053
> feat(database): connect postgres via socket and read config from env _FILE secrets

- web/src/screens/dashboard/ActivityTable.tsx
- web/src/screens/releases/ReleaseTable.tsx
Fixes an issue where the Activity and Release tables would not auto-update with new data unless the page was manually refreshed. The regression was introduced in commit 24648e45. The root cause is related to how the table detects data changes and how `useEffect` dependencies were structured after the incognito mode feature was added.
> fix(web): ensure release table auto-update

- .github/workflows/release.yml
Build goreleaser as snapshot during PRs to allow forks to build with GoReleaser Pro.
> build: goreleaser snapshot during pr builds

- internal/database/postgres_migrate.go
- internal/database/sqlite_migrate.go
- internal/indexer/definitions/rocket-hd.yaml
RocketHD will make a change to their IRC server and its announce channel this weekend. 
After this change, the IRC server requires authentication with a network/server password. 
Users will be able to obtain an IRC key on site which needs to be used as their IRC server password. 
A channel password or NickServ auth will no longer be required.
> feat(indexers): new IRC auth mechanism for RocketHD

- internal/database/sqlite_migrate.go
There is an error in the `sqlite_migrate.go` file for the `list` table where we create the 
`skip_clean_sanitize` column at line 1818 and then we alter the table later 
at line 2003 adding the `skip_clean_sanitize` column again which result in an error.
The proposed fix is to not create the `skip_clean_sanitize` column in the initial creation of the table
and add the `skip_clean_sanitize` column later on.
`postgres_migrate.go` does not create the `skip_clean_sanitize` in the first place 
and adds the `skip_clean_sanitize` column later on, like proposed in the SQLite fix.
So the PostgreSQL migrations do not need to be fixed.
Migrations from 1.53.1 to develop have been tested with SQLite and PostgreSQL and are working.
fixes #2095 
Note: 
Issue says he upgraded from v1.52.1 but we don't …
> fix(database): duplicate `skip_clean_sanitize` column

- internal/domain/macros.go
Add Cookie to Macros for the few indexers that use it. Can be used for upcoming cross-seed features.
> feat(macros): add Cookie

- internal/release/service.go
Changed warning log level to debug for "no active filters found for indexer" messages to reduce noise when indexers are monitored but not actively filtered. Also removed redundant return statement.
Re: #2121
> fix(release): reduce log spam for indexers without active filters

- CONTRIBUTING.md
- Makefile
This is needed to build docker images for other platforms (I'm on Apple ARM for instance). This will build the image for both arm64 and amd64. Docker and container registries seamlessly support multiple archs for the same image tag, so if you build both, it will automatically select the correct one to run. Similarly, if you push the image tag, it will push up both and when you pull, it will select the correct arch for the target system.
> build(make): add build/dockerx for cross platform docker builds

- internal/indexer/definitions/seedpool.yaml
This PR updates the seedpool regex pattern to allow optional trailing whitespace due to inconsistencies with announce bots, specifically with the seedpool internal release announces.
Strings like:
`【 Movie 】 ... ჻ iNTERNAL `
previously failed to match due to the trailing space. This change fixes that.
- Added `\s*` at the end of the regex pattern in internal/indexer/definitions/seedpool.yaml
> fix(indexers): SeedPool internal announces

- internal/indexer/service.go
The Test API button for indexers would send and use the `<redacted>` value if form was saved before clicking the button.
> fix(indexers): Test API sends key as redacted if saved

- internal/indexer/definitions/hdb.yaml
* [Reported on Discord](https://discord.com/channels/881212911849209957/881967548143403058/1420817396741963887)
Fix the HDB announce regex to capture both Internal and Exclusive.
https://regex101.com/r/6iVKmC/1
* HDB indexer definition regex
> fix(indexers): HDB parse announce with Internal and Exclusive correctly
