web/src/domain/interfaces.ts
web/src/screens/Filters.tsx

Add freeleech toggle in filters view.
And refactor advanced tab while we're at it.

Filters: freeleech toggle

---

cmd/autobrrctl/main.go
internal/database/user.go

Add feature to change password with `autobrrctl`.

Feat: autobrrctl change-password

---

cmd/autobrrctl/main.go
internal/database/migrate.go
internal/database/user.go

Fix `autobrrctl` change-password for user.

Fix: autobrrctl change password for user

---

go.mod
go.sum
internal/action/deluge.go
internal/action/service.go
internal/announce/parse.go
internal/domain/action.go
internal/domain/client.go
internal/download_client/service.go
pkg/releaseinfo/parser.go
pkg/releaseinfo/parser_test.go
web/src/components/FilterActionList.tsx
web/src/components/inputs/SelectField.tsx
web/src/components/inputs/index.ts
web/src/domain/constants.ts
web/src/domain/interfaces.ts
web/src/forms/filters/FilterActionAddForm.tsx
web/src/forms/filters/FilterActionUpdateForm.tsx
web/src/forms/settings/DownloadClientAddForm.tsx
web/src/screens/settings/DownloadClient.tsx

Add Deluge as download client. Supports both V1 and V2 as separate types. 
Might refactor into one single action type in the future.

Feature: Deluge download client

---

web/src/screens/Filters.tsx

Fixes wrong field for `match_release_groups` on filters.

Fix: wrong field match_release_groups

---

internal/http/auth.go

Feat: Add secure flags to cookie

---

internal/indexer/definitions/beyondhd.yaml
internal/indexer/definitions/btn.yaml
internal/indexer/definitions/filelist.yaml
internal/indexer/definitions/gazellegames.yaml
internal/indexer/definitions/hd-torrents.yaml
internal/indexer/definitions/iptorrents.yaml
internal/indexer/definitions/nebulance.yaml
internal/indexer/definitions/orpheus.yaml
internal/indexer/definitions/ptp.yaml
internal/indexer/definitions/red.yaml
internal/indexer/definitions/torrentleech.yaml
internal/indexer/definitions/uhdbits.yaml

Go through indexer definitions and check regexes.

Refactor: indexer definitions

---

internal/action/lidarr.go
internal/action/radarr.go
internal/action/sonarr.go
internal/irc/handler.go
pkg/lidarr/client.go
pkg/lidarr/lidarr.go
pkg/lidarr/lidarr_test.go
pkg/radarr/client.go
pkg/radarr/radarr.go
pkg/radarr/radarr_test.go
pkg/sonarr/client.go
pkg/sonarr/sonarr.go
pkg/sonarr/sonarr_test.go

Fix: date time for release push to arr's and improve erorrs.

Fix: date time for release push to arr's and improve erorrs

---

internal/database/download_client.go
web/src/domain/interfaces.ts
web/src/forms/settings/downloadclient/shared.tsx
web/src/screens/settings/DownloadClient.tsx

Improves logging and fixes update of download client.
Use password fields in UI to hide secrets.

Fix: update download client

---

web/package.json
web/src/components/Layout.tsx
web/src/components/notifications/Toast.tsx
web/src/forms/filters/FilterActionAddForm.tsx
web/src/forms/filters/FilterActionUpdateForm.tsx
web/src/forms/filters/FilterAddForm.tsx
web/src/forms/settings/IndexerAddForm.tsx
web/src/forms/settings/IndexerUpdateForm.tsx
web/src/forms/settings/IrcNetworkAddForm.tsx
web/src/forms/settings/IrcNetworkUpdateForm.tsx
web/src/forms/settings/downloadclient/DownloadClientAddForm.tsx
web/src/forms/settings/downloadclient/DownloadClientUpdateForm.tsx
web/src/index.css
web/src/screens/Filters.tsx
web/tailwind.config.js

**Major Changes**
1.  Add react-hot-toast as a new package
1. Add new `Toast` component used for notifications
1. Add new notifications to almost all components and usages beside `Actions` in `Filters`
**Minor Changes**
1. Fix validation for `nickserv.account` and `port`
1. Fix update issue when port isn't required (now required by default)

Feature: Toast Notification System

---

cmd/autobrr/main.go
go.mod
go.sum
internal/http/server.go
internal/irc/handler.go
internal/logger/logger.go
internal/logger/ssehook.go
web/public/index.html
web/src/api/APIClient.ts
web/src/forms/settings/IrcNetworkUpdateForm.tsx
web/src/screens/Base.tsx
web/src/screens/Logs.tsx
web/src/utils/utils.ts
web/yarn.lock

Tail live logs in UI.
Backend logger implements a hook to send log messages over SSE (server-sent-events) to the frontend to tail live logs.
No support for older logs, only new.

Feature: Tail live logs

---

internal/indexer/definitions/ptp.yaml

Match case without `by Director`.

Fix(indexers): ptp regex pattern

---

.github/workflows/release.yml
Dockerfile

Build both `autobrr` and `autobrrctl` in Dockerfile, and push to `ghcr.io`/GitHub packages.

build: docker build autobrrctl and push to ghcr

---

web/src/components/inputs/MultiSelectField.tsx
web/src/components/inputs/wide/NumberField.tsx
web/src/screens/filters/inputs/MultiSelect.tsx
web/yarn.lock

Update web dependencies to get rid of vulnerable packages.

fix: Update web deps and fix imports

---

internal/indexer/definitions/trancetraffic.yaml

Add TT. Second one using multi-line irc parsing.

Indexers: Add TranceTraffic

---

internal/database/release.go
internal/domain/release.go
internal/http/release.go
internal/release/service.go
web/src/domain/interfaces.ts
web/src/screens/Base.tsx
web/src/screens/Releases.tsx

Create a separate page for releases with filtering.
- Pagination
- Filters
- Search?
Filters:
- Order by [time, indexer]
- Indexer
- Status

Feature: List releases

---

internal/database/filter.go
internal/domain/filter.go
internal/filter/service.go
internal/http/filter.go
web/src/api/APIClient.ts
web/src/screens/filters/list.tsx

Toggle on Filter list now works and sends a request to the backend to update enabled.

Fix: Filter list toggle

---

internal/announce/announce.go
internal/indexer/definitions/torrentseeds.yaml

Regex was not working with wrong URL.
Updated it and tested, it is working

Indexers: Update TorrentSeeds for new site

---

internal/domain/release.go
internal/domain/release_test.go

What: Mixed up true/false check for check of `except_releases`.

Fix(filters): Check except_releases properly

---

.goreleaser.yml
cmd/autobrr/main.go
go.mod
go.sum
internal/http/config.go
internal/http/server.go
internal/logger/logger.go
web/src/domain/interfaces.ts
web/src/screens/settings/Application.tsx

Inject `version`, `commit` and `date` during build and display in ui. Only currently available when built with GoReleaser.

Feature: Set and display version info

---

internal/irc/handler.go

Since some channels can be different case, make it lower case before compare.

Fix: Make valid channels check lowercase

---

internal/database/filter.go
internal/database/release.go
internal/domain/filter.go

With the recent change of database driver we now don't need to do extra datetime handling.

Fix: Date parsing

---

web/src/screens/Dashboard.tsx
web/src/screens/Releases.tsx
web/src/screens/filters/list.tsx

Make filter name clickable/link to filter edit.

Feature: clickable filter name link

---

internal/database/filter.go
internal/database/migrate.go
internal/domain/filter.go
internal/domain/release.go
internal/domain/release_test.go
web/src/components/inputs/select.tsx
web/src/domain/constants.ts
web/src/domain/interfaces.ts
web/src/index.css
web/src/screens/filters/details.tsx

Add filtering for HDR. Match and ignore.
Resolves #85

Feature: Add HDR filtering

---

.github/workflows/docker.yml
.github/workflows/release.yml
Dockerfile

Split workflow into two: Go releaser and Docker.

Build: Update and split gh workflows

---

internal/database/filter.go

Sort filters list by name ASC.

Feat(filters): sort list by name

---

README.md
internal/indexer/definitions/torrentdb.yaml

Have been testing and working both with Freeleech and without.

Indexers: Add TorrentDb

---

README.md
internal/indexer/definitions/hdb.yaml

Tested it briefly and it should work now:
```
2022-01-23T04:47:56+07:00 DBG irc.p2p-network.net: #hdbits.announce midgards: New Torrent: Squid Game S01 2160p WEB-DL DD+5.1 HDR HEVC-Telly - Type: TV (HEVC, WEB-DL) - Uploaded by: Anonymous - Size: 52.83 GiB - https://hdbits.org/details.php?id=600030&hit=1
2022-01-23T04:47:56+07:00 TRC announce: queued line: New Torrent: Squid Game S01 2160p WEB-DL DD+5.1 HDR HEVC-Telly - Type: TV (HEVC, WEB-DL) - Uploaded by: Anonymous - Size: 52.83 GiB - https://hdbits.org/details.php?id=600030&hit=1
2022-01-23T04:47:56+07:00 TRC announce: process line: New Torrent: Squid Game S01 2160p WEB-DL DD+5.1 HDR HEVC-Telly - Type: TV (HEVC, WEB-DL) - Uploaded by: Anonymous - Size: 52.83 GiB - https://hdbits.org/details.php?id=600030&hit=1
2022-01-23T04:47:56+07:00 …
```

Indexers: Add HDBits

---

internal/action/lidarr.go
internal/action/qbittorrent.go
internal/action/radarr.go
internal/action/run.go
internal/action/sonarr.go
internal/domain/release.go
internal/events/subscribers.go
pkg/lidarr/lidarr.go
pkg/lidarr/lidarr_test.go
pkg/radarr/radarr.go
pkg/radarr/radarr_test.go
pkg/sonarr/sonarr.go
pkg/sonarr/sonarr_test.go
web/src/screens/Releases.tsx
web/src/types/Release.d.ts
web/src/utils/index.ts

Correctly return and display push status and rejections from the arr's.

Feat: return action status from arrs

---

internal/download_client/connection.go
pkg/lidarr/client.go
pkg/radarr/client.go
pkg/radarr/radarr_test.go
pkg/sonarr/client.go
web/src/components/inputs/input_wide.tsx
web/src/forms/settings/DownloadClientForms.tsx

What:
Fixes parsing of download client addresses to allow for trailing slashes etc.

refactor: download client addr parsing

---

internal/indexer/definitions/digitalcore.yaml

Indexer: Add DigitalCore

---

web/src/screens/filters/list.tsx

fix: filters list wrong status

---

web/src/components/panels/index.tsx
web/src/forms/settings/DownloadClientForms.tsx

Change remove button text to white when using dark theme.

fix: web correct remove button colors

---

web/src/screens/Settings.tsx

Set uniform color for icon in settings menu.

fix: web settings menu icon color

---

.gitignore
web/package.json
web/src/App.tsx
web/src/api/APIClient.ts
web/src/components/inputs/common.tsx
web/src/components/inputs/input.tsx
web/src/components/inputs/input_wide.tsx
web/src/components/inputs/select.tsx
web/src/components/inputs/switch.tsx
web/src/domain/react-table-config.d.ts
web/src/forms/filters/FilterAddForm.tsx
web/src/forms/settings/DownloadClientForms.tsx
web/src/forms/settings/IndexerForms.tsx
web/src/forms/settings/IrcForms.tsx
web/src/hooks/hooks.ts
web/src/index.tsx
web/src/reportWebVitals.ts
web/src/screens/Dashboard.tsx
web/src/screens/Logs.tsx
web/src/screens/Releases.tsx
web/src/screens/Settings.tsx
web/src/screens/auth/logout.tsx
web/src/screens/filters/details.tsx
web/src/screens/filters/list.tsx
web/src/screens/settings/Action.tsx
web/src/screens/settings/DownloadClient.tsx
web/src/screens/settings/Indexer.tsx
web/src/screens/settings/RegexPlayground.tsx
web/src/utils/index.ts

ESLint was added, some imports were cleaned up/reorganized along the way. Also, .gitignore was updated not to include some rather useless artefacts.

Feature: Added ESLint and cleaned up code as necessary

---

internal/action/qbittorrent.go
pkg/qbittorrent/methods.go

Minor changes to qbit re-announce to try and make it work better.

fix: improve qbit re-announce

---

internal/action/qbittorrent.go
internal/action/run.go
internal/domain/release.go
internal/filter/service.go
internal/release/service.go

Simplify some logic for downloading files.
* Save tmpfile on release
* Save size on release
* Save hash on release

refactor: download torrent files

---

web/src/screens/Base.tsx

fix(Base): Added missing transition-colors property to the user dropdown pill in the header component.

fix(Base): Added missing transition-colors property

---

web/src/components/inputs/input.tsx
web/src/components/inputs/switch.tsx
web/src/components/modals/index.tsx
web/src/forms/filters/FilterAddForm.tsx
web/src/index.css
web/src/screens/Base.tsx
web/src/screens/Logs.tsx
web/src/screens/filters/details.tsx
web/src/screens/filters/list.tsx

fix(react-multi-select-component): adjusted the component to fit in with other components when comparing across multiple browsers. (where firefox consistently handles pixels and rem's, chromium doesn't agree).
refactor(input): removed shadow from input components to match react-multi-select-component look where needed.
refactor(SwitchGroup): added a small top margin for a less dense look. cleaned up surrounding code.
refactor(DeleteModal): adjusted the background color to fit more nicely across dark/light themes. made the exclamation icon bigger and removed the circle container.
refactor(Logs): adjusted text color on the light theme. cleaned up the code.
refactor(FilterAddForm): adapted to conform with the changes.
feat(FilterItemDropdown): added a dropdown component to the filter list as …

feat(FilterItemDropdown): added a filter dropdown component from #26

---

README.md
internal/domain/release.go
internal/indexer/definitions/danishbytes.yaml

Add support for danishbytes and improve parsing of freeleech vars and parse resolution.

feat(indexers): add danishbytes

---

README.md
internal/indexer/definitions/revolutiontt.yaml

Add support for `RevolutionTT`.

Indexer: Add RevolutionTT

---

README.md
internal/indexer/definitions/norbits.yaml

Indexers: Add Norbits

---

pkg/qbittorrent/client.go

Extend timeout and add retry with small backoff for qbit requests.
Fixes #154

feat: qbit add retry and extend timeout

---

.github/workflows/docker.yml
Dockerfile
Makefile

Set `version` and `commit` during docker build.
Resolves #162

build: set version in docker build

---

.github/workflows/docker.yml
Dockerfile

Fix docker build args for version etc.

Fix(build): Actions docker build-args

---

web/src/components/inputs/input_wide.tsx
web/src/forms/settings/IndexerForms.tsx

* Fix the default values on the add indexer panel after selecting n indexer.
* Reset form values on indexer change
* Password field add padding to eye icon

fix: indexer add default values

---

internal/database/filter.go
internal/domain/filter.go
internal/filter/service.go
internal/http/filter.go
web/src/api/APIClient.ts
web/src/screens/filters/list.tsx

Add the ability to duplicate filters.

feat(filters): duplicate

---

internal/database/release.go
internal/domain/release.go
internal/http/encoder.go
internal/http/release.go
internal/release/service.go
web/src/api/APIClient.ts
web/src/screens/Settings.tsx
web/src/screens/settings/Releases.tsx

Add button to delete all releases from the ui.
**Future improvements:**
* Delete older than X days
Resolves #123

feat: delete all releases from ui

---

internal/http/encoder.go
internal/http/irc.go
internal/http/release.go
web/src/api/APIClient.ts
web/src/forms/settings/IndexerForms.tsx
web/src/types/Irc.d.ts

A faulty Date (`0`) was being sent and failed to decode the json into a struct. And thanks to no error or log returned hard to grasp why. 
Fixes #176

fix: No IRC network created when adding a new indexer

---

cmd/autobrr/main.go
config.toml
internal/config/config.go
internal/domain/config.go
internal/indexer/service.go
test/definitions/mock.yaml

Add support to load custom definitions from location on disk. Makes local development easier.

feat(indexers): load custom definitions

---

internal/irc/handler.go
internal/irc/service.go

Run `NickServ IDENTIFY` with password only.

fix(irc): run nickserv identify with password only

---

internal/irc/handler.go

Increase sleep before join to give more time for nickserv and bots to respond.

fix(irc): increase sleep pre join

---

internal/irc/handler.go

Fix the command for join channel to properly use password if set.

fix(irc): irc join cmd channel with password

---

internal/irc/handler.go

Allow to join other channels than only those in definitions, to allow for idling for bonus etc.

feat(irc): allow other channels for idle

---

internal/domain/release.go

Fix some of the release parsing/extracting and make it case-insensitive for badly named releases.

fix(releases): parse case insensitive

---

web/src/screens/filters/details.tsx
web/src/screens/filters/list.tsx
web/src/screens/releases/ReleaseTable.tsx

Refetch filters list on update.

fix(filters): refetch on update

---

internal/action/run.go
internal/domain/release.go
internal/filter/service.go

Add cookie support for download of files.

feat(indexers): add cookie support

---

internal/http/auth.go
internal/http/middleware.go
web/src/App.tsx
web/src/api/APIClient.ts

Redirect to `login` on expired cookie session.
Fixes #201

feat(web): redirect to login on expired cookie

---

README.md
internal/indexer/definitions/torrentnetwork.yaml

Indexers add tnetwork

---

cmd/autobrr/main.go
cmd/autobrrctl/main.go
internal/action/service.go
internal/database/action.go
internal/database/database.go
internal/database/download_client.go
internal/database/filter.go
internal/database/indexer.go
internal/database/irc.go
internal/database/migrate.go
internal/database/postgres.go
internal/database/release.go
internal/database/sqlite.go
internal/database/user.go
internal/domain/action.go
internal/domain/client.go
internal/domain/indexer.go
internal/domain/irc.go
internal/domain/release.go
internal/domain/user.go
internal/download_client/service.go
internal/filter/service.go
internal/http/action.go
internal/http/download_client.go
internal/http/indexer.go
internal/http/irc.go
internal/http/release.go
internal/indexer/service.go
internal/irc/service.go
internal/release/service.go

Add postgres support.
Quite a major refactor of the entire database layer, but made some great improvements in the refactor. It's now using Squirrel for most queries which is a nice and simple query builder, and it makes it easy to support both SQLite and Postgres.

Feature: Postgres support

---

internal/action/run.go
internal/notification/discord.go

fix(notifications): send error and reject events

---

internal/action/run.go
internal/action/whisparr.go
internal/domain/action.go
internal/domain/client.go
internal/download_client/connection.go
pkg/whisparr/client.go
pkg/whisparr/whisparr.go
web/src/domain/constants.ts
web/src/forms/settings/DownloadClientForms.tsx
web/src/screens/filters/details.tsx
web/src/types/Download.d.ts

feat(clients): add whisparr

---

internal/indexer/definitions/emp.yaml

Change to correct irc network.

fix(indexers): emp change irc network

---

internal/database/user.go

Fix issue with creating new users.

fix(users): use insert instead of update

---

internal/announce/service.go

To prevent saving all releases in the database, only save after a match. This will allow for saving rejections from starr apps as well.
* Create a settings option to allow to save all releases

fix(filter): save only matched releases

---

internal/auth/service.go
internal/database/user.go
internal/domain/user.go
internal/http/auth.go
internal/user/service.go
web/src/App.tsx
web/src/api/APIClient.ts
web/src/components/inputs/input.tsx
web/src/screens/auth/login.tsx
web/src/screens/auth/logout.tsx
web/src/screens/auth/onboarding.tsx

This PR makes it easier for new users to create an account without the need to use autobrrctl.

feat: add ability to create an account via the webui

---

internal/database/sqlite.go

Disable sqlite foreign key check.

fix(database): sqlite disable foreign key check

---

internal/database/indexer.go

Get api keys from indexer repo findByFilterID.

fix(indexer): repo get api keys in find

---

internal/database/action.go

Fixes ordering of action data from fetch.

fix(actions): repo ordering of query args

---

web/src/screens/Logs.tsx
web/src/utils/Context.ts

enhancement(frontend/logs): added ability to customize logs view

---

README.md
internal/indexer/definitions/myanonamouse.yaml

Add MAM.
**Need to verify the regex and announce.**

feat(indexers): add mam

---

.github/workflows/docker.yml

build: run ci and build on pr

---

pkg/lidarr/client.go
pkg/lidarr/lidarr.go
pkg/radarr/client.go
pkg/radarr/radarr.go
pkg/radarr/radarr_test.go
pkg/radarr/testdata/release_push_parse_error.json
pkg/sonarr/client.go
pkg/sonarr/sonarr.go

Improve errors and logging for starr actions.

feat(download-clients): improve errors for starr apps

---

.github/workflows/docker.yml

Add `push: true` to docker workflow.

build(actions): update docker workflow

---

internal/domain/filter.go
internal/domain/filter_test.go
web/src/screens/filters/details.tsx

Add regex support for filters fields `match release` and `except release`.

feat(filters): add regex support

---

internal/domain/feed.go

Pass `indexer_id` from request when creating indexer.

fix(feeds): create with indexer id

---

internal/action/qbittorrent.go
internal/database/action.go
internal/database/migrate.go
internal/domain/action.go
web/src/components/inputs/switch.tsx
web/src/screens/filters/details.tsx
web/src/types/Filter.d.ts

Make the re-announce options settable in the action to customize intervals or disable it completely.

feat(download-clients): qbt set re-announce opts

---

internal/database/migrate.go

fix(db): bad migration

---

internal/action/qbittorrent.go
internal/database/action.go
internal/database/migrate.go
internal/database/utils.go
internal/domain/action.go
web/src/components/inputs/input.tsx
web/src/screens/filters/details.tsx
web/src/types/Filter.d.ts

Add ratio and seed time limit to qbittorrent action.
Resolves #247

feat(actions): qbit set ratio and seed time limits

---

internal/domain/filter.go
internal/domain/filter_test.go

Support comma separated list for regex `match releases` and `except releases`.

feat(filters): regex match release support list

---

web/src/components/debug.tsx
web/src/screens/Settings.tsx
web/src/screens/filters/details.tsx
web/src/utils/index.ts

fix(components/Debug): added overflow handling for smaller screens (or for long lines)
enhancement(settings/SidebarNav): shortened vertical padding from 24px to 8px
fix(filters/FilterDetails): fixed FilterDetails component to behave properly with mobile devices and made it consistent with the desktop UI
chore: cleaned up unnecessary code

web: mobile improvements

---

internal/announce/announce.go
internal/domain/release.go
internal/http/indexer.go
internal/indexer/service.go
internal/irc/handler.go
web/src/forms/settings/IndexerForms.tsx

Store indexerDefinition on pointer to have access to potentially changed data on reload.

fix(indexers-irc): reload config on restart

---

internal/database/filter.go
internal/database/migrate.go
internal/database/release.go
internal/domain/filter.go
internal/domain/filter_test.go
internal/filter/service.go
web/src/components/inputs/select.tsx
web/src/domain/constants.ts
web/src/screens/filters/details.tsx
web/src/types/Filter.d.ts

Add download limits to filters. `Max 1 per hour`.

feat(filters): add download limits

---

internal/irc/handler.go

refactor(irc): cleanup logging

---

internal/indexer/definitions/bit-hdtv.yaml

Still testing. Progress towards https://github.com/autobrr/autobrr/issues/1
Note: there's a fixed password on the channel, defaulting it publicly is disallowed.

feat(indexers): add bit-hdtv

---

internal/indexer/definitions/acidlounge.yaml

Still testing. Progress towards https://github.com/autobrr/autobrr/issues/1

feat(indexers): add AL

---

web/package.json
web/src/domain/react-table-config.d.ts
web/src/screens/Logs.tsx

- added log searching (case insensitive needle-in-haystack matching) with 200ms debouncing
- fixed parent container not to push the page further down, rather to overflow and show a scrollbar appropriately
- switched to showing time, instead of date + time
closes https://github.com/autobrr/autobrr/issues/232

enhancement(web/logs): improved functionality

---

web/yarn.lock

fix(deps): update yarn lock

---

internal/database/irc.go
internal/domain/irc.go
internal/irc/service.go

Append invite command on save for existing networks.
Fixes #99

fix(irc): append invite command on save

---

internal/indexer/definitions/pussytorrents.yaml

Work towards https://github.com/autobrr/autobrr/issues/1
Requested by x

 feat(indexers): add PT

---

web/src/components/data-table/Cells.tsx
web/src/screens/filters/details.tsx
web/src/screens/releases/Filters.tsx
web/src/screens/releases/ReleaseTable.tsx
web/src/screens/settings/DownloadClient.tsx

fix(ListboxFilter): Added z-index in order to properly render dropdown box.
fix(ReleaseTable): Added flex-direction: column to wrap on mobile devices (otherwise it's set to row)
feat(DownloadClientSettingsListItem): Made it possible to toggle client state directly, without opening the update form.

fix: mobile ux improvements

---

internal/database/filter.go

Fix postgres query for filter limits.

fix(filters): postgres dl limits check

---

internal/indexer/service.go

fix(indexers): don't die on failed load of custom-definitions

---

internal/database/migrate.go

Optimize indexes to speedup queries related to releases.

feature(releases): optimize database indexes

---

web/src/components/alerts/ErrorPage.tsx
web/src/screens/auth/login.tsx
web/src/screens/auth/logout.tsx

chore(ErrorPage): clean up code, fix typo
fix(Logout): replace /logout URL after logging out to /

fix(web): correctly replace logout url

---

internal/http/indexer.go
internal/indexer/service.go

Fixes the setup and duplicates torznab items in the indexer list.
Fixes #312

fix(indexers): duplicates in list

---

go.mod
go.sum
internal/indexer/service.go
web/src/forms/settings/IndexerForms.tsx

Set mappedIndexers on store and update.
Related #317

fix(indexers): indexers store and update

---

web/src/api/APIClient.ts

Fallback to login instead of showing scare big red error.

fix(web): auth fallback to login instead of error

---

internal/indexer/service.go

Updating of torznab indexers did not work.

fix(indexers): torznab update not working

---

internal/action/macros.go

Would help for some workflows - or may be it is just me.

feat(macros): add FilterName

---

internal/action/run.go
internal/database/migrate.go
internal/database/release.go
internal/domain/release.go
web/src/components/data-table/Cells.tsx
web/src/components/tooltips/Tooltip.tsx
web/src/screens/releases/ReleaseTable.tsx
web/src/types/Release.d.ts

Add client and filter to release action status popup on releases list.

feat(releases): action status show filter and client

---

internal/database/postgres_migrate.go
internal/database/sqlite_migrate.go

Missing types for latest migration.

fix(database): migration missing types

---

internal/database/feed_cache.go
internal/domain/feed.go
internal/feed/service.go
internal/feed/torznab.go
internal/indexer/service.go
internal/release/service.go

Fully delete and update everything needed.

fix(feeds): torznab update and delete

---

internal/indexer/definitions/pbay.yaml

Work towards that PB request.  #1

feat(indexers): add PB

---

go.mod
go.sum
internal/action/run.go
internal/action/transmission.go
internal/domain/action.go
internal/domain/client.go
internal/download_client/connection.go
web/src/domain/constants.ts
web/src/forms/settings/DownloadClientForms.tsx
web/src/screens/filters/details.tsx
web/src/types/Download.d.ts

Add support for Transmission as download client.

feat(download-clients): add Transmission

---

internal/action/run.go

https://github.com/autobrr/autobrr/issues/349
Iam no Go developer, please review

feat(actions): watch dir create folder if not exists

---

internal/irc/handler.go

Fix logic error in connect for joins.

fix(irc): connect join logic error

---

internal/irc/handler.go

This PR changes the behavoir of how autobrr handles invites to irc channels.
Previously it would join on all invites but this could be abused. 
Now it does a `validChannel` check. A channel is considered valid if it's:
1. Defined in the indexer definition
2. A user have added an additional channel to the network
If a channel isn't considered valid, it will `PART` that channel.
The additional channel can be used for idling etc.
Fixes #268

feat(irc): only join valid channels from invite

---

cmd/autobrrctl/main.go
internal/database/database.go

Logger was missing which caused an imediate crash.

fix(autobrrctl): add missing logger

---

internal/action/qbittorrent.go
pkg/qbittorrent/client.go
pkg/qbittorrent/methods.go

in https://github.com/autobrr/autobrr/pull/344 the client was changed from storing a pointer to a full copy of the client.  This results in state not changing when the value is taken from the client. As the login presently happens after the struct copy, this results in the first push being successful, and subsequent pushes silently failing.
This is a speculative fix as there's not much state to maintain after the login.

fix(qbittorrent): remove client cache

---

.github/workflows/docker.yml
.github/workflows/release.yml

Upload binary artifacts on PR runs.

build: pr upload binary artifacts

---

internal/action/deluge.go

During the last big refactor of actions the download file and check rules for deluge 2 got lost.

fix(actions): deluge v2 download file and check rules

---

internal/domain/release.go
internal/domain/releasetags.go
internal/domain/releasetags_test.go
internal/indexer/definitions/btn.yaml

Improve parsing of BTN announces to get `Origin` and `Title`.

feat(indexers): btn improve parsing

---

internal/indexer/definitions/emp.yaml

Fix parsing of url for match url.

fix(indexers): emp parse pattern id

---

internal/indexer/definitions/subsplease.yaml

feat(indexers): add subsplease

---

internal/indexer/definitions/retroflix.yaml

feat(indexers): add RetroFlix

---

internal/indexer/definitions/immortalseed.yaml

feat(indexers): add ImmortalSeed

---

internal/indexer/definitions/immortalseed.yaml

fix(indexers): immortalseed settings parse

---

internal/indexer/definitions/hd-space.yaml

feat(indexers): add HD-Space

---

internal/indexer/definitions/torrentsyndikat.yaml

Switched to tags to filter by announced tags.

feat(indexers): torrentsyndikat change releaseTags to tags

---

internal/database/filter.go
internal/database/postgres_migrate.go
internal/database/sqlite_migrate.go
internal/domain/filter.go
internal/domain/filter_test.go
internal/domain/releasetags.go
web/src/screens/filters/details.tsx
web/src/types/Filter.d.ts

feat(filters): add except origins

---

internal/indexer/definitions/nebulance.yaml

* Set tls to true
* Improve parsing
* Add invite command

feat(indexers): nbl set tls and improve parsing

---

go.mod
go.sum
internal/domain/irc.go
internal/irc/handler.go
internal/irc/service.go
web/src/screens/settings/Irc.tsx
web/src/types/Irc.d.ts

This might be overkill but the pipeline has been made event driven. I've tested on a couple networks, and bouncing nicks / connections brings it back every time. creating the a different branch from https://github.com/autobrr/autobrr/pull/398 because it's pretty intrusive (and I didn't apply the GUI changes).

fix(irc): rewrite handler pipeline

---

internal/domain/release.go
internal/domain/release_test.go

feat(indexers): mam parse vip as freeleech

---

internal/database/filter.go
internal/domain/filter.go
internal/filter/service.go
internal/http/filter.go

Support partial update of only passed values.
Useful for regbrr and arrbrr scripts.

feat(filters): support partial update

---

internal/indexer/definitions/red.yaml

fixes https://github.com/autobrr/autobrr/issues/412

fix(indexers): red grab torrent id

---

.dockerignore
internal/api/service.go
internal/config/config.go

Fix the config container detection to also check for `.dockerenv` and set `host` in the config accordingly.

fix(config): improve container detection

---

internal/domain/filter.go
internal/domain/filter_test.go

Check `match other` and `except other`.

fix(filters): check `match other` and `except other`

---

pkg/qbittorrent/domain.go
pkg/qbittorrent/methods.go

https://www.youtube.com/watch?v=JxPj3GAYYZ0

feat(qbit): implement errored

---

internal/domain/macros.go

fixes https://github.com/autobrr/autobrr/issues/445

feat(macros): implement size

---

internal/indexer/definitions/oppaitime.yaml

Add OppaiTIme. 
Reference #330 and #1

feat(indexers): add OppaiTime

---

internal/indexer/definitions/polishtracker.yaml

Add PolishTracker
References #1

feat(indexers): add PolishTracker

---

internal/indexer/definitions/polishsource.yaml

Add PolishSource.
References #1

feat(indexers): add PolishSource

---

internal/indexer/definitions/scenehd.yaml

feat(indexers): add SceneHD

---

internal/indexer/definitions/xspeeds.yaml

feat(indexers): add XSpeeds

---

internal/indexer/definitions/btfiles.yaml

feat(indexers): add BitTorrentFiles

---

internal/indexer/definitions/speedapp.yaml

feat(indexers): add SpeedApp

---

internal/indexer/definitions/btfiles.yaml
internal/indexer/definitions/scenehd.yaml
internal/indexer/definitions/xspeeds.yaml

Properly escape regex patterns for new indexers.

fix(indexers): properly escape regex patterns

---

web/src/screens/filters/details.tsx

First PR ever - be gentle if I made a mistake in creating a pull request!

fix(web): fix artist placeholder typo in music filters

---

internal/domain/release.go
internal/domain/release_test.go

Improve tags parsing.
Fixes #437

fix(releases): improve tags parsing

---

internal/database/notification.go
internal/domain/notification.go
internal/notification/notifiarr.go
internal/notification/service.go
web/src/domain/constants.ts
web/src/forms/settings/NotificationForms.tsx
web/src/screens/settings/Notifications.tsx
web/src/types/Notification.d.ts

Add support for Notifiarr natively.

feat(notifications): add Notifiarr support

---

internal/database/filter.go
internal/domain/filter.go
internal/filter/service.go
internal/http/filter.go
web/src/api/APIClient.ts
web/src/screens/filters/details.tsx
web/src/screens/filters/list.tsx

Improve listview of Filters in the ui with 
* filtering for indexer
* Sort by Name and Priority ASC DESC
* Show only enabled, disabled or all filters
* Highlight filters with missing actions or indexers
* Shorten indexer list to only show 2 with `+2` for two more
* Show priority

feat(filters): improve list view with filtering

---

web/src/screens/filters/action.tsx

Just fixing the label, nothing to change on the backend.

fix(actions): qbit seedtime minutes instead of seconds

---

web/src/components/inputs/text.tsx
web/src/components/panels/index.tsx
web/src/forms/settings/FeedForms.tsx
web/src/forms/settings/NotificationForms.tsx
web/src/screens/Base.tsx

- fix TS typings since `yarn build` was failing on my machine.
- also fixed the dashboard navlink (it was always active on my end)

fix(web): TS typings and always active navbar link

---

.github/workflows/release.yml
Dockerfile
Dockerfile.ci
go.mod
internal/feed/rss.go
internal/feed/rss_test.go

Implements relative URL support for as part 1 for https://github.com/autobrr/autobrr/issues/482

feat(rss): implement relative URL support

---

.github/workflows/release.yml
.goreleaser.yml
goreleaser.Dockerfile

Experimental PR to speed up builds by utliizing GoReleaser to build binaries and images all in one.

build: images with goreleaser

---

internal/indexer/definitions/speedapp.yaml

Fix SpeedApp download url from announces.

fix(indexers): SpeedApp download url

---

internal/database/feed.go
internal/database/feed_cache.go
internal/database/postgres_migrate.go
internal/database/sqlite_migrate.go
internal/domain/feed.go
internal/feed/client.go
internal/feed/rss.go
internal/feed/rss_test.go
internal/feed/service.go
internal/feed/torznab.go
internal/release/service.go
pkg/torznab/torznab_test.go
web/src/forms/settings/FeedForms.tsx
web/src/screens/settings/Feed.tsx
web/src/types/Feed.d.ts

Improve RSS feeds.
Multiple changes in this PR to improve the overall handling of RSS feeds.

feat(feeds): improve RSS

---

internal/indexer/definitions/iplay.yaml

feat(indexers): add iPlay / RMT

---

internal/indexer/definitions/enthralled.yaml

Add Enthralled (ENT) indexer.
Ref #1

feat(indexers): add Enthralled

---

internal/database/filter.go
internal/database/postgres_migrate.go
internal/database/sqlite_migrate.go
internal/domain/filter.go
internal/domain/filter_test.go
web/src/screens/filters/details.tsx
web/src/types/Filter.d.ts

Filter for raw releaseTags string from announce. Only for people who know they need it.

feat(filters): filtering for raw releaseTags

---

internal/domain/filter.go
internal/domain/filter_test.go

Bad check for `except categories`.

fix(filters): except categories

---

internal/action/run.go

Add support to set a file name pattern for watch dir files.
Supports variables like other fields.
Examples:
`/mnt/watch/[{{.Indexer}}]{{.TorrentName}}.torrent` > `/mnt/watch/[mock]Torrent.Name-GROUP.torrent`
`/mnt/watch/{{.Indexer}}-{{.TorrentName}}.torrent` > `/mnt/watch/mockindexer-Torrent.Name-GROUP.torrent`
Fixes #507

feat(actions): watch dir rename file

---

internal/database/download_client.go

Fixes https://github.com/autobrr/autobrr/issues/499

fix(download_client): improve no-client error

---

internal/indexer/definitions/scenehd.yaml

ref badwars message on discord: [link](https://discord.com/channels/881212911849209957/938041584413462539/1039829252218040351)

fix(indexers): scenehd invite cmd

---

internal/domain/release.go
internal/domain/release_test.go
internal/indexer/definitions/huno.yaml

feat(indexers): add HUNO

---

internal/indexer/definitions/huno.yaml

Fixing some missing escapes
https://regex101.com/r/4e129m/3

fix(indexers): HUNO missing escapes on slashes

---

internal/indexer/definitions/huno.yaml

fix(indexers): HUNO fix parsing

---

internal/action/run.go

Make conditional for generating random torrent name more specific

fix(actions): watch dir name check torrent suffix

---

internal/notification/notifiarr.go

Move from url param to auth header for auth.

feat(notifications): Notifiarr use auth header

---

pkg/lidarr/lidarr.go
pkg/radarr/radarr.go
pkg/radarr/radarr_test.go
pkg/readarr/readarr.go
pkg/sonarr/sonarr.go

Improve error handling to catch all errors and not just "unable to parse" errors.

feat(download-clients): improve arr error handling

---

internal/domain/indexer.go
internal/domain/indexer_test.go

Fix parsing of torrentUrl in announce processor.

fix(announce): parse torrentUrl

---

internal/indexer/definitions/uhdbits.yaml

Support new announce format for UHDBits.

feat(indexers): UHDBits support new format

---

cmd/autobrr/main.go
internal/database/filter.go
internal/database/postgres_migrate.go
internal/database/release.go
internal/database/sqlite_migrate.go
internal/domain/filter.go
internal/domain/release.go
internal/filter/service.go
internal/release/service.go
web/src/screens/filters/details.tsx
web/src/types/Filter.d.ts

Add Smart episode check like autodl-irssi.
* Checks all releases for `title`, `season`, `episode` to see if it's newer or not.
Todo:
- Support date based shows like `2022-10-13`

feat(filters): smart episode

---

cmd/autobrr/main.go
internal/auth/service.go
internal/database/user.go
internal/http/auth.go
internal/http/server.go

Log invalid login attempts.
A Fail2ban `failregex` for like `Auth: invalid login \[.+\] from: .+:.+` should be able to grab it.
#585

feat(http): log invalid login attempts

---

internal/auth/service.go
internal/http/auth.go

Improve invalid login handling.

feat(http): improve invalid login handling

---

internal/database/release.go

Fix table sorting of releases.

fix(releases): table sorting

---

internal/domain/releasetags.go
internal/domain/releasetags_test.go
internal/indexer/definitions/orpheus.yaml

Improves logscore parsing.
Fixes #590

feat(releases): improve logscore parsing

---

internal/action/run.go
internal/database/feed.go
internal/domain/feed.go
internal/feed/rss.go
internal/feed/service.go
internal/feed/torznab.go
internal/http/feed.go
internal/scheduler/service.go
pkg/torznab/feed.go
pkg/torznab/torznab.go
web/src/screens/settings/Feed.tsx

Add ability to view the latest fetch of the feed items.
The RSS parser converts the data into JSON and the Torznab parser returns the raw XML.
Resolves #525

feat(feeds): view latest RSS and Torznab feed

---

web/src/screens/settings/DownloadClient.tsx

Branch name says it all - i can't indent correctly.
ESLint screamed at me to fix it so i did.
I'm stupid. Fixed my stupidity.

refactor(web): fix indentation

---

internal/indexer/definitions/pixelhd.yaml

feat(indexers): add PixelHD

---

internal/indexer/definitions/aither.yaml

Add Aither
ref https://github.com/autobrr/autobrr/issues/1
Thank you @nuxencs for assisting with the regex pattern 😃

feat(indexers): add Aither

---

internal/indexer/definitions/ant.yaml

feat(indexers): add ANT

---

internal/indexer/definitions/bitsexy.yaml

Add BitSexy.
Regex playground: https://regex101.com/r/m6Blin/1
Ref #1

feat(indexers): add BitSexy

---

web/src/screens/settings/Feed.tsx

Add baseurl to `View last run` link for Feeds.

fix(feeds): view last run with baseurl

---

internal/indexer/definitions/iptorrents.yaml

https://regex101.com/r/YtdL46/1

fix(indexers): IPT regex

---

internal/indexer/definitions/aither.yaml
web/src/forms/settings/IndexerForms.tsx

Add network from Indexer setup with network password. Used by Aither and custom indexers.

feat(irc): add with network password

---

internal/indexer/definitions/funfile.yaml

https://regex101.com/r/LO2ET8/1- updated with fresh announces.

feat(indexers): add funfile

---

internal/announce/announce.go
internal/domain/indexer.go
internal/indexer/definitions/pixelhd.yaml

Support ignore lines for irc parsing.

feat(indexers): irc parse support ignoring lines

---

internal/indexer/definitions/funfile.yaml

Line 2 of their announce is only listed when there is a scene release.
~~This regex should solve that.~~
https://regex101.com/r/1JI657/1

fix(indexers): funfile single line parsing

---

web/src/screens/filters/action.tsx
web/src/screens/filters/details.tsx

To avoid errors when user clears the field and tries to save. 
Ref https://github.com/autobrr/autobrr/issues/650

fix(filters): Set NumberFields to required

---

internal/feed/torznab.go

The current implementation for Torznab feed uses the `downloadvolumefactor` attribute to set the freeleech status based on the attribute value being `"0"`. However, this does not follow the [specification](https://torznab.github.io/spec-1.3-draft/revisions/1.2-Torznab-Download-Upload-Factors.html) where it is outlined how `downloadvolumefactor` has a decimal value.
This PR aims to solve this problem and extend the functionality by parsing the value as a decimal number and setting the freeleech percentage accordingly. Invalid values are ignored, but a debug message is logged. For the freeleech percentages 25, 50, 75 and 100 an additional bonus is added, but it is unclear to me how bonuses are further used.
If any changes are required, please let me know.

enhancement(feeds): torznab freeleech percentage

---

config.toml
internal/config/config.go
internal/domain/config.go
internal/logger/logger.go

Make the log size and amount of log backups configurable via config.

feat(logging): make log size and log backups configurable

---

internal/action/qbittorrent.go
internal/domain/client.go
web/src/components/inputs/input_wide.tsx
web/src/components/inputs/select.tsx
web/src/domain/constants.ts
web/src/forms/settings/DownloadClientForms.tsx

Check rules for speed threshold conditionally.

feat(downloadclients): qBit rules add speed threshold condition

---

internal/indexer/definitions/nebulance.yaml

This needs to be merged when the new announcer goes live.

fix(indexers): new announcer for Nebulance

---

internal/indexer/definitions/funfile.yaml

As reported here: https://discord.com/channels/881212911849209957/1066228159080575066
Closes #664

fix(indexers): Funfile download URL

---

internal/domain/release.go
internal/indexer/definitions/animebytes.yaml

Tested it, should be good to go.

fix(releases): force capture titles

---

internal/indexer/definitions/lst.yaml

add LST
https://regex101.com/r/VFyKoK/1
Closes #672

feat(indexers): add LST

---

.gitignore
Makefile
cmd/autobrr/main.go
config.toml
internal/config/config.go
internal/config/config_test.go
internal/domain/config.go
internal/http/config.go
internal/http/middleware.go
internal/http/server.go
internal/http/update.go
internal/scheduler/jobs.go
internal/scheduler/service.go
internal/server/server.go
internal/update/update.go
pkg/version/version.go
pkg/version/version_test.go
web/src/api/APIClient.ts
web/src/screens/Base.tsx
web/src/screens/settings/Application.tsx
web/src/types/Config.d.ts
web/src/types/Irc.d.ts
web/src/types/Update.d.ts
web/src/utils/Context.ts

Show new updates in dashboard.
Other work:
- add request logger
- minor api restructure
Resolves #319 and #267

feat: show new updates in dashboard

---

internal/indexer/definitions/skipthetrailers.yaml

feat(indexers): add SkipTheTrailers (STT)

---

internal/indexer/definitions/alpharatio.yaml

https://regex101.com/r/0UidSd/1

fix(indexers) alpharatio infourl

---

internal/indexer/definitions/red.yaml

https://regex101.com/r/lTYwCu/1

fix(indexers): redacted infourl

---

internal/config/config.go
internal/config/config_test.go
internal/http/config.go
web/src/domain/constants.ts
web/src/domain/routes.tsx
web/src/screens/Settings.tsx
web/src/screens/settings/Application.tsx
web/src/screens/settings/Irc.tsx
web/src/screens/settings/Logs.tsx
web/src/screens/settings/index.ts
web/src/types/Config.d.ts

Make it possible to set log level from settings in the UI.

feat(settings): set log level

---

internal/http/logs.go
internal/http/server.go
web/src/api/APIClient.ts
web/src/screens/Logs.tsx
web/src/screens/settings/Application.tsx
web/src/screens/settings/Logs.tsx
web/src/types/Config.d.ts

List log files if logPath is set and make them downloadable.
**Logs page**
**Settings / Logs page**

feat(logs): list log files and make downloadable

---

Dockerfile
Dockerfile.ci

Add pkg `jq` to image.
Fixes #689

build(docker): add pkg `jq`

---

internal/action/porla.go
internal/action/run.go
internal/download_client/connection.go
pkg/jsonrpc/jsonrpc.go
pkg/porla/client.go
pkg/porla/domain.go
pkg/porla/methods.go
web/src/forms/settings/DownloadClientForms.tsx
web/src/screens/filters/action.tsx

feat(download-clients): porla implement rules

---

internal/indexer/definitions/ptfiles.yaml

Add  PTF -  https://regex101.com/r/xjKAcY/1
Ref https://github.com/autobrr/autobrr/issues/1
Thanks to qmayer for providing it!

feat(indexers): add PTFiles (PTF)

---

web/src/screens/dashboard/ActivityTable.tsx
web/src/screens/dashboard/Stats.tsx
web/src/screens/releases/ReleaseTable.tsx

Whenever the release table is loading, we're presented with a "Loading..." message. This text is black and nobody has probably noticed it in dark mode.
This improves on that by pulsating the skeletons until they are fully loaded.

enhancement(web): stats and releases pretty loading

---

.github/workflows/release.yml

build: always run test job

---

.goreleaser.yml

Disable CGO during goreleaser build.

build: force disable cgo

---

internal/indexer/definitions/newznab_generic.yaml

Add missing generic newznab definition.

fix(indexers): add generic newznab definition

---

internal/action/exec.go
internal/action/exec_test.go
internal/action/run.go
internal/action/service.go
internal/domain/action.go
internal/release/service.go

Working fix for torrent data macro parsing.

fix(macros): torrentdata parsing

---

internal/domain/event.go
internal/domain/notification.go
internal/domain/release.go
internal/notification/notifiarr.go

also update comments
Fixes #761

fix(newznab): Use valid usenet release protocol for Starrs

---

internal/feed/newznab.go
internal/feed/torznab.go

Speculative fix for Max Age not working for items retrieved from Torznab / Newznab.

fix(feeds): implement max_age for torznab/newznab

---

web/src/components/data-table/Cells.tsx

fix(releases): mismatched timestamp in list

---

internal/feed/newznab.go
internal/feed/torznab.go
pkg/newznab/feed.go
pkg/torznab/feed.go
pkg/torznab/torznab.go

Fix category parsing for torznab and newznab feeds.

fix(feeds): torznab newznab category parsing

---

web/src/screens/filters/list.tsx

fix(filters): drop down menu z-index

---

internal/http/logs.go

Thanks for noticing @KyleSanderson

refactor(logs): use zerolog instead of log

---

pkg/newznab/feed.go
pkg/torznab/feed.go

Fixes https://github.com/autobrr/autobrr/issues/754

fix(feeds): torznab newznab pubdate parsing

---

internal/indexer/definitions/thedarkcommunity.yaml

feat(indexers): add TheDarkCommunity

---

web/src/components/inputs/input.tsx

Small cosmetic bug i came across during testing for the migration to vite.

fix(web): PasswordField eye icon alignment

---

internal/indexer/definitions/orpheus.yaml

https://regex101.com/r/pHwz9e/1

fix(indexers): OPS parsing

---

internal/domain/release.go
internal/indexer/definitions/polishsource.yaml

Debug issues with polishsource downloads.

fix(indexers): polishsource downloads

---

internal/indexer/definitions/ianon.yaml

Add iAnon, successor to BrokenStones.

feat(indexers): add iAnon

---

internal/domain/indexer.go
internal/filter/service.go
internal/http/indexer.go
internal/indexer/api.go
internal/indexer/service.go
internal/mock/indexer_api.go
pkg/btn/btn.go
pkg/btn/btn_test.go
pkg/btn/client.go
pkg/ggn/ggn.go
pkg/ggn/ggn_test.go
pkg/ptp/ptp.go
pkg/ptp/ptp_test.go
pkg/red/red.go
pkg/red/red_test.go
web/src/api/APIClient.ts
web/src/components/panels/index.tsx
web/src/forms/settings/IndexerForms.tsx
web/src/types/Indexer.d.ts

Add button in indexer settings to test indexer api clients.
Fixes #747

feat(indexers): test API from settings

---

web/index.html
web/src/App.tsx
web/src/forms/filters/FilterAddForm.tsx
web/src/forms/settings/APIKeyAddForm.tsx
web/src/forms/settings/DownloadClientForms.tsx
web/src/forms/settings/FeedForms.tsx
web/src/forms/settings/IndexerForms.tsx
web/src/forms/settings/IrcForms.tsx
web/src/forms/settings/NotificationForms.tsx
web/src/screens/Base.tsx
web/src/screens/auth/login.tsx
web/src/screens/filters/details.tsx
web/src/screens/filters/list.tsx
web/src/screens/settings/Api.tsx
web/src/screens/settings/Application.tsx
web/src/screens/settings/DownloadClient.tsx
web/src/screens/settings/Feed.tsx
web/src/screens/settings/Irc.tsx
web/src/screens/settings/Logs.tsx
web/src/screens/settings/Releases.tsx

Fix issue where Newznab indexers would crash because of missing settings.
Also unifi usage of queryContext.

fix(indexers): test API button

---

web/src/screens/auth/login.tsx

added check for failed login as well remove user when visiting login.

fix(web): unrecoverable unauthorized error

---

cmd/autobrrctl/main.go
internal/auth/service.go
internal/database/user.go
internal/domain/user.go
internal/http/action.go
internal/http/apikey.go
internal/http/auth.go
internal/http/download_client.go
internal/http/encoder.go
internal/http/feed.go
internal/http/filter.go
internal/http/indexer.go
internal/http/irc.go
internal/http/notification.go
internal/http/release.go
internal/user/service.go

Fixes issues with onboarding.
Fixes #846

fix(onboarding): could not create user

---

internal/domain/macros.go

Add "Category" and "Categories" to available filter variables, ie available as `{{ .Category }}`.

feat(macros): add Category and Categories

---

internal/indexer/definitions/ianon.yaml

feat(indexers): iAnon parse category and freeleech

---

web/src/domain/constants.ts
web/src/forms/settings/DownloadClientForms.tsx

Pretty minor, we stylize other product names per their published title, so lets do this one too.

chore(web): Sabnzbd -> SABnzbd

---

.gitignore
internal/http/auth.go

Specualtive fix or invlaid session errors.
Fixes #887

fix(auth): invalid session error

---

.github/workflows/release.yml

build(ci): goreleaser optimize uploads

---

internal/action/run.go
internal/filter/service.go
test/mockindexer/main.go

Increase timeout for webhooks in external filters and actions.

fix(webhooks): increase timeout

---

web/src/screens/filters/list.tsx

Fix filter list status all button.
The change in this previous PR did part of it https://github.com/autobrr/autobrr/pull/899

fix(filters): list show status all

---

internal/indexer/definitions/xspeeds.yaml

Update the help info line for the Passkey.

fix(indexers): xspeeds update passkey help

---

go.mod
go.sum
internal/action/deluge.go
internal/download_client/connection.go

Fix issue with Deluge v1 not setting `save path`.
Fixes #727

fix(downloadclients): Deluge v1 save path

---

web/src/screens/filters/details.tsx

Since #872 has been merged it was proposed that we lock the freeleech field when freeleech has been set to true.

enhancement(web): disable freeleech percent when freeleech is toggled

---

.gitignore
Makefile

Update to use pnpm in Makefile. Looks like this was missed in #919.

chore(build): Use pnpm in Makefile

---

internal/http/auth.go

This should fix issues users are having with broken frontend state and not being able to login properly.

fix(auth): too restrictive session handling

---

internal/indexer/definitions/hebits.yaml

https://github.com/autobrr/autobrr/pull/656#issuecomment-1553027753

fix(indexers): hebits use full category

---

web/src/screens/Logs.tsx

This was fixed in https://github.com/autobrr/autobrr/pull/948

chore(logs): remove warning text saying no scrollback

---

internal/indexer/definitions/morethantv.yaml

Ref https://github.com/autobrr/autobrr/pull/967#discussion_r1213666802

fix(indexers): update mtv network for consistency

---

internal/indexer/definitions/sharewood.yaml

Added the French Sharewood indexer on autobrr. Closes my own Request #966.

feat(indexers): add Sharewood

---

internal/indexer/definitions/tsc.yaml
internal/indexer/definitions/tsc.yml

Added german tracker TorrentSectorCrew.
Ref #1

feat(indexers): add TorrentSectorCrew

---

internal/database/irc.go
internal/domain/irc.go
internal/irc/service.go

Fixes issue when creating IRC network channel due to missing/nil context.

fix(irc): panic when creating indexer with irc

---

web/package.json
web/pnpm-lock.yaml

- upgrade pnpm to 8.6.2
- upgrade vite to 4.3.9
- remove devDependencies (our app do not have concept of runtime, dont make sense have the environments)
- fix pnpm.overrides

chore(web): update package.json and pkgs

---

internal/database/action.go

Fix replaying of actions with Watch dir and Exec cmd.

fix(actions): replay watch dir and exec cmd

---

internal/http/apikey.go
internal/http/feed.go
internal/http/filter.go
internal/http/indexer.go
internal/http/irc.go
internal/http/notification.go

Improve HTTP api error handling.

feat(http): improve error handling

---

web/src/index.css
web/src/screens/settings/Irc.tsx

- inherit text-sm and cursor-point to avoid repeated code
- add mouse hover and event click to the entire row (it had a small gap that wasnt being triggered)
- fix react key to use elements.id instead of array position (also removed repeated keys)
- fix little square corner on the scrollbar

feat(web): improve irc view 

---

internal/indexer/definitions/nebulance.yaml

https://regex101.com/r/mL5Rqy/1

fix(indexers): nebulance regex pattern

---

web/src/screens/Base.tsx
web/src/screens/settings/Application.tsx
web/src/screens/settings/Feed.tsx

https://github.com/autobrr/autobrr/security/code-scanning/1
https://github.com/autobrr/autobrr/security/code-scanning/2
https://github.com/autobrr/autobrr/security/code-scanning/3

fix(web): potentially unsafe external links

---

internal/database/action.go
internal/database/download_client.go
internal/database/feed_cache.go
internal/database/filter.go
internal/database/irc.go
internal/database/release.go
internal/database/user.go
internal/domain/action.go
internal/domain/filter.go
internal/filter/service.go
internal/http/filter.go
web/src/screens/filters/Details.tsx
web/src/screens/filters/External.tsx
web/src/types/Filter.d.ts

Fix store and update filters after #1030.

fix(filters): store and update with no external filters

---

internal/indexer/definitions/ant.yaml

Confirmed this is the new IRC format announced coming from ant.

feat(indexers): support improved ANT announce

---

internal/database/feed_cache.go
internal/feed/service.go
internal/http/feed.go
web/src/api/APIClient.ts
web/src/screens/settings/Feed.tsx

Add ability to clear feed cache.

feat(feeds): clear feed cache

---

web/package.json

build(deps): bump pnpm

---

internal/indexer/definitions/iplay.yaml

Port changed to 6668 due to botnet attack

fix(indexers): update iPlay IRC port

---

internal/domain/feed.go
internal/feed/service.go
web/src/screens/settings/Feed.tsx
web/src/types/Feed.d.ts

Show next run for feed if active.
Fixes #984

feat(feeds): show next run

---

internal/indexer/definitions/digitalcore.yaml

Add support for tags on DigitalCore announce.
https://regex101.com/r/GrIUaf/1
Fixes #1031

feat(indexers): DigitalCore support tags

---

web/package.json
web/pnpm-lock.yaml
web/src/index.tsx
web/src/utils/index.ts

added missing Buffer definition for Stacktracey, made date functions …more robust against undefined values
enhancement: made simplifyDate and IsEmptyDate prone against undefined values
fix: added a global Buffer definition (apparently required by Stacktracey)

enhancement(web): improve functionality of utility components

---

web/src/components/inputs/input.tsx
web/src/screens/filters/Action.tsx

fix(web): actions ratio limit support decimal values

---

web/src/screens/filters/List.tsx

fix(web): floating "Import filter" dropdown button

---

web/src/utils/Context.ts

Set initial context state correctly by triggering onSet callbacks.

fix(web): improve initial context state

---

web/src/components/panels/index.tsx

fix: slideover propagation bug which was present when one added IRC networks and interacted with TextFields (the irc network would toggle itself)

fix(web): slideover propagation bug

---

web/src/components/panels/index.tsx
web/src/screens/settings/Irc.tsx

Fix propagation bug with IRC network table dropdown.

fix(web): cant update from settings panels

---

web/src/forms/settings/IndexerForms.tsx

fix: tooltips in IndexerForms.tsx
chore: linting

fix(web): Add and update Indexer tooltips

---

internal/indexer/definitions/reelflix.yaml

Closes #1126
Tested and successfully fetched a file.
Ref #1

feat(indexers): add ReeFflix

---

internal/indexer/definitions/subsplease.yaml
internal/indexer/definitions/tokyotoshokan.yaml

feat(indexers): Add tests to subsplease
feat(indexers):  Add infourl to subsplease

feat(indexers): IRC do not require auth for irc.rizon.net

---

internal/indexer/definitions/bemaniso.yaml

Closes https://github.com/autobrr/autobrr/issues/1135
Untested as no account on bemaniso.ws
Ref https://github.com/autobrr/autobrr/issues/1
edit (martyluky): https://regex101.com/r/gHa2GT/2

feat(indexers): add Bemaniso

---

internal/database/indexer.go
internal/irc/service.go

Fix to send empty array for lists and not null.

fix(http): do not send null for empty arrays

---

internal/notification/pushover.go

Add size to Pushover notification.
Fixes #1117

feat(notifications): Pushover add size

---

internal/indexer/definitions/torrenthr.yaml

feat(indexers): add TorrentHR

---

internal/http/config.go
web/src/screens/settings/Application.tsx
web/src/screens/settings/Logs.tsx
web/src/types/Config.d.ts

Add more app info.
* database type used
* application binary path
* config path

feat(web): show more app info

---

internal/indexer/definitions/nebulance.yaml

Fix for NBL regex.
Title should now be parsed without any extra values.
https://regex101.com/r/XNRxjd/2

fix(indexers): NBL irc announce regex

---

internal/database/indexer.go
internal/domain/indexer.go
internal/http/indexer.go
internal/indexer/service.go
web/src/api/APIClient.ts
web/src/screens/settings/Indexer.tsx
web/src/screens/settings/Irc.tsx

The idea is the make it similar to the IRC page, also the code have been taken from there.
The issue Im currently facing here is the `mutation` at Indexers.tsx:131 it seems to override everything is sent... I can not spread the indexers because it refuses with `cannot unmarshal array into Go ... something` and looking at the onSubmit method at IndexesForms.tsx:317 it does **a lot** of things...
So... Im begging some help here :D

fix(indexes): toggle on and off with switch

---

web/src/screens/filters/Action.tsx

fix(web): actions tooltip links

---

internal/database/notification.go
internal/domain/notification.go
internal/notification/gotify.go
internal/notification/service.go
web/src/domain/constants.ts
web/src/forms/settings/NotificationForms.tsx
web/src/screens/settings/Notifications.tsx
web/src/types/Notification.d.ts

Add Gotify notification provider.
The icon is a simplified version from their github repo: https://github.com/gotify/logo/blob/master/gotify-logo-notification.svg
Fixes #513

feat(notifications): Add Gotify

---

internal/indexer/definitions/subsplease.yaml

This change aims to parse any multiple-word title to populate the title macro.

feat(indexers): SubsPlease parse title

---

internal/database/release.go
internal/domain/release.go
internal/http/release.go

Fixes release search with Postgres.
Needs a refactor for a proper fix. The query can likely be improved.
Fixes #1169

fix(releases): search with postgres

---

internal/action/transmission.go
web/src/screens/filters/Action.tsx

Add Label to Transmission actions.
Fixes #1193

feat(clients): Transmission set label

---

internal/indexer/definitions/theoldschool.yaml

Add indexer TheOldSchool.
Related #1

feat(indexers): add TheOldSchool

---

go.mod
go.sum

Update go-qbittorrent to `v1.7.1`.
Fixes #1213

chore(deps): update go-qbittorrent to v1.7.1

---

web/src/screens/settings/Application.tsx

Commit is always empty on official builds. This PR hides Commit and Build Date if empty.

feat(settings): hide empty fields

---

internal/feed/rss.go

Fix sometimes missing key for feed cache.

fix(feeds): feed cache key

---

internal/config/config.go

fix(config): prevent overwriting default logPath

---

internal/indexer/definitions/abnormal.yaml

Add ABNormal indexer.
Related #1

feat(indexers): add ABNormal

---

internal/indexer/definitions/milkie.yaml

This is needed to prevent redirects www to non-www.

feat(indexers): update base url for Milkie

---

internal/database/filter.go
internal/database/postgres_migrate.go
internal/database/sqlite_migrate.go
internal/domain/filter.go
internal/filter/service.go
web/src/screens/filters/Details.tsx
web/src/screens/filters/External.tsx
web/src/screens/filters/List.tsx
web/src/types/Filter.d.ts

Tested and works great.
Semi-dupe of #1238

fix(filters): external webhook remove jitter

---

.dockerignore
CODE_OF_CONDUCT.md

This would be great inorder to remind people to be on their best behavior when interacting with each other in this project.

chore: Add CODE_OF_CONDUCT

---

README.md

Added a ToC, a contributing section, a placeholder for CoC, and other small changes.

docs: readme improvements and additions

---

.github/workflows/codeql.yml

Speculative fix for coceql node cache error.

fix(codeql): empty node cache error

---

internal/indexer/definition_test.go
internal/indexer/definitions/animebytes.yaml

Fixes a regex bug for animebytes.

fix(indexers): animebytes parsing

---

README.md

Added coc to readme and did some markdownlinting.

docs: add coc to readme

---

web/src/screens/settings/DownloadClient.tsx
web/src/screens/settings/Feed.tsx
web/src/screens/settings/Notifications.tsx

fix(web): improve responsiveness on settings pages

---

internal/config/config.go

Fixes a panic from changing log level / config.

fix(config): log level change causes panic

---

internal/action/qbittorrent.go

We did not check for the enabled state of the rule it seems. This should solve that.
Ref: https://discord.com/channels/881212911849209957/881967548143403058/1185543801494843452

fix(actions): qBit handle `Ignore slow torrents` rule correctly when disabled

---

web/src/screens/settings/Irc.tsx

This PR makes improvements to the IRC settings page.
- Unify font size for network, channels and announce logs.
- Improve mobile view
- Visually connect network row to dropdown area
- some smaller alignment changes

enchancement(web): IRC settings layout

---

web/package.json
web/pnpm-lock.yaml
web/src/components/tooltips/Tooltip.tsx

Closes #1194 
Tested and working as expected on iPad and iPhone with Safari. Someone should test on Android.

fix(web): improve tooltip responsiveness and click-through

---

internal/database/postgres_migrate.go
internal/database/sqlite_migrate.go
web/src/forms/settings/FeedForms.tsx

Updated help text.
Partially closes #1280.

enhancement(feeds): change max age default value to 0

---

go.mod
go.sum
internal/action/deluge.go
web/src/screens/filters/sections/action_components/ActionDeluge.tsx

Closes #1258 
Relies on https://github.com/autobrr/go-deluge/pull/6

feat(actions): deluge v2 add skip recheck

---

internal/domain/notification.go
internal/http/auth_test.go
internal/notification/message_builder.go
internal/notification/ntfy.go
internal/notification/service.go
web/src/domain/constants.ts
web/src/forms/settings/NotificationForms.tsx
web/src/screens/settings/Notifications.tsx
web/src/screens/settings/_components.tsx
web/src/types/Notification.d.ts

Add support for [ntfy.sh](https://ntfy.sh) notifications.
Fixes #535

feat(notifications): add ntfy support

---

go.mod
go.sum
internal/domain/notification.go
internal/notification/service.go
internal/notification/shoutrrr.go
web/src/domain/constants.ts
web/src/forms/settings/NotificationForms.tsx
web/src/screens/settings/Notifications.tsx
web/src/types/Notification.d.ts

Add support for [Shoutrrr](https://containrrr.dev/shoutrrr/).
Supported services:
* Bark
* Discord
* Email
* Gotify
* Google Chat
* IFTTT
* Join
* Mattermost
* Matrix
* Ntfy
* OpsGenie
* Pushbullet
* Pushover
* Rocketchat
* Slack
* Teams
* Telegram
* Zulip Chat
* Generic Webhook
Closes #583 
Closes #867

feat(notifications): add Shoutrrr support

---

internal/notification/ntfy.go
internal/notification/shoutrrr.go

Fix isEnabled check for ntfy and Shoutrrr notifications.

fix(notifications): ntfy and shoutrrr enabled check

---

internal/database/release.go
internal/domain/release.go
web/src/components/data-table/Cells.tsx
web/src/components/data-table/index.tsx
web/src/screens/dashboard/ActivityTable.tsx
web/src/screens/releases/ReleaseTable.tsx
web/src/types/Release.d.ts
web/src/utils/index.ts

Show more details in releases list view.
Screenshots:
Closes #1004

feat(releases): show details in list view

---

.github/workflows/release.yml

Add Go test summary output to action.

build(ci): add Go test summary

---

internal/database/filter.go

This is the extra comment I mentioned wanting to add in https://github.com/autobrr/autobrr/pull/1285

docs(filters): explain GetDownloadsByFilterId

---

internal/database/filter.go
internal/database/postgres_migrate.go
internal/database/sqlite_migrate.go
internal/domain/filter.go
internal/domain/release.go
internal/feed/torznab.go
web/src/screens/filters/Details.tsx
web/src/screens/filters/_const.ts
web/src/screens/filters/sections/Advanced.tsx
web/src/types/Filter.d.ts

This PR implement feature for min and max seeders/leechers filtering
Seeders/Leechers filtering will improve share rate for torrents.
closes #815

feat(filters): implement min and max seeders/leechers filtering for Torznab feeds

---

web/src/api/APIClient.ts

Fix search query for releases page.
Broke during the refactor of release struct fields.

fix(releases): search query

---

internal/http/auth.go
internal/http/auth_test.go
internal/http/middleware.go
web/src/api/APIClient.ts

This should fix issues with specifically Chromium based browsers.

fix(auth): force invalidate invalid session cookies in middleware

---

.gitignore
test/mockindexer/README.md
test/mockindexer/irc/client.go
test/mockindexer/irc/handlers.go
test/mockindexer/irc/server.go
test/mockindexer/main.go

Update to MockIndexer:
- Add support for RSS feeds
- Add support for Webhooks
- Improvements to mock IRC server
- Minor improvements to the webui

feat(mockindexer): support feeds and webhooks

---

CONTRIBUTING.md
README.md

docs: add contribution guide

---

internal/indexer/definitions/toonsforme.yaml

feat(indexers): add ToonsForMe

---

internal/indexer/definitions/ant.yaml

see title.
A user on discord has made us aware about a news post about this change.

fix(indexers): ANT new irc address

---

web/src/screens/releases/ReleaseTable.tsx

This PR further cleans up the code for the loading animation of the releases table.

enhancement(web): debloat release loading animation

---

web/src/screens/filters/List.tsx

When the filters query takes too long to finish, a message will be shown that on filters have been created.
This PR implements a loading animation similar to the release table one, just for the filters list.

enhancement(web): filters list query loading animation

---

internal/indexer/definitions/nyaa.yaml

Add (unofficial) Nyaa announce maintained by @Flupster

feat(indexers): add Nyaa

---

README.md

Autobrr is saltbox app not sandbox app
https://docs.saltbox.dev/apps/autobrr/

docs(installers): update Saltbox instructions

---

internal/database/postgres_migrate.go
internal/database/sqlite_migrate.go

Force update IRC server addr for ANT and NBL. Will only update if the old addr is used.

fix(irc): force update ANT and NBL irc server addr

---

internal/domain/macros.go
internal/domain/macros_test.go

Expose `Tags` as a comma separated list.

feat(macros): add Tags

---

internal/indexer/service.go
pkg/sanitize/sanitize.go

Implement basic user input sanitizing.

feat(indexers): sanitize user input

---

internal/database/postgres_migrate.go
internal/database/sqlite_migrate.go
internal/indexer/definitions/animebytes.yaml

This PR prepares autobrr for the new AB irc server address.
In case the database migration for the name column is unwanted,  
please express your concerns and i will revert that change.
~Couldn't test this properly since announces at AB are not working currently.~
EDIT: Tested and works.

fix(indexers): AB new irc address

---

README.md

Move Swizzin shared installer from script to box.

docs: update installers

---

internal/notification/ntfy.go

Header value should be text/plain and not text/pain

fix(notifications): ntfy.sh Typo in Content-Type header value

---

cmd/autobrrctl/main.go
internal/auth/service.go

fix(autobrrctl): prevent empty password

---

internal/domain/release_test.go
web/src/domain/constants.ts

This PR adds:
- AHDTV tag to sources
- MPEG-2 tag to codecs
Also sort alphabetically.

feat(filters): add sources and codecs

---

internal/indexer/definitions/huno.yaml

It now uses the site username and irc key

feat(indexers): update Hawke-UNO irc auth

---

web/src/forms/settings/IndexerForms.tsx

Set IRC channel pass when adding indexer.
In the definition this needs to be added.
```yaml
- name: channels.password
type: secret
required: true
label: Channel Password
help: Channel password
```

feat(irc): set channel pass on indexer add

---

internal/indexer/definitions/lillesky.yaml

Update parsing to use new autodl channel and format.

fix(indexers): LilleSky update irc announce parsing

---

internal/indexer/definitions/btfiles.yaml

feat(indexers): BTFiles add channel password field

---

internal/indexer/definitions/keepfrds.yaml

https://regex101.com/r/X5fdZu/1

feat(indexers): add KeepFRDS

---

internal/domain/macros.go
internal/domain/macros_test.go

Verified and tested with mockindexer.
Closes #1481 and #1491

feat(macros): add Artists

---

go.mod
go.sum

https://github.com/moistari/rls/compare/v0.5.10...v0.5.12

build(deps): bump rls to v0.5.12

---

web/src/screens/releases/ReleaseTable.tsx

feat(releases): replace misc info in incognito mode

---

web/src/api/query_keys.ts
web/src/components/ExternalLink.tsx

missed two files... well, that happened..

chore: add missing license headers

---

internal/feed/rss.go
internal/feed/rss_test.go

Try to parse magnet URI from enclosure.
Fixes #1513

fix(feeds): parse magnet URI from enclosure

---

internal/indexer/definitions/danishbytes.yaml

chore(indexers): danishbytes remove unused url

---

internal/indexer/definitions/hdonly.yaml

feat(indexers): add HD-Only

---

web/src/screens/settings/Account.tsx

fix(web): responsive account settings

---

internal/indexer/definitions/finelite.yaml

Closes https://github.com/autobrr/autobrr/issues/1561

feat(indexers): add FinElite

---

web/src/api/APIClient.ts

Since there still seem to be some auth woes (see recent report in discord)  
we need more meaningful error messages in the toast to figure out what's causing those issues.
With this PR the toast will return more meaningful error message in future.

enhancement(web): return more meaningful error message in toast

---

web/index.html
web/package.json
web/src/components/modals/index.tsx
web/src/components/panels/index.tsx
web/src/components/tooltips/Tooltip.tsx
web/src/forms/filters/FilterAddForm.tsx
web/src/forms/settings/APIKeyAddForm.tsx
web/src/forms/settings/DownloadClientForms.tsx
web/src/forms/settings/IndexerForms.tsx
web/src/forms/settings/IrcForms.tsx
web/src/forms/settings/NotificationForms.tsx
web/src/routes.tsx
web/src/screens/filters/Importer.tsx

This PR fixes the build errors for the June 2024 npm updates in #1571 
Additionally this PR refactors the frontend code to work with HeadlessUI v2.

refactor(web): headlessui v2

---

internal/indexer/definitions/bithumen.yaml

feat(indexers): add BitHUmen

---

web/src/components/tooltips/Tooltip.tsx

This PR fixes the weird tooltip placement on the release name column of the ActivityTable.

fix(web): tooltip placement

---

internal/indexer/definitions/fearnopeer.yaml

Fix for the announce pattern regex to properly capture announces with multiple sets of brackets inside, typically music releases.
Fixes #1579

fix(indexers): FearNoPeer irc regex for music

---

internal/indexer/definitions/satclubbing.yaml

feat(indexers): add SATClubbing

---

web/src/screens/filters/Details.tsx

Add validation to require Max Downloads Per to be set if Max Downloads is greater than 0.

feat(filters): add validation for max downloads unit

---

internal/indexer/definitions/insane.yaml

feat(indexers): add iNSANE

---

internal/indexer/definitions/hdonly.yaml

feat(indexers): HD-Only add size

---

internal/indexer/definitions/seedpool.yaml

feat(indexers): add SeedPool

---

internal/indexer/definitions/satclubbing.yaml

Fix bad url params for SATClubbing download url.

fix(indexers): SATClubbing download url

---

internal/api/service.go
internal/database/api.go
internal/database/api_test.go
internal/domain/api.go
internal/http/apikey.go
internal/http/encoder.go

Refactor API key cache handling.
* Change from slice to map for constant lookup

refactor(http): api key cache handling

---

internal/api/service.go
internal/database/feed.go
internal/database/release.go
internal/http/action.go
internal/http/apikey.go
internal/http/download_client.go
internal/http/encoder.go
internal/http/feed.go
internal/http/filter.go
internal/http/indexer.go
internal/http/irc.go
internal/http/logs.go
internal/http/notification.go
internal/http/release.go
internal/notification/service.go

Add missing methods like FindByID for most entities. 
* general cleanup
* unify param handling
* handle not found errors
* unify err handlers

feat(http): implement missing findByID methods

---

internal/http/logs.go
internal/logger/sanitize.go
internal/logger/sanitize_test.go

Move logs sanitize to logger package.

refactor(logs): move sanitize

---

.github/workflows/codeql.yml
.github/workflows/eslint.yml
.github/workflows/golang-linter.yml

Update Go and Node versions in Action Workflows.

ci(linters): update Go and Node versions

---

internal/feed/rss.go

Fix size parsing of UNIT3D based RSS feeds.
Fixes #1603

fix(feeds): UNIT3D RSS size parsing

---

internal/irc/handler.go

fix(irc): revert lazy announcer check

---

web/src/screens/settings/Irc.tsx

This PR fixes an out of bound options menu in the IRC settings on mobile views.
Thanks to @s0up4200 for debugging this for me and for bringing this to my attention.
Old (left) New (right)

fix(web): irc view mobile optimizations

---

internal/domain/release_test.go

https://goreportcard.com/report/github.com/autobrr/autobrr

chore(tests): correct typos

---

internal/feed/service.go

Fixes an issue with signals handling not working until all feeds were started. We implemented staggered start of feeds with a 5 second delay to not stress the database during feed refresh.
The starting of feeds were blocking and signal.Notify would only start to listen after those were done.

fix(feeds): start feeds in background

---

internal/database/notification.go
internal/database/notification_test.go
internal/domain/notification.go
internal/http/notification.go
internal/notification/discord.go
internal/notification/gotify.go
internal/notification/lunasea.go
internal/notification/notifiarr.go
internal/notification/ntfy.go
internal/notification/pushover.go
internal/notification/service.go
internal/notification/shoutrrr.go
internal/notification/telegram.go

Fix a bug where disabling a notification sender would not have any effect.
Did additional refactoring.

fix(notifications): disable notification and events have no effect

---

internal/releasedownload/download_service.go

A fix for panics during error check when downloading .torrent files.
The check for `*url.Error` will take care of responses being magnet links when expecting a http url.

fix(downloads): handle panic in error check

---

internal/domain/filter.go

Trim user input in filters before comparison.

fix(filters): trim user input

---

internal/indexer/definitions/fearnopeer.yaml

fix(indexer): update suggested nick format for FearNoPeer IRC

---

internal/indexer/definitions/digitalcore.yaml

feat(indexers): DigitalCore parse Tags and Genre

---

internal/indexer/definitions/scenehd.yaml

SceneHD changed IRC server domain to .org.

feat(indexers): update SceneHD IRC server

---

internal/action/exec_test.go
internal/config/config_test.go
internal/domain/client_test.go
internal/domain/filter_test.go
internal/domain/indexer_test.go
internal/domain/macros_test.go
internal/domain/rejections_test.go
internal/domain/releasetags_test.go
internal/feed/rss_test.go
internal/http/auth_test.go
internal/indexer/definition_test.go
internal/indexer/indexer_test.go
internal/logger/sanitize_test.go
internal/notification/message_builder_test.go
pkg/argon2id/argon2id_test.go
pkg/sanitize/sanitize_test.go
pkg/version/version_test.go
pkg/wildcard/match_test.go

Make more tests run in parallel.

feat(tests): add Parallelization where possible

---

ciwindows.Dockerfile

Fix lint warning for entrypoint.

fix(build): Dockerfile windows entrypoint

---

internal/database/postgres_migrate.go
internal/database/sqlite_migrate.go
internal/indexer/definitions/red.yaml
internal/indexer/indexer_test.go
pkg/red/red.go

feat(indexers): REDACTED update urls

---

internal/database/postgres_migrate.go
internal/database/sqlite_migrate.go
internal/domain/release.go
internal/indexer/definitions/seedpool.yaml

Update SeedPool IRC announce format, port and ssl.
Fixes #1825

feat(indexers): update SeedPool IRC announce parsing

---

internal/database/postgres_migrate.go
internal/database/sqlite_migrate.go

Fix typo in url for SeedPool updates.

fix(database): SeedPool migrations

---

internal/indexer/definitions/iplay.yaml

Update iPlay / RMT download url.
Fixes #1414

fix(indexers): iPlay RMT update download url

---

Makefile

- Added tmux-based dev environment - `make dev`
- Added touch command to preserve web/dist/.gitkeep during `make build/web`

feat(makefile): add tmux-based dev environment

---

.github/workflows/release.yml

Don't run the build workflow for changes to files that don't impact the build.

feat(ci): skip build on misc files

---

internal/domain/release.go

fix(releases): set freeleech from downloadVolumeFactor

---

web/src/screens/releases/ReleaseTable.tsx

Restore functionality where clicking stats cards filters the releases table by status.

fix(web): releases status URL filtering

---

.github/workflows/update-indexers.yml
scripts/update-indexers.py

Add Python script and workflow to automatically update indexer documentation in autobrr.com
Features:
- Generate indexers.mdx with IRC and RSS support status
- Generate freeleech.mdx tracking freeleech support
- Sort indexers alphabetically (generic indexers last)
- Filter freeleech table to only show supporting indexers
- Automated daily updates via GitHub Actions

feat(docs): add indexer docs update script

---

.github/workflows/update-indexers.yml
scripts/update-indexers.py

Triggered and confirmed to work: https://github.com/autobrr/autobrr.com/pull/238

fix(ci): update indexers workflow with improved path handling

---

internal/domain/release.go

Improve freeleech parsing, specifically for FunFile.
* capture `fl` as freeleech from vars

feat(releases): improve freeleech parsing

---

web/src/api/QueryClient.tsx
web/src/components/header/Header.tsx
web/src/screens/auth/Login.tsx
web/src/screens/filters/Details.tsx
web/src/screens/filters/NotFound.tsx
web/src/screens/settings/Application.tsx
web/src/screens/settings/Logs.tsx

Remove circular imports.
Supersedes #1415

fix(web): circular dependencies

---

internal/http/auth.go

Only init OIDC handler if it's enabled via the config.

fix(http): init oidc handler if enabled

---

internal/database/postgres_migrate.go
internal/database/sqlite_migrate.go
internal/filter/service.go

Set default `Announce Type` on existing and new filters to `NEW`.

feat(filters): set default `Announce Type` to `NEW`

---

web/src/screens/settings/Lists.tsx

https://discord.com/channels/881212911849209957/881967548143403058/1321727786494332938

fix(lists): toggle toast message

---

web/src/forms/settings/ListForms.tsx

Removed predefined trakt lists from ListTypePlainText

fix(lists): plaintext only accept URLs

---

web/package.json
web/src/domain/constants.ts
web/src/forms/settings/ReleaseForms.tsx
web/src/screens/settings/Lists.tsx
web/src/screens/settings/Proxy.tsx
web/src/screens/settings/Releases.tsx

- Make the page look more similar to the others, if you switch between pages you can notice it.
- I could not 100% fix the overflow when big filters exists, but it looks better.
- Changed the types to a map labels.
- That `browserlist` is not used anymore (since webpack)

feat(lists): ui enhancements

---

internal/database/postgres_migrate.go
internal/database/sqlite_migrate.go
web/src/forms/settings/IrcForms.tsx

Add conditional check to PTP irc channel update to not cause fatal `UNIQUE CONSTRAINT` error during migrations.

fix(database): migrations to update PTP IRC channel

---

internal/domain/list.go
internal/http/list.go
internal/http/webhook.go
internal/list/process_arr_lidarr.go
internal/list/process_arr_radarr.go
internal/list/process_arr_readarr.go
internal/list/process_arr_sonarr.go
internal/list/process_list_mdblist.go
internal/list/process_list_metacritic.go
internal/list/process_list_plaintext.go
internal/list/process_list_steam.go
internal/list/process_list_trakt.go
internal/list/scheduled_jobs.go
internal/list/service.go
internal/list/tags.go
internal/list/tags_test.go
internal/list/title.go
internal/list/title_test.go

Improve parsing and ignore single star values for filters.
Fixes #1912

fix(lists): improve parsing and exclude unwanted characters

---

internal/release/service.go

Truncate long rejections on debug level.

fix(filters): truncate rejections on debug level

---

scripts/update-indexers.py

Fixes detection of freeleech in mappings. Needed to detect freeleech for MAM.

docs: improve freeleech detection in parsing

---

internal/database/notification.go
web/src/forms/settings/NotificationForms.tsx
web/src/types/Notification.d.ts

Missing password from updating and listing NTFY notifications.
Fixes #1947

fix(notifications): update and list password

---

web/src/forms/settings/NotificationForms.tsx

fixes #1834 
This PR fixes the checkboxes in the notification update form not updating it's state unless you click another checkbox.
Left is old. Right is new.
Full disclosure: the Formik part is done by AI 😂

fix(web): notification form checkboxes

---

internal/indexer/definitions/nordicquality.yaml

feat(indexers): add NordicQuality

---

internal/indexer/definitions/darkpeers.yaml

Add new indexer DarkPeers.
Resolves #1985

feat(indexers): add DarkPeers

---

internal/indexer/definitions/rocket-hd.yaml

Add new indexer RocketHD.
Resolves #1997

feat(indexers): add RocketHD

---

internal/indexer/definitions/phoenixproject.yaml

Add new indexer Phoenix Project.

feat(indexers): add PhoenixProject

---

internal/database/filter.go
internal/domain/filter.go
internal/filter/service.go
web/src/screens/filters/List.tsx
web/src/types/Filter.d.ts

Show current download count if max downloads is set in a filter.
Closes https://github.com/autobrr/autobrr/discussions/1660

feat(filters): show current download count in list

---

internal/irc/service.go

During startup, only attach proxy if UseProxy is enabled and the ID is set.

fix(irc): set proxy if use proxy is enabled

---

internal/indexer/definitions/homiehelpdesk.yaml

feat(indexers): add HomieHelpDesk

---

internal/indexer/definitions/xwt.yaml

Add XtremeWrestlingTorrents.
Closes #2014

feat(indexers): add XtremeWrestlingTorrents

---

.github/workflows/codeql.yml
.github/workflows/golang-linter.yml
.github/workflows/release.yml
Dockerfile
ci.Dockerfile
ciwindows.Dockerfile
go.mod
internal/list/process_list_trakt.go
internal/proxy/service.go
pkg/jsonrpc/jsonrpc.go

build(deps): bump Go to 1.24

---

web/src/screens/dashboard/ActivityTable.tsx
web/src/screens/releases/ReleaseTable.tsx
web/src/utils/Context.ts
web/src/utils/index.ts

Persists incognito state using localStorage via `IncognitoContext`
Updates the list of Linux ISOs used in `RandomLinuxIsos`. (Taken from https://distrowatch.com/dwres.php?resource=bittorrent&sortorder=date)
Added a new `RandomIsoTracker` utility to randomize tracker names. (Added fosstorrents to the list)

feat(web): persist releases incognito state

---

internal/indexer/definitions/capybarabr.yaml

This PR updates the CapybaraBR tracker parsing, adding FreeleechPercent and internal fields.

feat(indexers): CapybaraBR parse freeleech and internal

---

internal/domain/filter.go
internal/domain/filter_test.go

Fix for multi year ranges checks.
Ref https://www.reddit.com/r/autobrr/comments/1lpf9qb/rejection_year_not_matching_got_2025_want/

fix(filters): multiple year ranges check

---

internal/indexer/definitions/happyfappy.yaml

feat(indexers): add HappyFappy

---

internal/feed/torznab.go
pkg/torznab/feed.go

Parse author from torznab feed if present.
Fixes #2074

feat(feeds): torznab parse author

---

pkg/version/version.go

Ignore version check for PR tags.

fix(versioncheck): ignore pr tags

---

internal/database/feed_cache.go
internal/feed/cleanup.go
internal/feed/mock.go
internal/feed/newznab.go
internal/feed/rss.go
internal/feed/rss_test.go
internal/feed/service.go
internal/feed/testdata/torznab/caps_response.xml
internal/feed/testdata/torznab/torznab_response.xml
internal/feed/torznab.go
internal/feed/torznab_test.go
pkg/torznab/feed.go
pkg/torznab/testdata/torznab_response.xml
pkg/torznab/torznab_test.go

Fix parsing of torznab attributes, especially downloadvolumefactor/freeleech percent.
Did some more cleanup and improvements like adding tests.
Fixes #2148

fix(feeds): torznab freeleech percent parsing

---

internal/indexer/definitions/homiehelpdesk.yaml

Update HHD announce format after breaking change on their end.
Fixes #2147

fix(indexers): update HomieHelpDesk announce format

---

web/src/screens/Logs.tsx

* N/A
* Trash icon to clear the current logs
* `web/src/screens/Logs.tsx`
1. `go run cmd/autobrr/main.go`
2. `pnpm dev`
* Unsure
* Before:
* After:
* No

feat(web): clear logs view

---

internal/indexer/definitions/darkpeers.yaml

adds support for parsing freeleech tags to darkpeers

feat(indexers): DarkPeers parse freeleech

---

internal/database/postgres_migrate.go
internal/database/sqlite_migrate.go
internal/indexer/definitions/uploadcx.yaml

Update and migrate the IRC network and channel for ULCX.

feat(indexers): update ULCX IRC network address

---

internal/indexer/definitions/fappaizuri.yaml

closes #2173 
Automated download of metadata file upon announce, infourl and torrenturl are tested and working.

feat(indexers): add Fappaizuri

---

internal/domain/client.go
internal/download_client/service.go

Client Test button sends redacted keys if saved before clicking send.

fix(downloadclient): Test sends keys as redacted if saved

---

internal/scheduler/jobs.go
internal/scheduler/ownership.go
internal/scheduler/ownership_windows.go

Fix current user check in TMP cleanup background job.

fix(jobs): tmp cleanup user check

---

.goreleaser.yml
CONTRIBUTING.md
README.md
docs/man/autobrr.1
web/src/components/alerts/ErrorPage.tsx
web/src/components/alerts/NotFound.tsx
web/src/screens/filters/NotFound.tsx

Update Discord invite links to use https://discord.autobrr.com

docs: update Discord invite links

---

internal/indexer/definitions/rastastugan.yaml

feat(indexers): add Rastastugan

---

internal/indexer/definitions/homiehelpdesk.yaml

* Reported on Discord
* new announcer for the irc channel

fix(indexers): HHD add new announcer
